/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * First-run status
         * @description Whether the first-run setup wizard still needs to run. Public.
         */
        get: operations["getSetupStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete first-run setup
         * @description Sets the local admin password, stores the base URL, creates the first org, and logs the admin in. Works once; later calls get 409. Public.
         */
        post: operations["completeSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pluggable type schemas
         * @description JSON Schemas for every registered DNS provider, deploy target, notifier, and signer. The UI renders forms from them.
         */
        get: operations["getMetaSchemas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List organizations
         * @description Organizations visible to the caller.
         */
        get: operations["listOrgs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in as the local admin
         * @description Break-glass local admin login. Sets the cf_session cookie. OIDC login arrives in Phase 2.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Ends the current session and clears the cookie. Requires X-CSRF-Token.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current principal
         * @description The signed-in user, roles, visible orgs, and the CSRF token for mutating requests.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/{section}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Section name, for example general, backup, or issuance_defaults. */
                section: string;
            };
            cookie?: never;
        };
        /**
         * Read a settings section
         * @description Returns the section's JSON Schema and its current value (the default when unset).
         */
        get: operations["getSettingsSection"];
        /**
         * Replace a settings section
         * @description Validates the value against the section schema (422 on failure) and stores it. Admin only. For a secret property (schema "secret": true), send "__unchanged__" or omit the field to keep the stored value, "" to clear it, or any other string to replace it; "__unchanged__" with nothing stored is a 422. Secret values are never echoed back.
         */
        put: operations["putSettingsSection"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/ca-presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List CA presets
         * @description Well-known ACME CAs with their directory URLs and whether they require External Account Binding. Needs cas:read.
         */
        get: operations["listCaPresets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/cas": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        /**
         * List ACME CAs
         * @description CAs of the org sorted by name. Needs cas:read.
         */
        get: operations["listCas"];
        put?: never;
        /**
         * Add an ACME CA
         * @description Needs cas:write (global admin). A preset fills directoryUrl when omitted. Presets that require EAB return 422 without eabKid and eabHmac.
         */
        post: operations["createCa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/cas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Get a CA
         * @description Needs cas:read.
         */
        get: operations["getCa"];
        /**
         * Replace a CA
         * @description Needs cas:write. eabHmac omitted, null or __unchanged__ keeps the stored HMAC; an empty string removes it.
         */
        put: operations["updateCa"];
        post?: never;
        /**
         * Delete a CA
         * @description Needs cas:write. 409 while accounts, certificates or defaults reference it.
         */
        delete: operations["deleteCa"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/acme-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        /**
         * List ACME accounts
         * @description Accounts of the org sorted by email. Needs accounts:read.
         */
        get: operations["listAcmeAccounts"];
        put?: never;
        /**
         * Register an ACME account
         * @description Needs accounts:write. Registers at the CA now (with the CA's EAB) and stores the account key encrypted. A CA rejection returns 502 with the ACME problem in detail.
         */
        post: operations["createAcmeAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/acme-accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Get an ACME account
         * @description Needs accounts:read.
         */
        get: operations["getAcmeAccount"];
        put?: never;
        post?: never;
        /**
         * Delete an ACME account
         * @description Needs accounts:write. Removes the stored account only; it is not deactivated at the CA. 409 while referenced.
         */
        delete: operations["deleteAcmeAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/dns-credentials": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        /**
         * List DNS credentials
         * @description Credentials of the org sorted by name, without secrets. Needs dnscreds:read.
         */
        get: operations["listDNSCredentials"];
        put?: never;
        /**
         * Add a DNS credential
         * @description Needs dnscreds:write. config keys must be properties of the provider schema from GET /meta/schemas; fields with secret true are stored encrypted. Unknown keys, a key with a serverPath schema property, or a provider marked unsupported all return 422.
         */
        post: operations["createDNSCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/dns-credentials/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Get a DNS credential
         * @description Secrets are never returned. Needs dnscreds:read.
         */
        get: operations["getDNSCredential"];
        /**
         * Replace a DNS credential
         * @description Needs dnscreds:write. config is replaced as a whole; a secret field set to __unchanged__ keeps its stored value and a secret field left out is removed. The provider cannot change; 422 if it is (or has since become) marked unsupported.
         */
        put: operations["updateDNSCredential"];
        post?: never;
        /**
         * Delete a DNS credential
         * @description Needs dnscreds:write. 409 while certificates, org defaults or the global defaults reference it.
         */
        delete: operations["deleteDNSCredential"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/dns-credentials/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test a DNS credential
         * @description Needs dnscreds:write. Creates and removes a TXT record at _acme-challenge._certforge-test.<zone> (lego always adds the _acme-challenge label). Provider failures return 200 with ok false; error text has every config value redacted. Past a bounded timeout the response is ok false with error "timed out", but cleanup keeps running in the background. At most 2 tests run at once server-wide; beyond that this returns 503 with Retry-After.
         */
        post: operations["testDNSCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/issuance-defaults": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        /**
         * Get org issuance defaults
         * @description The org level only; null fields inherit from the global settings section issuance_defaults. Needs certs:read.
         */
        get: operations["getOrgIssuanceDefaults"];
        /**
         * Replace org issuance defaults
         * @description Null or omitted fields inherit from global. Applies at each inheriting certificate's next renewal. Needs certs:write.
         */
        put: operations["putOrgIssuanceDefaults"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/issuance-defaults/effective": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        /**
         * Get effective org defaults
         * @description Each field's resolved value and the level it came from (default, global, org). Needs certs:read.
         */
        get: operations["getEffectiveIssuanceDefaults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/certificates": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        /**
         * List certificates
         * @description Needs certs:read. status filters by status; q matches the name and any certificate name; sort is name, notAfter, nextRenewAt or status, with a leading - for descending.
         */
        get: operations["listCertificates"];
        put?: never;
        /**
         * Create a certificate
         * @description Needs certs:write. Names are validated and de-duplicated; the first issuance is queued immediately.
         */
        post: operations["createCertificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/certificates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Get a certificate
         * @description Needs certs:read.
         */
        get: operations["getCertificate"];
        /**
         * Replace a certificate definition
         * @description Needs certs:write. Changing names queues a new issuance; other changes apply at the next renewal.
         */
        put: operations["updateCertificate"];
        post?: never;
        /**
         * Delete a certificate
         * @description Deletes the definition with all versions and attempts; does not revoke. Needs certs:write.
         */
        delete: operations["deleteCertificate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/certificates/{id}/renew": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue now
         * @description Queues an issuance. enqueued is false when one is already queued or running. Needs certs:issue.
         */
        post: operations["renewCertificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/certificates/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * List versions
         * @description Issued versions, newest first. Needs certs:read.
         */
        get: operations["listCertificateVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/certificates/{id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * List issuance attempts
         * @description The 50 newest attempts with step timeline and log. Needs certs:read.
         */
        get: operations["listIssuanceAttempts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/certificates/{id}/versions/{vid}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
                /** @description Certificate version id. */
                vid: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        /**
         * Download a version
         * @description Needs certs:read; the key and combined parts also need keys:export and are recorded in the audit log before anything is sent. One part returns a PEM file, several a zip.
         */
        get: operations["downloadCertificateVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/certificates/{id}/manual-dns": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * List pending manual TXT records
         * @description Records an operator must add; empty unless a manual-dns attempt is waiting. Needs certs:read.
         */
        get: operations["listManualDNS"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/certificates/{id}/manual-dns/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm manual TXT records
         * @description Resumes the waiting attempt. 409 when nothing is waiting or the records expired. Needs certs:issue.
         */
        post: operations["confirmManualDNS"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 problem details, sent with content type application/problem+json. */
        Problem: {
            /** @description Problem type URI; about:blank for generic HTTP errors. */
            type: string;
            /** @description Short, human-readable summary. */
            title: string;
            /** @description HTTP status code. */
            status: number;
            /** @description Explanation specific to this occurrence. */
            detail?: string;
        };
        /** @description An organization; most resources are scoped to one. */
        Org: {
            /**
             * Format: uuid
             * @description Org id.
             */
            id: string;
            /** @description URL-safe identifier, lowercase letters, digits, and hyphens. */
            slug: string;
            /** @description Display name. */
            name: string;
        };
        /** @description A list of organizations. */
        OrgList: {
            /** @description Organizations sorted by name. */
            items: components["schemas"]["Org"][];
        };
        /** @description One registered pluggable type. */
        SchemaEntry: {
            /** @description Stable type code, for example cloudflare. */
            code: string;
            /** @description Display name. */
            name: string;
            /** @description JSON Schema for the type's configuration. Fields with secret true are write-only. */
            schema: {
                [key: string]: unknown;
            };
            /** @description Other codes that select this type; used by search. */
            aliases?: string[];
        };
        /** @description Pluggable type schemas grouped by kind. */
        MetaSchemas: {
            /** @description DNS-01 providers. */
            dnsProviders: components["schemas"]["SchemaEntry"][];
            /** @description Deploy targets. */
            deployTargets: components["schemas"]["SchemaEntry"][];
            /** @description Notification channels. */
            notifiers: components["schemas"]["SchemaEntry"][];
            /** @description Private CA signers. */
            signers: components["schemas"]["SchemaEntry"][];
        };
        /** @description Local admin credentials. */
        LoginRequest: {
            /**
             * Format: password
             * @description Local admin password.
             */
            password: string;
        };
        /** @description A CertForge user. */
        User: {
            /**
             * Format: uuid
             * @description User id.
             */
            id: string;
            /** @description Name shown in the UI. */
            displayName: string;
            /** @description True for the break-glass local admin. */
            localAdmin: boolean;
        };
        /**
         * @description A role. admin is everything; org-admin everything in its org except global-only actions; operator certificates, credentials, accounts, clients, issue and renew; viewer read-only; auditor viewer plus the audit log.
         * @enum {string}
         */
        Role: "admin" | "org-admin" | "operator" | "viewer" | "auditor";
        /** @description One role held by the signed-in principal. */
        MeBinding: {
            role: components["schemas"]["Role"];
            /**
             * Format: uuid
             * @description The org the role applies to; null for a global binding.
             */
            orgId: string | null;
        };
        /** @description The signed-in principal. */
        Me: {
            /** @description The signed-in user. */
            user: components["schemas"]["User"];
            /** @description Distinct role names bound to the user. */
            roles: string[];
            /** @description The roles behind `roles`, with their scope. The UI mirrors authz.Can from these. */
            bindings: components["schemas"]["MeBinding"][];
            /** @description Orgs the user can see. */
            orgs: components["schemas"]["Org"][];
            /** @description Send in the X-CSRF-Token header on every POST, PUT, PATCH, and DELETE. */
            csrfToken: string;
        };
        /** @description A settings section value; its shape is defined by the section schema. */
        SettingsValue: {
            [key: string]: unknown;
        };
        /** @description A settings section with its schema. */
        SettingsSection: {
            /** @description Section name. */
            section: string;
            /** @description JSON Schema (draft 2020-12) of the value; the UI renders the form from it. */
            schema: {
                [key: string]: unknown;
            };
            /** @description The section's effective value — its own stored value, or the section's built-in default when it has never been saved. Secret properties are never included here. */
            value: components["schemas"]["SettingsValue"];
            /** @description The raw value actually saved for this section, before built-in defaults are filled in; null when the section has never been saved. Lets a client tell "never configured" apart from "explicitly set to the built-in value" (value alone cannot, since it always looks concrete once a default is filled in). Secret properties are never included here. */
            stored: components["schemas"]["SettingsValue"] | null;
            /** @description Names of the section's secret properties that currently hold a value. Secret values are never returned; send "__unchanged__" to keep one, "" to clear it. */
            storedSecrets: string[];
        };
        /** @description First-run state. */
        SetupStatus: {
            /** @description True until POST /setup/complete succeeds. */
            needsSetup: boolean;
        };
        /** @description First-run wizard input. */
        SetupRequest: {
            /**
             * Format: password
             * @description New local admin password, at least 12 characters.
             */
            adminPassword: string;
            /** @description Display name of the first org. */
            orgName: string;
            /** @description URL-safe identifier of the first org. */
            orgSlug: string;
            /** @description Public URL of this CertForge instance, for example https://certs.example.com. */
            baseUrl: string;
        };
        /**
         * @description CA preset code; custom takes any directory URL.
         * @enum {string}
         */
        CAPresetCode: "letsencrypt" | "letsencrypt-staging" | "zerossl" | "buypass" | "google" | "sslcom" | "custom";
        /** @description A well-known ACME CA. */
        CAPreset: {
            /** @description Preset code. */
            preset: components["schemas"]["CAPresetCode"];
            /** @description Display name. */
            name: string;
            /** @description ACME directory URL; empty for custom. */
            directoryUrl: string;
            /** @description The CA needs External Account Binding. */
            requiresEab: boolean;
        };
        /** @description An ACME certificate authority. */
        CA: {
            /**
             * Format: uuid
             * @description CA id.
             */
            id: string;
            /**
             * Format: uuid
             * @description Owning org.
             */
            orgId?: string;
            /** @description Unique name in the org. */
            name: string;
            /** @description Preset code. */
            preset: components["schemas"]["CAPresetCode"];
            /** @description ACME directory URL. */
            directoryUrl: string;
            /** @description Extra PEM roots for a private ACME server. */
            trustBundlePem?: string;
            /** @description EAB key id; empty when unused. */
            eabKid?: string;
            /** @description An EAB HMAC is stored (it is never returned). */
            hasEab?: boolean;
            /** @description DNS resolvers (host or host:port) for propagation checks. */
            resolvers: string[];
            /** @description Reserved for Phase 2 global CAs; false in Phase 1. */
            shared?: boolean;
            /**
             * Format: date-time
             * @description Creation time.
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description Last change.
             */
            updatedAt?: string;
        };
        /** @description Fields to create or replace a CA. */
        CAInput: {
            /** @description Unique name in the org. */
            name: string;
            /** @description Preset code. */
            preset: components["schemas"]["CAPresetCode"];
            /** @description Required for custom; defaults to the preset URL. */
            directoryUrl?: string;
            /** @description Extra PEM roots. */
            trustBundlePem?: string;
            /** @description EAB key id. */
            eabKid?: string;
            /** @description EAB HMAC key (base64url). Write-only: on update null or __unchanged__ keeps it, empty string removes it. */
            eabHmac?: string | null;
            /** @description DNS resolvers for propagation checks. */
            resolvers?: string[];
        };
        /** @description A registered ACME account; its key never leaves the server. */
        AcmeAccount: {
            /**
             * Format: uuid
             * @description Account id.
             */
            id: string;
            /**
             * Format: uuid
             * @description Owning org.
             */
            orgId?: string;
            /**
             * Format: uuid
             * @description CA the account is registered with.
             */
            caId: string;
            /** @description Contact email. */
            email: string;
            /**
             * @description Account status.
             * @enum {string}
             */
            status: "valid" | "deactivated";
            /** @description Account URL (kid) at the CA. */
            registrationUri: string;
            /**
             * Format: date-time
             * @description Registration time.
             */
            createdAt?: string;
        };
        /** @description Account to register. */
        AcmeAccountInput: {
            /**
             * Format: uuid
             * @description CA to register with.
             */
            caId: string;
            /** @description Contact email. */
            email: string;
        };
        /** @description A DNS provider credential. Secret values are never returned. */
        DNSCredential: {
            /**
             * Format: uuid
             * @description Credential id.
             */
            id: string;
            /**
             * Format: uuid
             * @description Owning org.
             */
            orgId?: string;
            /** @description Unique name in the org. */
            name: string;
            /** @description Provider code from GET /meta/schemas dnsProviders. */
            providerCode: string;
            /** @description Non-secret field values. */
            config: {
                [key: string]: string;
            };
            /** @description Secret fields that have a stored value. */
            storedSecrets?: string[];
            /** @description Certificates and defaults whose rules reference this credential. */
            usedBy?: number;
            /**
             * Format: date-time
             * @description Creation time.
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description Last change.
             */
            updatedAt?: string;
        };
        /** @description A new DNS credential. */
        DNSCredentialInput: {
            /** @description Unique name in the org. */
            name: string;
            /** @description Provider code or alias. */
            providerCode: string;
            /** @description Field values keyed by schema property. */
            config: {
                [key: string]: string;
            };
        };
        /** @description Replacement name and config. */
        DNSCredentialUpdate: {
            /** @description Unique name in the org. */
            name: string;
            /** @description Full config; secret fields may be __unchanged__. */
            config: {
                [key: string]: string;
            };
        };
        /** @description Zone to test against. */
        DNSCredentialTestRequest: {
            /**
             * @description A zone the credential manages.
             * @example example.com
             */
            zone: string;
        };
        /** @description Outcome of a credential test. */
        DNSCredentialTestResult: {
            /** @description The record was created and removed. */
            ok: boolean;
            /** @description TXT record name used; empty if the test timed out before it was known. */
            fqdn: string;
            /** @description Provider error when ok is false, with every config value redacted; "timed out" past the bounded timeout (cleanup keeps running in the background). */
            error?: string;
            /** @description Test duration in milliseconds. */
            durationMs: number;
        };
        /**
         * @description Certificate key algorithm.
         * @enum {string}
         */
        KeyType: "rsa2048" | "rsa3072" | "rsa4096" | "ec256" | "ec384";
        /** @description When to renew. */
        RenewPolicy: {
            /**
             * @description days: renew value days before expiry. percent: renew when value percent of the lifetime remains.
             * @enum {string}
             */
            mode: "days" | "percent";
            /** @description Days (1-365) or percent (1-99). */
            value: number;
            /** @description Stored now; ACME Renewal Information is used from Phase 4. */
            useAri: boolean;
        };
        /** @description How to prove control of the names this rule matches. First match wins. */
        VerificationRule: {
            /**
             * @description * (every name), *.zone (names one label below zone, and *.zone itself), or zone (the zone, its subdomains and wildcards).
             * @example *.example.com
             */
            match: string;
            /**
             * @description Verification method.
             * @enum {string}
             */
            method: "dns-01" | "manual-dns";
            /**
             * Format: uuid
             * @description DNS credential; required for dns-01.
             */
            dnsCredentialId?: string;
            /** @description Propagation timeout override. */
            propagationSeconds?: number;
            /** @description Resolvers for propagation checks. */
            resolvers?: string[];
            /** @description Zone that _acme-challenge is CNAMEd into; checked before validation. */
            cnameAliasZone?: string;
        };
        /** @description One level of issuance settings (org defaults or certificate overrides). Null or omitted inherits from the level above. */
        IssuanceDefaults: {
            /**
             * Format: uuid
             * @description CA.
             */
            caId?: string | null;
            /**
             * Format: uuid
             * @description ACME account; must belong to the CA.
             */
            accountId?: string | null;
            /** @description Key algorithm. */
            keyType?: components["schemas"]["KeyType"] | null;
            /** @description Renewal policy. */
            renewPolicy?: components["schemas"]["RenewPolicy"] | null;
            /** @description Issuer common name of the preferred alternate chain. */
            preferredChain?: string | null;
            /** @description Keep the private key across renewals. */
            reuseKey?: boolean | null;
            /** @description Request OCSP must-staple. */
            mustStaple?: boolean | null;
            /** @description Catch-all rules checked after a certificate's own rules. */
            verificationRules?: components["schemas"]["VerificationRule"][] | null;
            /** @description Propagation timeout in seconds. */
            propagationSeconds?: number | null;
            /** @description Resolvers for propagation checks. */
            resolvers?: string[] | null;
        };
        /**
         * @description Level an effective value came from; default means the built-in value.
         * @enum {string}
         */
        Source: "default" | "global" | "org" | "cert";
        /** @description Effective id and its source. */
        EffectiveUuid: {
            /**
             * Format: uuid
             * @description Resolved value.
             */
            value?: string | null;
            /** @description Level this value came from. */
            source: components["schemas"]["Source"];
        };
        /** @description Effective string and its source. */
        EffectiveString: {
            /** @description Resolved value. */
            value: string;
            /** @description Level this value came from. */
            source: components["schemas"]["Source"];
        };
        /** @description Effective flag and its source. */
        EffectiveBool: {
            /** @description Resolved value. */
            value: boolean;
            /** @description Level this value came from. */
            source: components["schemas"]["Source"];
        };
        /** @description Effective number and its source. */
        EffectiveInt: {
            /** @description Resolved value. */
            value: number;
            /** @description Level this value came from. */
            source: components["schemas"]["Source"];
        };
        /** @description Effective string list and its source. */
        EffectiveStrings: {
            /** @description Resolved value. */
            value: string[];
            /** @description Level this value came from. */
            source: components["schemas"]["Source"];
        };
        /** @description Effective renewal policy and its source. */
        EffectiveRenewPolicy: {
            /** @description Resolved renewal policy. */
            value: components["schemas"]["RenewPolicy"];
            /** @description Level this value came from. */
            source: components["schemas"]["Source"];
        };
        /** @description Effective catch-all rules and their source. */
        EffectiveRules: {
            /** @description Resolved rules. */
            value: components["schemas"]["VerificationRule"][];
            /** @description Level this value came from. */
            source: components["schemas"]["Source"];
        };
        /** @description Resolved issuance settings, each with the level it came from. */
        EffectiveIssuanceDefaults: {
            /** @description Resolved CA and its source. */
            caId?: components["schemas"]["EffectiveUuid"];
            /** @description Resolved ACME account and its source. */
            accountId?: components["schemas"]["EffectiveUuid"];
            /** @description Resolved key algorithm and its source. */
            keyType?: components["schemas"]["EffectiveString"];
            /** @description Resolved renewal policy and its source. */
            renewPolicy?: components["schemas"]["EffectiveRenewPolicy"];
            /** @description Resolved preferred chain and its source. */
            preferredChain?: components["schemas"]["EffectiveString"];
            /** @description Resolved reuse-key flag and its source. */
            reuseKey?: components["schemas"]["EffectiveBool"];
            /** @description Resolved must-staple flag and its source. */
            mustStaple?: components["schemas"]["EffectiveBool"];
            /** @description Resolved catch-all rules and their source. */
            verificationRules?: components["schemas"]["EffectiveRules"];
            /** @description Resolved propagation timeout and its source. */
            propagationSeconds?: components["schemas"]["EffectiveInt"];
            /** @description Resolved resolvers and their source. */
            resolvers?: components["schemas"]["EffectiveStrings"];
        };
        /** @description One issued certificate. */
        CertificateVersion: {
            /**
             * Format: uuid
             * @description Version id.
             */
            id: string;
            /** @description Serial number */
            serial: string;
            /**
             * Format: date-time
             * @description Start of validity.
             */
            notBefore: string;
            /**
             * Format: date-time
             * @description End of validity.
             */
            notAfter: string;
            /** @description SHA-256 of the leaf DER */
            sha256Fingerprint: string;
            /** @description Key algorithm. */
            keyType?: components["schemas"]["KeyType"];
            /**
             * @description How the version was obtained.
             * @enum {string}
             */
            source: "issued" | "imported" | "uploaded";
            /**
             * Format: date-time
             * @description Revocation time.
             */
            revokedAt?: string | null;
            /**
             * Format: date-time
             * @description When it was stored.
             */
            createdAt?: string;
        };
        /** @description A managed certificate. */
        Certificate: {
            /**
             * Format: uuid
             * @description Certificate id.
             */
            id: string;
            /**
             * Format: uuid
             * @description Owning org.
             */
            orgId?: string;
            /** @description Unique name in the org. */
            name: string;
            /** @description First name; the certificate subject. */
            commonName: string;
            /** @description Names besides the common name. */
            sans: string[];
            /** @description Certificate rules, checked before the inherited catch-all rules. */
            verificationRules: components["schemas"]["VerificationRule"][];
            /** @description Per-certificate overrides of issuance settings. */
            overrides: components["schemas"]["IssuanceDefaults"];
            /**
             * @description pending until first issued; active while a valid version exists.
             * @enum {string}
             */
            status: "pending" | "active" | "failed" | "expired" | "revoked";
            /** @description Newest issued version. */
            currentVersion?: components["schemas"]["CertificateVersion"] | null;
            /**
             * Format: date-time
             * @description Next scheduled issuance or retry.
             */
            nextRenewAt?: string | null;
            /** @description Consecutive failed attempts. */
            failureCount: number;
            /** @description Error of the last failed attempt. */
            lastError?: string | null;
            /** @description Resolved issuance settings for this certificate. */
            effective: components["schemas"]["EffectiveIssuanceDefaults"];
            /**
             * Format: date-time
             * @description Creation time.
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description Last change.
             */
            updatedAt?: string;
        };
        /** @description Fields to create or replace a certificate. */
        CertificateInput: {
            /** @description Unique name in the org. */
            name: string;
            /** @description Common name. */
            commonName: string;
            /** @description More names; the common name may repeat here. */
            sans?: string[];
            /** @description Ordered rules. */
            verificationRules?: components["schemas"]["VerificationRule"][];
            /** @description Per-certificate overrides of issuance settings. */
            overrides?: components["schemas"]["IssuanceDefaults"];
        };
        /** @description One page of certificates. */
        CertificateList: {
            /** @description Certificates. */
            items: components["schemas"]["Certificate"][];
            /** @description Cursor for the next page; null on the last page. */
            nextCursor?: string | null;
        };
        /** @description One step of an attempt. */
        AttemptStep: {
            /**
             * @description caa, rate_ledger, account, order, challenge <name>, finalize or store.
             * @example challenge *.example.com
             */
            name: string;
            /**
             * @description Step state.
             * @enum {string}
             */
            status: "pending" | "running" | "success" | "failed" | "skipped" | "waiting_manual";
            /**
             * Format: date-time
             * @description Start time.
             */
            startedAt: string;
            /**
             * Format: date-time
             * @description End time.
             */
            finishedAt?: string | null;
            /** @description Detail or error. */
            message?: string | null;
        };
        /** @description One issuance run. */
        IssuanceAttempt: {
            /**
             * Format: uuid
             * @description Attempt id.
             */
            id: string;
            /**
             * Format: date-time
             * @description Start time.
             */
            startedAt: string;
            /**
             * Format: date-time
             * @description End time.
             */
            finishedAt?: string | null;
            /**
             * @description Result.
             * @enum {string}
             */
            outcome: "running" | "success" | "failed";
            /**
             * @description ACME problem type of the failure.
             * @example urn:ietf:params:acme:error:rateLimited
             */
            acmeErrorType?: string | null;
            /**
             * Format: date-time
             * @description Earliest retry the CA allows.
             */
            retryAfter?: string | null;
            /** @description Step timeline. */
            steps: components["schemas"]["AttemptStep"][];
            /** @description Attempt log. */
            log: string;
        };
        /** @description A TXT record the operator must add. */
        ManualDNSRecord: {
            /**
             * @description Record name.
             * @example _acme-challenge.lab.example.com
             */
            name: string;
            /**
             * @description Record type.
             * @enum {string}
             */
            type: "TXT";
            /** @description Record value. */
            value: string;
            /** @description Suggested TTL in seconds. */
            ttl: number;
            /**
             * Format: date-time
             * @description The attempt fails if not confirmed by then.
             */
            expiresAt?: string;
        };
        /** @description Confirmation result. */
        ManualDNSConfirmResult: {
            /** @description Records confirmed. */
            confirmed: number;
        };
        /** @description Renew request result. */
        RenewResult: {
            /** @description False when an issuance was already queued or running. */
            enqueued: boolean;
        };
    };
    responses: never;
    parameters: {
        /** @description Org id. */
        OrgId: string;
        /** @description Resource id. */
        Id: string;
        /** @description Certificate version id. */
        VersionId: string;
        /** @description Only certificates with this status. */
        ListStatus: "pending" | "active" | "failed" | "expired" | "revoked";
        /** @description Case-insensitive substring of the name or any certificate name. */
        ListQ: string;
        /** @description name, notAfter, nextRenewAt or status; prefix - for descending. Default name. */
        ListSort: string;
        /** @description Page size, 1 to 500. */
        ListLimit: number;
        /** @description nextCursor from the previous page. */
        ListCursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSetupStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setup status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    completeSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Setup done; session cookie set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    getMetaSchemas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schemas grouped by kind. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaSchemas"];
                };
            };
        };
    };
    listOrgs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible organizations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgList"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in; session cookie set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current principal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    getSettingsSection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Section name, for example general, backup, or issuance_defaults. */
                section: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Section schema and value. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsSection"];
                };
            };
        };
    };
    putSettingsSection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Section name, for example general, backup, or issuance_defaults. */
                section: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsValue"];
            };
        };
        responses: {
            /** @description Stored section. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsSection"];
                };
            };
        };
    };
    listCaPresets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Presets in display order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CAPreset"][];
                };
            };
        };
    };
    listCas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All CAs of the org. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CA"][];
                };
            };
        };
    };
    createCa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CAInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CA"];
                };
            };
        };
    };
    getCa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The CA. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CA"];
                };
            };
        };
    };
    updateCa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CAInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CA"];
                };
            };
        };
    };
    deleteCa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAcmeAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All accounts of the org. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcmeAccount"][];
                };
            };
        };
    };
    createAcmeAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcmeAccountInput"];
            };
        };
        responses: {
            /** @description Registered. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcmeAccount"];
                };
            };
        };
    };
    getAcmeAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcmeAccount"];
                };
            };
        };
    };
    deleteAcmeAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listDNSCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All credentials of the org. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DNSCredential"][];
                };
            };
        };
    };
    createDNSCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DNSCredentialInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DNSCredential"];
                };
            };
        };
    };
    getDNSCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The credential. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DNSCredential"];
                };
            };
        };
    };
    updateDNSCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DNSCredentialUpdate"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DNSCredential"];
                };
            };
        };
    };
    deleteDNSCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    testDNSCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DNSCredentialTestRequest"];
            };
        };
        responses: {
            /** @description Test outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DNSCredentialTestResult"];
                };
            };
        };
    };
    getOrgIssuanceDefaults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Org defaults. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuanceDefaults"];
                };
            };
        };
    };
    putOrgIssuanceDefaults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssuanceDefaults"];
            };
        };
        responses: {
            /** @description Stored defaults. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuanceDefaults"];
                };
            };
        };
    };
    getEffectiveIssuanceDefaults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Effective defaults. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffectiveIssuanceDefaults"];
                };
            };
        };
    };
    listCertificates: {
        parameters: {
            query?: {
                /** @description Only certificates with this status. */
                status?: components["parameters"]["ListStatus"];
                /** @description Case-insensitive substring of the name or any certificate name. */
                q?: components["parameters"]["ListQ"];
                /** @description name, notAfter, nextRenewAt or status; prefix - for descending. Default name. */
                sort?: components["parameters"]["ListSort"];
                /** @description Page size, 1 to 500. */
                limit?: components["parameters"]["ListLimit"];
                /** @description nextCursor from the previous page. */
                cursor?: components["parameters"]["ListCursor"];
            };
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of certificates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateList"];
                };
            };
        };
    };
    createCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CertificateInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Certificate"];
                };
            };
        };
    };
    getCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The certificate. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Certificate"];
                };
            };
        };
    };
    updateCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CertificateInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Certificate"];
                };
            };
        };
    };
    deleteCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    renewCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenewResult"];
                };
            };
        };
    };
    listCertificateVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All versions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateVersion"][];
                };
            };
        };
    };
    listIssuanceAttempts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attempts, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuanceAttempt"][];
                };
            };
        };
    };
    downloadCertificateVersion: {
        parameters: {
            query: {
                /** @description Output format; Phase 1 supports pem. */
                format?: "pem";
                /** @description Comma-separated parts from cert, chain, fullchain, key, combined (fullchain plus key). */
                parts: string;
            };
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
                /** @description Certificate version id. */
                vid: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File contents. */
            200: {
                headers: {
                    /** @description Attachment file name. */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/x-pem-file": string;
                    "application/zip": string;
                };
            };
        };
    };
    listManualDNS: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending records. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualDNSRecord"][];
                };
            };
        };
    };
    confirmManualDNS: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Org id. */
                orgId: components["parameters"]["OrgId"];
                /** @description Resource id. */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Confirmed. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualDNSConfirmResult"];
                };
            };
        };
    };
}
