// Command gen-lego-schemas turns lego's per-provider TOML metadata
// (providers/dns/<code>/<code>.toml) into JSON Schemas embedded by
// internal/challenge, and writes docs/dns-providers.md from the same data.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/BurntSushi/toml"
)

type providerTOML struct {
	Name          string
	Code          string
	URL           string
	Aliases       []string
	Configuration struct {
		Credentials map[string]string
		Additional  map[string]string
	}
}

type property struct {
	Type        string `json:"type"`
	Title       string `json:"title"`
	Description string `json:"description,omitempty"`
	Secret      bool   `json:"secret"`
	Group       string `json:"x-group"`
}

type schema struct {
	Schema               string              `json:"$schema"`
	Title                string              `json:"title"`
	Type                 string              `json:"type"`
	AdditionalProperties bool                `json:"additionalProperties"`
	Properties           map[string]property `json:"properties"`
}

type providerFile struct {
	Code    string   `json:"code"`
	Name    string   `json:"name"`
	URL     string   `json:"url,omitempty"`
	Aliases []string `json:"aliases,omitempty"`
	Schema  schema   `json:"schema"`
}

// secretName marks credential fields as write-only.
var secretName = regexp.MustCompile(`(?i)(secret|token|key|password|pass)`)

// skipped providers: "manual" reads stdin, "exec" runs an arbitrary program
// on the server; neither is safe to expose as a stored credential.
var skipped = map[string]bool{"manual": true, "exec": true}

func main() {
	legoDir := flag.String("lego-dir", "", "lego module dir (default: go list -m)")
	out := flag.String("out", "schemas", "output directory for <code>.json")
	docs := flag.String("docs", "", "markdown output path (optional)")
	flag.Parse()
	if *legoDir == "" {
		b, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", "github.com/go-acme/lego/v4").Output()
		if err != nil {
			log.Fatalf("locate lego module: %v", err)
		}
		*legoDir = strings.TrimSpace(string(b))
	}
	if err := generate(*legoDir, *out, *docs); err != nil {
		log.Fatal(err)
	}
}

func generate(legoDir, outDir, docsPath string) error {
	paths, err := filepath.Glob(filepath.Join(legoDir, "providers", "dns", "*", "*.toml"))
	if err != nil {
		return err
	}
	var files []providerFile
	for _, p := range paths {
		var t providerTOML
		if _, err := toml.DecodeFile(p, &t); err != nil {
			return fmt.Errorf("%s: %w", p, err)
		}
		if t.Code == "" || skipped[t.Code] {
			continue
		}
		files = append(files, convert(t))
	}
	// A misresolved lego module dir (for example an empty extracted module
	// cache) would otherwise glob to zero files and silently wipe outDir.
	if len(files) == 0 {
		return fmt.Errorf("no providers found under %s: refusing to overwrite %s", legoDir, outDir)
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Code < files[j].Code })
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	old, err := filepath.Glob(filepath.Join(outDir, "*.json"))
	if err != nil {
		return err
	}
	for _, o := range old {
		if err := os.Remove(o); err != nil {
			return err
		}
	}
	for _, f := range files {
		b, err := json.MarshalIndent(f, "", "  ")
		if err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(outDir, f.Code+".json"), append(b, '\n'), 0o644); err != nil {
			return err
		}
	}
	if docsPath != "" {
		return os.WriteFile(docsPath, renderDocs(files), 0o644)
	}
	return nil
}

func convert(t providerTOML) providerFile {
	props := map[string]property{}
	for k, d := range t.Configuration.Credentials {
		props[k] = property{Type: "string", Title: k, Description: d, Secret: secretName.MatchString(k), Group: "credentials"}
	}
	// Additional (tuning) fields are never secret: lego marks them optional.
	for k, d := range t.Configuration.Additional {
		props[k] = property{Type: "string", Title: k, Description: d, Group: "additional"}
	}
	return providerFile{
		Code: t.Code, Name: t.Name, URL: t.URL, Aliases: t.Aliases,
		Schema: schema{
			Schema: "https://json-schema.org/draft/2020-12/schema", Title: t.Name, Type: "object",
			AdditionalProperties: false, Properties: props,
		},
	}
}

func renderDocs(files []providerFile) []byte {
	var b bytes.Buffer
	b.WriteString("# DNS providers\n\n")
	b.WriteString("Generated by `tools/gen-lego-schemas` from lego's provider metadata. Do not edit by hand.\n\n")
	b.WriteString("Fields marked secret are write-only: the API never returns them, and a PUT with `__unchanged__` keeps the stored value. Fields in the additional group are optional tuning knobs.\n\n")
	b.WriteString("The lego `exec` provider (runs an arbitrary program on the server) and `manual` provider (reads stdin) are not offered here; use verification rule method `manual-dns` instead.\n\n")
	for _, f := range files {
		fmt.Fprintf(&b, "## %s\n\nCode: `%s`", f.Name, f.Code)
		if len(f.Aliases) > 0 {
			fmt.Fprintf(&b, " (aliases: `%s`)", strings.Join(f.Aliases, "`, `"))
		}
		if f.URL != "" {
			fmt.Fprintf(&b, ". Website: <%s>", f.URL)
		}
		b.WriteString("\n\n| Field | Group | Secret | Description |\n|---|---|---|---|\n")
		keys := make([]string, 0, len(f.Schema.Properties))
		for k := range f.Schema.Properties {
			keys = append(keys, k)
		}
		sort.Slice(keys, func(i, j int) bool {
			pi, pj := f.Schema.Properties[keys[i]], f.Schema.Properties[keys[j]]
			if pi.Group != pj.Group {
				return pi.Group == "credentials"
			}
			return keys[i] < keys[j]
		})
		for _, k := range keys {
			p := f.Schema.Properties[k]
			secret := "no"
			if p.Secret {
				secret = "yes"
			}
			desc := strings.ReplaceAll(p.Description, "|", `\|`)
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", k, p.Group, secret, desc)
		}
		b.WriteString("\n")
	}
	return b.Bytes()
}
