// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agent_cas.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveClientCertsForCA = `-- name: CountActiveClientCertsForCA :one
SELECT count(*)::bigint FROM clients
WHERE agent_ca_id = $1::uuid AND status = 'active' AND agent_cert_not_after > now()
`

func (q *Queries) CountActiveClientCertsForCA(ctx context.Context, caID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveClientCertsForCA, caID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getActiveAgentCA = `-- name: GetActiveAgentCA :one
SELECT id, cert_der, key, status, not_before, not_after, created_at FROM agent_cas WHERE status = 'active'
`

func (q *Queries) GetActiveAgentCA(ctx context.Context) (AgentCa, error) {
	row := q.db.QueryRow(ctx, getActiveAgentCA)
	var i AgentCa
	err := row.Scan(
		&i.ID,
		&i.CertDer,
		&i.Key,
		&i.Status,
		&i.NotBefore,
		&i.NotAfter,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentCA = `-- name: GetAgentCA :one
SELECT id, cert_der, key, status, not_before, not_after, created_at FROM agent_cas WHERE id = $1
`

func (q *Queries) GetAgentCA(ctx context.Context, id uuid.UUID) (AgentCa, error) {
	row := q.db.QueryRow(ctx, getAgentCA, id)
	var i AgentCa
	err := row.Scan(
		&i.ID,
		&i.CertDer,
		&i.Key,
		&i.Status,
		&i.NotBefore,
		&i.NotAfter,
		&i.CreatedAt,
	)
	return i, err
}

const getOldestTrustedAgentCA = `-- name: GetOldestTrustedAgentCA :one
SELECT id, cert_der, key, status, not_before, not_after, created_at FROM agent_cas WHERE status <> 'retired' ORDER BY created_at, id LIMIT 1
`

func (q *Queries) GetOldestTrustedAgentCA(ctx context.Context) (AgentCa, error) {
	row := q.db.QueryRow(ctx, getOldestTrustedAgentCA)
	var i AgentCa
	err := row.Scan(
		&i.ID,
		&i.CertDer,
		&i.Key,
		&i.Status,
		&i.NotBefore,
		&i.NotAfter,
		&i.CreatedAt,
	)
	return i, err
}

const insertAgentCA = `-- name: InsertAgentCA :one
INSERT INTO agent_cas (cert_der, key, not_before, not_after) VALUES ($1, $2, $3, $4) RETURNING id, cert_der, key, status, not_before, not_after, created_at
`

type InsertAgentCAParams struct {
	CertDer   []byte    `json:"cert_der"`
	Key       []byte    `json:"key"`
	NotBefore time.Time `json:"not_before"`
	NotAfter  time.Time `json:"not_after"`
}

func (q *Queries) InsertAgentCA(ctx context.Context, arg InsertAgentCAParams) (AgentCa, error) {
	row := q.db.QueryRow(ctx, insertAgentCA,
		arg.CertDer,
		arg.Key,
		arg.NotBefore,
		arg.NotAfter,
	)
	var i AgentCa
	err := row.Scan(
		&i.ID,
		&i.CertDer,
		&i.Key,
		&i.Status,
		&i.NotBefore,
		&i.NotAfter,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentCAs = `-- name: ListAgentCAs :many
SELECT a.id, a.cert_der, a.status, a.created_at,
       (SELECT count(*) FROM clients c
         WHERE c.agent_ca_id = a.id AND c.status = 'active' AND c.agent_cert_not_after > now())::bigint AS active_client_certs
FROM agent_cas a ORDER BY a.created_at DESC, a.id
`

type ListAgentCAsRow struct {
	ID                uuid.UUID `json:"id"`
	CertDer           []byte    `json:"cert_der"`
	Status            string    `json:"status"`
	CreatedAt         time.Time `json:"created_at"`
	ActiveClientCerts int64     `json:"active_client_certs"`
}

func (q *Queries) ListAgentCAs(ctx context.Context) ([]ListAgentCAsRow, error) {
	rows, err := q.db.Query(ctx, listAgentCAs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentCAsRow{}
	for rows.Next() {
		var i ListAgentCAsRow
		if err := rows.Scan(
			&i.ID,
			&i.CertDer,
			&i.Status,
			&i.CreatedAt,
			&i.ActiveClientCerts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrustedAgentCAs = `-- name: ListTrustedAgentCAs :many
SELECT id, cert_der, status, not_after FROM agent_cas WHERE status <> 'retired' ORDER BY created_at, id
`

type ListTrustedAgentCAsRow struct {
	ID       uuid.UUID `json:"id"`
	CertDer  []byte    `json:"cert_der"`
	Status   string    `json:"status"`
	NotAfter time.Time `json:"not_after"`
}

func (q *Queries) ListTrustedAgentCAs(ctx context.Context) ([]ListTrustedAgentCAsRow, error) {
	rows, err := q.db.Query(ctx, listTrustedAgentCAs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrustedAgentCAsRow{}
	for rows.Next() {
		var i ListTrustedAgentCAsRow
		if err := rows.Scan(
			&i.ID,
			&i.CertDer,
			&i.Status,
			&i.NotAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAgentCA = `-- name: LockAgentCA :one
SELECT id, cert_der, key, status, not_before, not_after, created_at FROM agent_cas WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockAgentCA(ctx context.Context, id uuid.UUID) (AgentCa, error) {
	row := q.db.QueryRow(ctx, lockAgentCA, id)
	var i AgentCa
	err := row.Scan(
		&i.ID,
		&i.CertDer,
		&i.Key,
		&i.Status,
		&i.NotBefore,
		&i.NotAfter,
		&i.CreatedAt,
	)
	return i, err
}

const markActiveAgentCARetiring = `-- name: MarkActiveAgentCARetiring :many
UPDATE agent_cas SET status = 'retiring' WHERE status = 'active' RETURNING id
`

// Returns the previously active CA's id (zero rows when none was active),
// read atomically in the same transaction that marks it retiring, so a
// concurrent Rotate can never race this one for the "previous" CA.
func (q *Queries) MarkActiveAgentCARetiring(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, markActiveAgentCARetiring)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAgentCARetired = `-- name: SetAgentCARetired :one
UPDATE agent_cas SET status = 'retired' WHERE id = $1 RETURNING id, cert_der, key, status, not_before, not_after, created_at
`

func (q *Queries) SetAgentCARetired(ctx context.Context, id uuid.UUID) (AgentCa, error) {
	row := q.db.QueryRow(ctx, setAgentCARetired, id)
	var i AgentCa
	err := row.Scan(
		&i.ID,
		&i.CertDer,
		&i.Key,
		&i.Status,
		&i.NotBefore,
		&i.NotAfter,
		&i.CreatedAt,
	)
	return i, err
}

const shareAgentCA = `-- name: ShareAgentCA :one
SELECT id, cert_der, key, status, not_before, not_after, created_at FROM agent_cas WHERE id = $1 FOR SHARE
`

// A shared lock: concurrent enrolments/renewals against the same CA do not
// serialize on each other, but still conflict with Retire's FOR UPDATE.
func (q *Queries) ShareAgentCA(ctx context.Context, id uuid.UUID) (AgentCa, error) {
	row := q.db.QueryRow(ctx, shareAgentCA, id)
	var i AgentCa
	err := row.Scan(
		&i.ID,
		&i.CertDer,
		&i.Key,
		&i.Status,
		&i.NotBefore,
		&i.NotAfter,
		&i.CreatedAt,
	)
	return i, err
}
