// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: api_keys.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (name, prefix, secret_hash, scopes, org_id, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, name, prefix, secret_hash, scopes, org_id, created_by, expires_at, last_used_at, revoked_at, created_at
`

type CreateAPIKeyParams struct {
	Name       string     `json:"name"`
	Prefix     string     `json:"prefix"`
	SecretHash []byte     `json:"secret_hash"`
	Scopes     []string   `json:"scopes"`
	OrgID      *uuid.UUID `json:"org_id"`
	CreatedBy  uuid.UUID  `json:"created_by"`
	ExpiresAt  *time.Time `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.Name,
		arg.Prefix,
		arg.SecretHash,
		arg.Scopes,
		arg.OrgID,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.SecretHash,
		&i.Scopes,
		&i.OrgID,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, name, prefix, secret_hash, scopes, org_id, created_by, expires_at, last_used_at, revoked_at, created_at FROM api_keys WHERE id = $1
`

func (q *Queries) GetAPIKey(ctx context.Context, id uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.SecretHash,
		&i.Scopes,
		&i.OrgID,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT id, name, prefix, secret_hash, scopes, org_id, created_by, expires_at, last_used_at, revoked_at, created_at FROM api_keys WHERE prefix = $1
`

func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, prefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.SecretHash,
		&i.Scopes,
		&i.OrgID,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT k.id, k.name, k.prefix, k.secret_hash, k.scopes, k.org_id, k.created_by, k.expires_at, k.last_used_at, k.revoked_at, k.created_at, u.display_name AS created_by_name
FROM api_keys k JOIN users u ON u.id = k.created_by
WHERE $1::uuid IS NULL OR k.org_id = $1
ORDER BY k.created_at DESC, k.id
`

type ListAPIKeysRow struct {
	ID            uuid.UUID  `json:"id"`
	Name          string     `json:"name"`
	Prefix        string     `json:"prefix"`
	SecretHash    []byte     `json:"secret_hash"`
	Scopes        []string   `json:"scopes"`
	OrgID         *uuid.UUID `json:"org_id"`
	CreatedBy     uuid.UUID  `json:"created_by"`
	ExpiresAt     *time.Time `json:"expires_at"`
	LastUsedAt    *time.Time `json:"last_used_at"`
	RevokedAt     *time.Time `json:"revoked_at"`
	CreatedAt     time.Time  `json:"created_at"`
	CreatedByName string     `json:"created_by_name"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, orgID *uuid.UUID) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.SecretHash,
			&i.Scopes,
			&i.OrgID,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleBindingsForAPIKey = `-- name: ListRoleBindingsForAPIKey :many
SELECT id, subject_type, subject, role, org_id, site_id, created_at FROM role_bindings WHERE subject_type = 'apikey' AND subject = $1 ORDER BY created_at, id
`

func (q *Queries) ListRoleBindingsForAPIKey(ctx context.Context, subject string) ([]RoleBinding, error) {
	rows, err := q.db.Query(ctx, listRoleBindingsForAPIKey, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleBinding{}
	for rows.Next() {
		var i RoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.Subject,
			&i.Role,
			&i.OrgID,
			&i.SiteID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

func (q *Queries) TouchAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
