// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: attempts.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const appendAttemptLog = `-- name: AppendAttemptLog :exec
UPDATE issuance_attempts SET log = log || $2 WHERE id = $1
`

type AppendAttemptLogParams struct {
	ID  uuid.UUID `json:"id"`
	Log string    `json:"log"`
}

// Appends one line to an attempt's log after it has already finished (fix
// round 1): the post-issuance ARI poll runs after succeed's own
// transaction commits, and so after FinishAttempt already wrote the
// timeline snapshot, so a failure there can only ever be appended, not
// folded into that snapshot.
func (q *Queries) AppendAttemptLog(ctx context.Context, arg AppendAttemptLogParams) error {
	_, err := q.db.Exec(ctx, appendAttemptLog, arg.ID, arg.Log)
	return err
}

const confirmManualPending = `-- name: ConfirmManualPending :execrows
UPDATE manual_dns_pending SET confirmed_at = now()
WHERE cert_id = $1 AND confirmed_at IS NULL AND expires_at > now()
`

func (q *Queries) ConfirmManualPending(ctx context.Context, certID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, confirmManualPending, certID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO issuance_attempts (cert_id) VALUES ($1) RETURNING id, cert_id, started_at, finished_at, outcome, acme_error_type, retry_after, steps, log
`

func (q *Queries) CreateAttempt(ctx context.Context, certID uuid.UUID) (IssuanceAttempt, error) {
	row := q.db.QueryRow(ctx, createAttempt, certID)
	var i IssuanceAttempt
	err := row.Scan(
		&i.ID,
		&i.CertID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Outcome,
		&i.AcmeErrorType,
		&i.RetryAfter,
		&i.Steps,
		&i.Log,
	)
	return i, err
}

const deleteManualPending = `-- name: DeleteManualPending :exec
DELETE FROM manual_dns_pending WHERE attempt_id = $1
`

func (q *Queries) DeleteManualPending(ctx context.Context, attemptID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteManualPending, attemptID)
	return err
}

const failStaleAttempts = `-- name: FailStaleAttempts :execrows
UPDATE issuance_attempts SET outcome = 'failed', finished_at = now(),
    log = log || 'attempt interrupted (server restart or job timeout)' || E'\n'
WHERE outcome = 'running' AND started_at < $1
`

func (q *Queries) FailStaleAttempts(ctx context.Context, startedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, failStaleAttempts, startedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishAttempt = `-- name: FinishAttempt :execrows
UPDATE issuance_attempts SET outcome = $2, acme_error_type = $3, retry_after = $4,
    steps = $5, log = $6, finished_at = now()
WHERE id = $1 AND outcome = 'running'
`

type FinishAttemptParams struct {
	ID            uuid.UUID  `json:"id"`
	Outcome       string     `json:"outcome"`
	AcmeErrorType string     `json:"acme_error_type"`
	RetryAfter    *time.Time `json:"retry_after"`
	Steps         []byte     `json:"steps"`
	Log           string     `json:"log"`
}

func (q *Queries) FinishAttempt(ctx context.Context, arg FinishAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishAttempt,
		arg.ID,
		arg.Outcome,
		arg.AcmeErrorType,
		arg.RetryAfter,
		arg.Steps,
		arg.Log,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAttempt = `-- name: GetAttempt :one
SELECT id, cert_id, started_at, finished_at, outcome, acme_error_type, retry_after, steps, log FROM issuance_attempts WHERE id = $1 AND cert_id = $2
`

type GetAttemptParams struct {
	ID     uuid.UUID `json:"id"`
	CertID uuid.UUID `json:"cert_id"`
}

func (q *Queries) GetAttempt(ctx context.Context, arg GetAttemptParams) (IssuanceAttempt, error) {
	row := q.db.QueryRow(ctx, getAttempt, arg.ID, arg.CertID)
	var i IssuanceAttempt
	err := row.Scan(
		&i.ID,
		&i.CertID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Outcome,
		&i.AcmeErrorType,
		&i.RetryAfter,
		&i.Steps,
		&i.Log,
	)
	return i, err
}

const insertManualPending = `-- name: InsertManualPending :exec
INSERT INTO manual_dns_pending (attempt_id, cert_id, domain, fqdn, value, ttl, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertManualPendingParams struct {
	AttemptID uuid.UUID `json:"attempt_id"`
	CertID    uuid.UUID `json:"cert_id"`
	Domain    string    `json:"domain"`
	Fqdn      string    `json:"fqdn"`
	Value     string    `json:"value"`
	Ttl       int32     `json:"ttl"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertManualPending(ctx context.Context, arg InsertManualPendingParams) error {
	_, err := q.db.Exec(ctx, insertManualPending,
		arg.AttemptID,
		arg.CertID,
		arg.Domain,
		arg.Fqdn,
		arg.Value,
		arg.Ttl,
		arg.ExpiresAt,
	)
	return err
}

const listAttempts = `-- name: ListAttempts :many
SELECT id, cert_id, started_at, finished_at, outcome, acme_error_type, retry_after, steps,
       CASE WHEN $1::bool THEN log ELSE '' END::text AS log
FROM issuance_attempts WHERE cert_id = $2 ORDER BY started_at DESC LIMIT $3
`

type ListAttemptsParams struct {
	IncludeLog bool      `json:"include_log"`
	CertID     uuid.UUID `json:"cert_id"`
	RowLimit   int32     `json:"row_limit"`
}

type ListAttemptsRow struct {
	ID            uuid.UUID  `json:"id"`
	CertID        uuid.UUID  `json:"cert_id"`
	StartedAt     time.Time  `json:"started_at"`
	FinishedAt    *time.Time `json:"finished_at"`
	Outcome       string     `json:"outcome"`
	AcmeErrorType string     `json:"acme_error_type"`
	RetryAfter    *time.Time `json:"retry_after"`
	Steps         []byte     `json:"steps"`
	Log           string     `json:"log"`
}

func (q *Queries) ListAttempts(ctx context.Context, arg ListAttemptsParams) ([]ListAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listAttempts, arg.IncludeLog, arg.CertID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttemptsRow{}
	for rows.Next() {
		var i ListAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.CertID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Outcome,
			&i.AcmeErrorType,
			&i.RetryAfter,
			&i.Steps,
			&i.Log,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManualPending = `-- name: ListManualPending :many
SELECT id, attempt_id, cert_id, domain, fqdn, value, ttl, expires_at, confirmed_at, created_at FROM manual_dns_pending WHERE cert_id = $1 AND confirmed_at IS NULL AND expires_at > now() ORDER BY fqdn, value
`

func (q *Queries) ListManualPending(ctx context.Context, certID uuid.UUID) ([]ManualDnsPending, error) {
	rows, err := q.db.Query(ctx, listManualPending, certID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManualDnsPending{}
	for rows.Next() {
		var i ManualDnsPending
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.CertID,
			&i.Domain,
			&i.Fqdn,
			&i.Value,
			&i.Ttl,
			&i.ExpiresAt,
			&i.ConfirmedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manualAllConfirmed = `-- name: ManualAllConfirmed :one
SELECT (count(*) > 0 AND count(*) FILTER (WHERE confirmed_at IS NULL) = 0)::boolean AS confirmed
FROM manual_dns_pending WHERE attempt_id = $1
`

func (q *Queries) ManualAllConfirmed(ctx context.Context, attemptID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, manualAllConfirmed, attemptID)
	var confirmed bool
	err := row.Scan(&confirmed)
	return confirmed, err
}

const pruneExpiredManualPending = `-- name: PruneExpiredManualPending :execrows
DELETE FROM manual_dns_pending WHERE confirmed_at IS NULL AND expires_at < now()
`

func (q *Queries) PruneExpiredManualPending(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneExpiredManualPending)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneIssuanceAttempts = `-- name: PruneIssuanceAttempts :execrows
DELETE FROM issuance_attempts
WHERE id IN (
  SELECT ranked.id FROM (
    SELECT a.id, a.outcome, a.started_at,
           row_number() OVER (PARTITION BY a.cert_id ORDER BY a.started_at DESC, a.id DESC) AS rn
    FROM issuance_attempts a
  ) AS ranked
  WHERE ranked.outcome <> 'running' AND ranked.started_at < $1::timestamptz
    AND ranked.rn > $2::int
  LIMIT $3::int
)
`

type PruneIssuanceAttemptsParams struct {
	Before     time.Time `json:"before"`
	KeepRecent int32     `json:"keep_recent"`
	BatchLimit int32     `json:"batch_limit"`
}

// Deletes at most batch_limit finished attempts started before the cutoff,
// always sparing a certificate's newest keep_recent attempts (however old)
// and any attempt still running.
func (q *Queries) PruneIssuanceAttempts(ctx context.Context, arg PruneIssuanceAttemptsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneIssuanceAttempts, arg.Before, arg.KeepRecent, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveAttemptProgress = `-- name: SaveAttemptProgress :exec
UPDATE issuance_attempts SET steps = $2, log = $3 WHERE id = $1
`

type SaveAttemptProgressParams struct {
	ID    uuid.UUID `json:"id"`
	Steps []byte    `json:"steps"`
	Log   string    `json:"log"`
}

func (q *Queries) SaveAttemptProgress(ctx context.Context, arg SaveAttemptProgressParams) error {
	_, err := q.db.Exec(ctx, saveAttemptProgress, arg.ID, arg.Steps, arg.Log)
	return err
}
