// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_events (ts, actor_type, actor_id, action, resource_type, resource_id, org_id, ip, details, prev_hash, hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type InsertAuditEventParams struct {
	Ts           time.Time  `json:"ts"`
	ActorType    string     `json:"actor_type"`
	ActorID      string     `json:"actor_id"`
	Action       string     `json:"action"`
	ResourceType string     `json:"resource_type"`
	ResourceID   string     `json:"resource_id"`
	OrgID        *uuid.UUID `json:"org_id"`
	Ip           string     `json:"ip"`
	Details      []byte     `json:"details"`
	PrevHash     []byte     `json:"prev_hash"`
	Hash         []byte     `json:"hash"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.Ts,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.OrgID,
		arg.Ip,
		arg.Details,
		arg.PrevHash,
		arg.Hash,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lastAuditHash = `-- name: LastAuditHash :one
SELECT hash FROM audit_events ORDER BY id DESC LIMIT 1
`

func (q *Queries) LastAuditHash(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, lastAuditHash)
	var hash []byte
	err := row.Scan(&hash)
	return hash, err
}

const listAuditEventsAsc = `-- name: ListAuditEventsAsc :many
SELECT id, ts, actor_type, actor_id, action, resource_type, resource_id, org_id, ip, details, prev_hash, hash FROM audit_events WHERE id > $1 ORDER BY id LIMIT $2
`

type ListAuditEventsAscParams struct {
	ID    int64 `json:"id"`
	Limit int32 `json:"limit"`
}

func (q *Queries) ListAuditEventsAsc(ctx context.Context, arg ListAuditEventsAscParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsAsc, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.OrgID,
			&i.Ip,
			&i.Details,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
