// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: certificates.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const certificatesUsingClient = `-- name: CertificatesUsingClient :many
SELECT name FROM (
  SELECT c.name AS name FROM certificates c
  WHERE c.org_id = $1
    AND (c.verification_rules @> jsonb_build_array(jsonb_build_object('clientId', $2::uuid::text))
      OR c.overrides->'verificationRules' @> jsonb_build_array(jsonb_build_object('clientId', $2::uuid::text)))
  UNION ALL
  SELECT 'org default rules' AS name
  WHERE EXISTS (SELECT 1 FROM issuance_defaults d WHERE d.org_id = $1
    AND d.config->'verificationRules' @> jsonb_build_array(jsonb_build_object('clientId', $2::uuid::text)))
  UNION ALL
  SELECT 'global default rules' AS name
  WHERE EXISTS (SELECT 1 FROM settings s WHERE s.key = 'section.issuance_defaults'
    AND s.value->'verificationRules' @> jsonb_build_array(jsonb_build_object('clientId', $2::uuid::text)))
) u ORDER BY lower(name) LIMIT 6
`

type CertificatesUsingClientParams struct {
	OrgID    uuid.UUID `json:"org_id"`
	ClientID uuid.UUID `json:"client_id"`
}

// Certificates whose own verification rules reference clientId, plus the
// literal "org default rules" when this org's issuance_defaults rules do
// (a default rule names no single certificate of its own), plus "global
// default rules" when the cross-org global issuance_defaults settings
// section does (settings.key = 'section.issuance_defaults', the same JSON
// shape as issuance_defaults.config: see settings.SectionKey and
// issuance.SettingsKey); DeleteClient 409s naming these instead of
// deleting a client an http-01/tls-alpn-01 rule still relies on.
func (q *Queries) CertificatesUsingClient(ctx context.Context, arg CertificatesUsingClientParams) ([]string, error) {
	rows, err := q.db.Query(ctx, certificatesUsingClient, arg.OrgID, arg.ClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCertificate = `-- name: CreateCertificate :one
INSERT INTO certificates (org_id, name, common_name, sans, verification_rules, overrides, next_renew_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
RETURNING id, org_id, name, common_name, sans, verification_rules, overrides, status, current_version_id, next_renew_at, failure_count, last_error, created_at, updated_at, managed, ari_window_start, ari_window_end, ari_checked_at, ari_retry_after
`

type CreateCertificateParams struct {
	OrgID             uuid.UUID `json:"org_id"`
	Name              string    `json:"name"`
	CommonName        string    `json:"common_name"`
	Sans              []string  `json:"sans"`
	VerificationRules []byte    `json:"verification_rules"`
	Overrides         []byte    `json:"overrides"`
}

func (q *Queries) CreateCertificate(ctx context.Context, arg CreateCertificateParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, createCertificate,
		arg.OrgID,
		arg.Name,
		arg.CommonName,
		arg.Sans,
		arg.VerificationRules,
		arg.Overrides,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CommonName,
		&i.Sans,
		&i.VerificationRules,
		&i.Overrides,
		&i.Status,
		&i.CurrentVersionID,
		&i.NextRenewAt,
		&i.FailureCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Managed,
		&i.AriWindowStart,
		&i.AriWindowEnd,
		&i.AriCheckedAt,
		&i.AriRetryAfter,
	)
	return i, err
}

const currentVersionsForCerts = `-- name: CurrentVersionsForCerts :many
SELECT id, current_version_id FROM certificates WHERE id = ANY($1::uuid[])
`

type CurrentVersionsForCertsRow struct {
	ID               uuid.UUID  `json:"id"`
	CurrentVersionID *uuid.UUID `json:"current_version_id"`
}

// Cert id -> current_version_id for a layout's extra certificates, used to
// render them (agents.Service.render) and to detect drift
// (StaleDeploymentGrantIDs mirrors this same lookup in SQL).
func (q *Queries) CurrentVersionsForCerts(ctx context.Context, ids []uuid.UUID) ([]CurrentVersionsForCertsRow, error) {
	rows, err := q.db.Query(ctx, currentVersionsForCerts, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentVersionsForCertsRow{}
	for rows.Next() {
		var i CurrentVersionsForCertsRow
		if err := rows.Scan(&i.ID, &i.CurrentVersionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCertificate = `-- name: DeleteCertificate :execrows
DELETE FROM certificates WHERE id = $1 AND org_id = $2
`

type DeleteCertificateParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteCertificate(ctx context.Context, arg DeleteCertificateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCertificate, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCertificate = `-- name: GetCertificate :one
SELECT id, org_id, name, common_name, sans, verification_rules, overrides, status, current_version_id, next_renew_at, failure_count, last_error, created_at, updated_at, managed, ari_window_start, ari_window_end, ari_checked_at, ari_retry_after FROM certificates WHERE id = $1 AND org_id = $2
`

type GetCertificateParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetCertificate(ctx context.Context, arg GetCertificateParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, getCertificate, arg.ID, arg.OrgID)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CommonName,
		&i.Sans,
		&i.VerificationRules,
		&i.Overrides,
		&i.Status,
		&i.CurrentVersionID,
		&i.NextRenewAt,
		&i.FailureCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Managed,
		&i.AriWindowStart,
		&i.AriWindowEnd,
		&i.AriCheckedAt,
		&i.AriRetryAfter,
	)
	return i, err
}

const getCertificateByID = `-- name: GetCertificateByID :one
SELECT id, org_id, name, common_name, sans, verification_rules, overrides, status, current_version_id, next_renew_at, failure_count, last_error, created_at, updated_at, managed, ari_window_start, ari_window_end, ari_checked_at, ari_retry_after FROM certificates WHERE id = $1
`

func (q *Queries) GetCertificateByID(ctx context.Context, id uuid.UUID) (Certificate, error) {
	row := q.db.QueryRow(ctx, getCertificateByID, id)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CommonName,
		&i.Sans,
		&i.VerificationRules,
		&i.Overrides,
		&i.Status,
		&i.CurrentVersionID,
		&i.NextRenewAt,
		&i.FailureCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Managed,
		&i.AriWindowStart,
		&i.AriWindowEnd,
		&i.AriCheckedAt,
		&i.AriRetryAfter,
	)
	return i, err
}

const getCertificateForUpdate = `-- name: GetCertificateForUpdate :one
SELECT id, org_id, name, common_name, sans, verification_rules, overrides, status, current_version_id, next_renew_at, failure_count, last_error, created_at, updated_at, managed, ari_window_start, ari_window_end, ari_checked_at, ari_retry_after FROM certificates WHERE id = $1 AND org_id = $2 FOR UPDATE
`

type GetCertificateForUpdateParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Locks the row for the duration of UpdateCertificate's read-compute-write,
// so a concurrent update cannot compute reissue from names that are already
// stale by the time this transaction commits.
func (q *Queries) GetCertificateForUpdate(ctx context.Context, arg GetCertificateForUpdateParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, getCertificateForUpdate, arg.ID, arg.OrgID)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CommonName,
		&i.Sans,
		&i.VerificationRules,
		&i.Overrides,
		&i.Status,
		&i.CurrentVersionID,
		&i.NextRenewAt,
		&i.FailureCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Managed,
		&i.AriWindowStart,
		&i.AriWindowEnd,
		&i.AriCheckedAt,
		&i.AriRetryAfter,
	)
	return i, err
}

const getCertificateVersion = `-- name: GetCertificateVersion :one
SELECT id, cert_id, serial, not_before, not_after, sha256_fp, key_type, leaf_der, chain_der, private_key, source, ari_window, revoked_at, created_at, ca_id FROM certificate_versions WHERE id = $1 AND cert_id = $2
`

type GetCertificateVersionParams struct {
	ID     uuid.UUID `json:"id"`
	CertID uuid.UUID `json:"cert_id"`
}

func (q *Queries) GetCertificateVersion(ctx context.Context, arg GetCertificateVersionParams) (CertificateVersion, error) {
	row := q.db.QueryRow(ctx, getCertificateVersion, arg.ID, arg.CertID)
	var i CertificateVersion
	err := row.Scan(
		&i.ID,
		&i.CertID,
		&i.Serial,
		&i.NotBefore,
		&i.NotAfter,
		&i.Sha256Fp,
		&i.KeyType,
		&i.LeafDer,
		&i.ChainDer,
		&i.PrivateKey,
		&i.Source,
		&i.AriWindow,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.CaID,
	)
	return i, err
}

const getOrgIssuanceDefaults = `-- name: GetOrgIssuanceDefaults :one
SELECT config FROM issuance_defaults WHERE org_id = $1
`

func (q *Queries) GetOrgIssuanceDefaults(ctx context.Context, orgID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getOrgIssuanceDefaults, orgID)
	var config []byte
	err := row.Scan(&config)
	return config, err
}

const insertCertificateVersion = `-- name: InsertCertificateVersion :one
INSERT INTO certificate_versions (cert_id, serial, not_before, not_after, sha256_fp, key_type, leaf_der, chain_der, private_key, source, ca_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, cert_id, serial, not_before, not_after, sha256_fp, key_type, source, ca_id, (private_key IS NOT NULL)::boolean AS has_key, revoked_at, created_at
`

type InsertCertificateVersionParams struct {
	CertID     uuid.UUID  `json:"cert_id"`
	Serial     string     `json:"serial"`
	NotBefore  time.Time  `json:"not_before"`
	NotAfter   time.Time  `json:"not_after"`
	Sha256Fp   string     `json:"sha256_fp"`
	KeyType    string     `json:"key_type"`
	LeafDer    []byte     `json:"leaf_der"`
	ChainDer   [][]byte   `json:"chain_der"`
	PrivateKey []byte     `json:"private_key"`
	Source     string     `json:"source"`
	CaID       *uuid.UUID `json:"ca_id"`
}

type InsertCertificateVersionRow struct {
	ID        uuid.UUID  `json:"id"`
	CertID    uuid.UUID  `json:"cert_id"`
	Serial    string     `json:"serial"`
	NotBefore time.Time  `json:"not_before"`
	NotAfter  time.Time  `json:"not_after"`
	Sha256Fp  string     `json:"sha256_fp"`
	KeyType   string     `json:"key_type"`
	Source    string     `json:"source"`
	CaID      *uuid.UUID `json:"ca_id"`
	HasKey    bool       `json:"has_key"`
	RevokedAt *time.Time `json:"revoked_at"`
	CreatedAt time.Time  `json:"created_at"`
}

// private_key is nullable (a keyless import/upload stores NULL); has_key
// reports whether one is stored without ever selecting the sealed bytes
// themselves into a metadata-only row.
func (q *Queries) InsertCertificateVersion(ctx context.Context, arg InsertCertificateVersionParams) (InsertCertificateVersionRow, error) {
	row := q.db.QueryRow(ctx, insertCertificateVersion,
		arg.CertID,
		arg.Serial,
		arg.NotBefore,
		arg.NotAfter,
		arg.Sha256Fp,
		arg.KeyType,
		arg.LeafDer,
		arg.ChainDer,
		arg.PrivateKey,
		arg.Source,
		arg.CaID,
	)
	var i InsertCertificateVersionRow
	err := row.Scan(
		&i.ID,
		&i.CertID,
		&i.Serial,
		&i.NotBefore,
		&i.NotAfter,
		&i.Sha256Fp,
		&i.KeyType,
		&i.Source,
		&i.CaID,
		&i.HasKey,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCertificateVersions = `-- name: ListCertificateVersions :many
SELECT id, cert_id, serial, not_before, not_after, sha256_fp, key_type, source, ca_id, (private_key IS NOT NULL)::boolean AS has_key, revoked_at, created_at
FROM certificate_versions WHERE cert_id = $1 ORDER BY created_at DESC
`

type ListCertificateVersionsRow struct {
	ID        uuid.UUID  `json:"id"`
	CertID    uuid.UUID  `json:"cert_id"`
	Serial    string     `json:"serial"`
	NotBefore time.Time  `json:"not_before"`
	NotAfter  time.Time  `json:"not_after"`
	Sha256Fp  string     `json:"sha256_fp"`
	KeyType   string     `json:"key_type"`
	Source    string     `json:"source"`
	CaID      *uuid.UUID `json:"ca_id"`
	HasKey    bool       `json:"has_key"`
	RevokedAt *time.Time `json:"revoked_at"`
	CreatedAt time.Time  `json:"created_at"`
}

func (q *Queries) ListCertificateVersions(ctx context.Context, certID uuid.UUID) ([]ListCertificateVersionsRow, error) {
	rows, err := q.db.Query(ctx, listCertificateVersions, certID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificateVersionsRow{}
	for rows.Next() {
		var i ListCertificateVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CertID,
			&i.Serial,
			&i.NotBefore,
			&i.NotAfter,
			&i.Sha256Fp,
			&i.KeyType,
			&i.Source,
			&i.CaID,
			&i.HasKey,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificateVersionsByIDs = `-- name: ListCertificateVersionsByIDs :many
SELECT id, cert_id, serial, not_before, not_after, sha256_fp, key_type, source, ca_id, (private_key IS NOT NULL)::boolean AS has_key, revoked_at, created_at
FROM certificate_versions WHERE id = ANY($1::uuid[])
`

type ListCertificateVersionsByIDsRow struct {
	ID        uuid.UUID  `json:"id"`
	CertID    uuid.UUID  `json:"cert_id"`
	Serial    string     `json:"serial"`
	NotBefore time.Time  `json:"not_before"`
	NotAfter  time.Time  `json:"not_after"`
	Sha256Fp  string     `json:"sha256_fp"`
	KeyType   string     `json:"key_type"`
	Source    string     `json:"source"`
	CaID      *uuid.UUID `json:"ca_id"`
	HasKey    bool       `json:"has_key"`
	RevokedAt *time.Time `json:"revoked_at"`
	CreatedAt time.Time  `json:"created_at"`
}

// Batch-loads version metadata for a set of ids in one round trip, so a
// certificate list page can render every item's currentVersion without one
// query per certificate.
func (q *Queries) ListCertificateVersionsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ListCertificateVersionsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listCertificateVersionsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificateVersionsByIDsRow{}
	for rows.Next() {
		var i ListCertificateVersionsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CertID,
			&i.Serial,
			&i.NotBefore,
			&i.NotAfter,
			&i.Sha256Fp,
			&i.KeyType,
			&i.Source,
			&i.CaID,
			&i.HasKey,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesPageByNameAsc = `-- name: ListCertificatesPageByNameAsc :many

SELECT c.id, c.org_id, c.name, c.common_name, c.sans, c.verification_rules, c.overrides, c.status, c.current_version_id, c.next_renew_at, c.failure_count, c.last_error, c.created_at, c.updated_at, c.managed, c.ari_window_start, c.ari_window_end, c.ari_checked_at, c.ari_retry_after, c.name AS sort_key FROM certificates c
WHERE c.org_id = ANY($1::uuid[])
  AND ($2::text = '' OR c.status = $2)
  AND ($3::text = ''
       OR position(lower($3::text) in lower(c.name)) > 0
       OR position(lower($3::text) in lower(c.common_name)) > 0
       OR EXISTS (SELECT 1 FROM unnest(c.sans) AS s WHERE position(lower($3::text) in lower(s)) > 0))
  AND (NOT $4::bool OR (c.name, c.id) > ($5::text, $6::uuid))
ORDER BY c.name ASC, c.id ASC
LIMIT $7::int
`

type ListCertificatesPageByNameAscParams struct {
	OrgIds       []uuid.UUID `json:"org_ids"`
	StatusFilter string      `json:"status_filter"`
	QFilter      string      `json:"q_filter"`
	HasCursor    bool        `json:"has_cursor"`
	LastKey      string      `json:"last_key"`
	LastID       uuid.UUID   `json:"last_id"`
	PageLimit    int32       `json:"page_limit"`
}

type ListCertificatesPageByNameAscRow struct {
	ID                uuid.UUID  `json:"id"`
	OrgID             uuid.UUID  `json:"org_id"`
	Name              string     `json:"name"`
	CommonName        string     `json:"common_name"`
	Sans              []string   `json:"sans"`
	VerificationRules []byte     `json:"verification_rules"`
	Overrides         []byte     `json:"overrides"`
	Status            string     `json:"status"`
	CurrentVersionID  *uuid.UUID `json:"current_version_id"`
	NextRenewAt       *time.Time `json:"next_renew_at"`
	FailureCount      int32      `json:"failure_count"`
	LastError         string     `json:"last_error"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	Managed           bool       `json:"managed"`
	AriWindowStart    *time.Time `json:"ari_window_start"`
	AriWindowEnd      *time.Time `json:"ari_window_end"`
	AriCheckedAt      *time.Time `json:"ari_checked_at"`
	AriRetryAfter     *time.Time `json:"ari_retry_after"`
	SortKey           string     `json:"sort_key"`
}

// The 8 queries below back ListCertificates' keyset-paged listing (one per
// supported sort field x direction). They share the same q/status filter
// and cursor shape:
//   - status_filter/q_filter: ” means "no filter"; q is a case-insensitive
//     substring match against the certificate's name, common name, and any
//     SAN (mirrors the old in-memory listParams.matches).
//   - has_cursor/last_key/last_id: has_cursor false means "first page";
//     otherwise the predicate resumes strictly after (last_key, last_id) in
//     the query's sort order, which is why every ORDER BY also breaks ties
//     on id.
//   - page_limit is the caller's page size + 1, so the handler can detect
//     whether there is a next page without a second round trip.
//
// A nullable sort column (next_renew_at, and not_after via the current
// version, which is null for a pending certificate) is coalesced to the
// X.509 "no well-defined expiration" sentinel (9999-12-31T23:59:59Z, well
// outside any real certificate lifetime) so it sorts last ascending and
// first descending — Postgres's own NULLS LAST/NULLS FIRST defaults —
// without the keyset predicate's row comparison ever seeing a NULL, which
// would otherwise silently exclude every subsequent row.
func (q *Queries) ListCertificatesPageByNameAsc(ctx context.Context, arg ListCertificatesPageByNameAscParams) ([]ListCertificatesPageByNameAscRow, error) {
	rows, err := q.db.Query(ctx, listCertificatesPageByNameAsc,
		arg.OrgIds,
		arg.StatusFilter,
		arg.QFilter,
		arg.HasCursor,
		arg.LastKey,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificatesPageByNameAscRow{}
	for rows.Next() {
		var i ListCertificatesPageByNameAscRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CommonName,
			&i.Sans,
			&i.VerificationRules,
			&i.Overrides,
			&i.Status,
			&i.CurrentVersionID,
			&i.NextRenewAt,
			&i.FailureCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Managed,
			&i.AriWindowStart,
			&i.AriWindowEnd,
			&i.AriCheckedAt,
			&i.AriRetryAfter,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesPageByNameDesc = `-- name: ListCertificatesPageByNameDesc :many
SELECT c.id, c.org_id, c.name, c.common_name, c.sans, c.verification_rules, c.overrides, c.status, c.current_version_id, c.next_renew_at, c.failure_count, c.last_error, c.created_at, c.updated_at, c.managed, c.ari_window_start, c.ari_window_end, c.ari_checked_at, c.ari_retry_after, c.name AS sort_key FROM certificates c
WHERE c.org_id = ANY($1::uuid[])
  AND ($2::text = '' OR c.status = $2)
  AND ($3::text = ''
       OR position(lower($3::text) in lower(c.name)) > 0
       OR position(lower($3::text) in lower(c.common_name)) > 0
       OR EXISTS (SELECT 1 FROM unnest(c.sans) AS s WHERE position(lower($3::text) in lower(s)) > 0))
  AND (NOT $4::bool OR (c.name, c.id) < ($5::text, $6::uuid))
ORDER BY c.name DESC, c.id DESC
LIMIT $7::int
`

type ListCertificatesPageByNameDescParams struct {
	OrgIds       []uuid.UUID `json:"org_ids"`
	StatusFilter string      `json:"status_filter"`
	QFilter      string      `json:"q_filter"`
	HasCursor    bool        `json:"has_cursor"`
	LastKey      string      `json:"last_key"`
	LastID       uuid.UUID   `json:"last_id"`
	PageLimit    int32       `json:"page_limit"`
}

type ListCertificatesPageByNameDescRow struct {
	ID                uuid.UUID  `json:"id"`
	OrgID             uuid.UUID  `json:"org_id"`
	Name              string     `json:"name"`
	CommonName        string     `json:"common_name"`
	Sans              []string   `json:"sans"`
	VerificationRules []byte     `json:"verification_rules"`
	Overrides         []byte     `json:"overrides"`
	Status            string     `json:"status"`
	CurrentVersionID  *uuid.UUID `json:"current_version_id"`
	NextRenewAt       *time.Time `json:"next_renew_at"`
	FailureCount      int32      `json:"failure_count"`
	LastError         string     `json:"last_error"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	Managed           bool       `json:"managed"`
	AriWindowStart    *time.Time `json:"ari_window_start"`
	AriWindowEnd      *time.Time `json:"ari_window_end"`
	AriCheckedAt      *time.Time `json:"ari_checked_at"`
	AriRetryAfter     *time.Time `json:"ari_retry_after"`
	SortKey           string     `json:"sort_key"`
}

func (q *Queries) ListCertificatesPageByNameDesc(ctx context.Context, arg ListCertificatesPageByNameDescParams) ([]ListCertificatesPageByNameDescRow, error) {
	rows, err := q.db.Query(ctx, listCertificatesPageByNameDesc,
		arg.OrgIds,
		arg.StatusFilter,
		arg.QFilter,
		arg.HasCursor,
		arg.LastKey,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificatesPageByNameDescRow{}
	for rows.Next() {
		var i ListCertificatesPageByNameDescRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CommonName,
			&i.Sans,
			&i.VerificationRules,
			&i.Overrides,
			&i.Status,
			&i.CurrentVersionID,
			&i.NextRenewAt,
			&i.FailureCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Managed,
			&i.AriWindowStart,
			&i.AriWindowEnd,
			&i.AriCheckedAt,
			&i.AriRetryAfter,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesPageByNextRenewAtAsc = `-- name: ListCertificatesPageByNextRenewAtAsc :many
SELECT c.id, c.org_id, c.name, c.common_name, c.sans, c.verification_rules, c.overrides, c.status, c.current_version_id, c.next_renew_at, c.failure_count, c.last_error, c.created_at, c.updated_at, c.managed, c.ari_window_start, c.ari_window_end, c.ari_checked_at, c.ari_retry_after, COALESCE(c.next_renew_at, TIMESTAMPTZ '9999-12-31 23:59:59+00') AS sort_key FROM certificates c
WHERE c.org_id = ANY($1::uuid[])
  AND ($2::text = '' OR c.status = $2)
  AND ($3::text = ''
       OR position(lower($3::text) in lower(c.name)) > 0
       OR position(lower($3::text) in lower(c.common_name)) > 0
       OR EXISTS (SELECT 1 FROM unnest(c.sans) AS s WHERE position(lower($3::text) in lower(s)) > 0))
  AND (NOT $4::bool
       OR (COALESCE(c.next_renew_at, TIMESTAMPTZ '9999-12-31 23:59:59+00'), c.id) > ($5::timestamptz, $6::uuid))
ORDER BY sort_key ASC, c.id ASC
LIMIT $7::int
`

type ListCertificatesPageByNextRenewAtAscParams struct {
	OrgIds       []uuid.UUID `json:"org_ids"`
	StatusFilter string      `json:"status_filter"`
	QFilter      string      `json:"q_filter"`
	HasCursor    bool        `json:"has_cursor"`
	LastKey      time.Time   `json:"last_key"`
	LastID       uuid.UUID   `json:"last_id"`
	PageLimit    int32       `json:"page_limit"`
}

type ListCertificatesPageByNextRenewAtAscRow struct {
	ID                uuid.UUID  `json:"id"`
	OrgID             uuid.UUID  `json:"org_id"`
	Name              string     `json:"name"`
	CommonName        string     `json:"common_name"`
	Sans              []string   `json:"sans"`
	VerificationRules []byte     `json:"verification_rules"`
	Overrides         []byte     `json:"overrides"`
	Status            string     `json:"status"`
	CurrentVersionID  *uuid.UUID `json:"current_version_id"`
	NextRenewAt       *time.Time `json:"next_renew_at"`
	FailureCount      int32      `json:"failure_count"`
	LastError         string     `json:"last_error"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	Managed           bool       `json:"managed"`
	AriWindowStart    *time.Time `json:"ari_window_start"`
	AriWindowEnd      *time.Time `json:"ari_window_end"`
	AriCheckedAt      *time.Time `json:"ari_checked_at"`
	AriRetryAfter     *time.Time `json:"ari_retry_after"`
	SortKey           *time.Time `json:"sort_key"`
}

func (q *Queries) ListCertificatesPageByNextRenewAtAsc(ctx context.Context, arg ListCertificatesPageByNextRenewAtAscParams) ([]ListCertificatesPageByNextRenewAtAscRow, error) {
	rows, err := q.db.Query(ctx, listCertificatesPageByNextRenewAtAsc,
		arg.OrgIds,
		arg.StatusFilter,
		arg.QFilter,
		arg.HasCursor,
		arg.LastKey,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificatesPageByNextRenewAtAscRow{}
	for rows.Next() {
		var i ListCertificatesPageByNextRenewAtAscRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CommonName,
			&i.Sans,
			&i.VerificationRules,
			&i.Overrides,
			&i.Status,
			&i.CurrentVersionID,
			&i.NextRenewAt,
			&i.FailureCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Managed,
			&i.AriWindowStart,
			&i.AriWindowEnd,
			&i.AriCheckedAt,
			&i.AriRetryAfter,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesPageByNextRenewAtDesc = `-- name: ListCertificatesPageByNextRenewAtDesc :many
SELECT c.id, c.org_id, c.name, c.common_name, c.sans, c.verification_rules, c.overrides, c.status, c.current_version_id, c.next_renew_at, c.failure_count, c.last_error, c.created_at, c.updated_at, c.managed, c.ari_window_start, c.ari_window_end, c.ari_checked_at, c.ari_retry_after, COALESCE(c.next_renew_at, TIMESTAMPTZ '9999-12-31 23:59:59+00') AS sort_key FROM certificates c
WHERE c.org_id = ANY($1::uuid[])
  AND ($2::text = '' OR c.status = $2)
  AND ($3::text = ''
       OR position(lower($3::text) in lower(c.name)) > 0
       OR position(lower($3::text) in lower(c.common_name)) > 0
       OR EXISTS (SELECT 1 FROM unnest(c.sans) AS s WHERE position(lower($3::text) in lower(s)) > 0))
  AND (NOT $4::bool
       OR (COALESCE(c.next_renew_at, TIMESTAMPTZ '9999-12-31 23:59:59+00'), c.id) < ($5::timestamptz, $6::uuid))
ORDER BY sort_key DESC, c.id DESC
LIMIT $7::int
`

type ListCertificatesPageByNextRenewAtDescParams struct {
	OrgIds       []uuid.UUID `json:"org_ids"`
	StatusFilter string      `json:"status_filter"`
	QFilter      string      `json:"q_filter"`
	HasCursor    bool        `json:"has_cursor"`
	LastKey      time.Time   `json:"last_key"`
	LastID       uuid.UUID   `json:"last_id"`
	PageLimit    int32       `json:"page_limit"`
}

type ListCertificatesPageByNextRenewAtDescRow struct {
	ID                uuid.UUID  `json:"id"`
	OrgID             uuid.UUID  `json:"org_id"`
	Name              string     `json:"name"`
	CommonName        string     `json:"common_name"`
	Sans              []string   `json:"sans"`
	VerificationRules []byte     `json:"verification_rules"`
	Overrides         []byte     `json:"overrides"`
	Status            string     `json:"status"`
	CurrentVersionID  *uuid.UUID `json:"current_version_id"`
	NextRenewAt       *time.Time `json:"next_renew_at"`
	FailureCount      int32      `json:"failure_count"`
	LastError         string     `json:"last_error"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	Managed           bool       `json:"managed"`
	AriWindowStart    *time.Time `json:"ari_window_start"`
	AriWindowEnd      *time.Time `json:"ari_window_end"`
	AriCheckedAt      *time.Time `json:"ari_checked_at"`
	AriRetryAfter     *time.Time `json:"ari_retry_after"`
	SortKey           *time.Time `json:"sort_key"`
}

func (q *Queries) ListCertificatesPageByNextRenewAtDesc(ctx context.Context, arg ListCertificatesPageByNextRenewAtDescParams) ([]ListCertificatesPageByNextRenewAtDescRow, error) {
	rows, err := q.db.Query(ctx, listCertificatesPageByNextRenewAtDesc,
		arg.OrgIds,
		arg.StatusFilter,
		arg.QFilter,
		arg.HasCursor,
		arg.LastKey,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificatesPageByNextRenewAtDescRow{}
	for rows.Next() {
		var i ListCertificatesPageByNextRenewAtDescRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CommonName,
			&i.Sans,
			&i.VerificationRules,
			&i.Overrides,
			&i.Status,
			&i.CurrentVersionID,
			&i.NextRenewAt,
			&i.FailureCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Managed,
			&i.AriWindowStart,
			&i.AriWindowEnd,
			&i.AriCheckedAt,
			&i.AriRetryAfter,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesPageByNotAfterAsc = `-- name: ListCertificatesPageByNotAfterAsc :many
SELECT c.id, c.org_id, c.name, c.common_name, c.sans, c.verification_rules, c.overrides, c.status, c.current_version_id, c.next_renew_at, c.failure_count, c.last_error, c.created_at, c.updated_at, c.managed, c.ari_window_start, c.ari_window_end, c.ari_checked_at, c.ari_retry_after, COALESCE(v.not_after, TIMESTAMPTZ '9999-12-31 23:59:59+00') AS sort_key
FROM certificates c
LEFT JOIN certificate_versions v ON v.id = c.current_version_id
WHERE c.org_id = ANY($1::uuid[])
  AND ($2::text = '' OR c.status = $2)
  AND ($3::text = ''
       OR position(lower($3::text) in lower(c.name)) > 0
       OR position(lower($3::text) in lower(c.common_name)) > 0
       OR EXISTS (SELECT 1 FROM unnest(c.sans) AS s WHERE position(lower($3::text) in lower(s)) > 0))
  AND (NOT $4::bool
       OR (COALESCE(v.not_after, TIMESTAMPTZ '9999-12-31 23:59:59+00'), c.id) > ($5::timestamptz, $6::uuid))
ORDER BY sort_key ASC, c.id ASC
LIMIT $7::int
`

type ListCertificatesPageByNotAfterAscParams struct {
	OrgIds       []uuid.UUID `json:"org_ids"`
	StatusFilter string      `json:"status_filter"`
	QFilter      string      `json:"q_filter"`
	HasCursor    bool        `json:"has_cursor"`
	LastKey      time.Time   `json:"last_key"`
	LastID       uuid.UUID   `json:"last_id"`
	PageLimit    int32       `json:"page_limit"`
}

type ListCertificatesPageByNotAfterAscRow struct {
	ID                uuid.UUID  `json:"id"`
	OrgID             uuid.UUID  `json:"org_id"`
	Name              string     `json:"name"`
	CommonName        string     `json:"common_name"`
	Sans              []string   `json:"sans"`
	VerificationRules []byte     `json:"verification_rules"`
	Overrides         []byte     `json:"overrides"`
	Status            string     `json:"status"`
	CurrentVersionID  *uuid.UUID `json:"current_version_id"`
	NextRenewAt       *time.Time `json:"next_renew_at"`
	FailureCount      int32      `json:"failure_count"`
	LastError         string     `json:"last_error"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	Managed           bool       `json:"managed"`
	AriWindowStart    *time.Time `json:"ari_window_start"`
	AriWindowEnd      *time.Time `json:"ari_window_end"`
	AriCheckedAt      *time.Time `json:"ari_checked_at"`
	AriRetryAfter     *time.Time `json:"ari_retry_after"`
	SortKey           time.Time  `json:"sort_key"`
}

func (q *Queries) ListCertificatesPageByNotAfterAsc(ctx context.Context, arg ListCertificatesPageByNotAfterAscParams) ([]ListCertificatesPageByNotAfterAscRow, error) {
	rows, err := q.db.Query(ctx, listCertificatesPageByNotAfterAsc,
		arg.OrgIds,
		arg.StatusFilter,
		arg.QFilter,
		arg.HasCursor,
		arg.LastKey,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificatesPageByNotAfterAscRow{}
	for rows.Next() {
		var i ListCertificatesPageByNotAfterAscRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CommonName,
			&i.Sans,
			&i.VerificationRules,
			&i.Overrides,
			&i.Status,
			&i.CurrentVersionID,
			&i.NextRenewAt,
			&i.FailureCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Managed,
			&i.AriWindowStart,
			&i.AriWindowEnd,
			&i.AriCheckedAt,
			&i.AriRetryAfter,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesPageByNotAfterDesc = `-- name: ListCertificatesPageByNotAfterDesc :many
SELECT c.id, c.org_id, c.name, c.common_name, c.sans, c.verification_rules, c.overrides, c.status, c.current_version_id, c.next_renew_at, c.failure_count, c.last_error, c.created_at, c.updated_at, c.managed, c.ari_window_start, c.ari_window_end, c.ari_checked_at, c.ari_retry_after, COALESCE(v.not_after, TIMESTAMPTZ '9999-12-31 23:59:59+00') AS sort_key
FROM certificates c
LEFT JOIN certificate_versions v ON v.id = c.current_version_id
WHERE c.org_id = ANY($1::uuid[])
  AND ($2::text = '' OR c.status = $2)
  AND ($3::text = ''
       OR position(lower($3::text) in lower(c.name)) > 0
       OR position(lower($3::text) in lower(c.common_name)) > 0
       OR EXISTS (SELECT 1 FROM unnest(c.sans) AS s WHERE position(lower($3::text) in lower(s)) > 0))
  AND (NOT $4::bool
       OR (COALESCE(v.not_after, TIMESTAMPTZ '9999-12-31 23:59:59+00'), c.id) < ($5::timestamptz, $6::uuid))
ORDER BY sort_key DESC, c.id DESC
LIMIT $7::int
`

type ListCertificatesPageByNotAfterDescParams struct {
	OrgIds       []uuid.UUID `json:"org_ids"`
	StatusFilter string      `json:"status_filter"`
	QFilter      string      `json:"q_filter"`
	HasCursor    bool        `json:"has_cursor"`
	LastKey      time.Time   `json:"last_key"`
	LastID       uuid.UUID   `json:"last_id"`
	PageLimit    int32       `json:"page_limit"`
}

type ListCertificatesPageByNotAfterDescRow struct {
	ID                uuid.UUID  `json:"id"`
	OrgID             uuid.UUID  `json:"org_id"`
	Name              string     `json:"name"`
	CommonName        string     `json:"common_name"`
	Sans              []string   `json:"sans"`
	VerificationRules []byte     `json:"verification_rules"`
	Overrides         []byte     `json:"overrides"`
	Status            string     `json:"status"`
	CurrentVersionID  *uuid.UUID `json:"current_version_id"`
	NextRenewAt       *time.Time `json:"next_renew_at"`
	FailureCount      int32      `json:"failure_count"`
	LastError         string     `json:"last_error"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	Managed           bool       `json:"managed"`
	AriWindowStart    *time.Time `json:"ari_window_start"`
	AriWindowEnd      *time.Time `json:"ari_window_end"`
	AriCheckedAt      *time.Time `json:"ari_checked_at"`
	AriRetryAfter     *time.Time `json:"ari_retry_after"`
	SortKey           time.Time  `json:"sort_key"`
}

func (q *Queries) ListCertificatesPageByNotAfterDesc(ctx context.Context, arg ListCertificatesPageByNotAfterDescParams) ([]ListCertificatesPageByNotAfterDescRow, error) {
	rows, err := q.db.Query(ctx, listCertificatesPageByNotAfterDesc,
		arg.OrgIds,
		arg.StatusFilter,
		arg.QFilter,
		arg.HasCursor,
		arg.LastKey,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificatesPageByNotAfterDescRow{}
	for rows.Next() {
		var i ListCertificatesPageByNotAfterDescRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CommonName,
			&i.Sans,
			&i.VerificationRules,
			&i.Overrides,
			&i.Status,
			&i.CurrentVersionID,
			&i.NextRenewAt,
			&i.FailureCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Managed,
			&i.AriWindowStart,
			&i.AriWindowEnd,
			&i.AriCheckedAt,
			&i.AriRetryAfter,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesPageByStatusAsc = `-- name: ListCertificatesPageByStatusAsc :many
SELECT c.id, c.org_id, c.name, c.common_name, c.sans, c.verification_rules, c.overrides, c.status, c.current_version_id, c.next_renew_at, c.failure_count, c.last_error, c.created_at, c.updated_at, c.managed, c.ari_window_start, c.ari_window_end, c.ari_checked_at, c.ari_retry_after, c.status AS sort_key FROM certificates c
WHERE c.org_id = ANY($1::uuid[])
  AND ($2::text = '' OR c.status = $2)
  AND ($3::text = ''
       OR position(lower($3::text) in lower(c.name)) > 0
       OR position(lower($3::text) in lower(c.common_name)) > 0
       OR EXISTS (SELECT 1 FROM unnest(c.sans) AS s WHERE position(lower($3::text) in lower(s)) > 0))
  AND (NOT $4::bool OR (c.status, c.id) > ($5::text, $6::uuid))
ORDER BY c.status ASC, c.id ASC
LIMIT $7::int
`

type ListCertificatesPageByStatusAscParams struct {
	OrgIds       []uuid.UUID `json:"org_ids"`
	StatusFilter string      `json:"status_filter"`
	QFilter      string      `json:"q_filter"`
	HasCursor    bool        `json:"has_cursor"`
	LastKey      string      `json:"last_key"`
	LastID       uuid.UUID   `json:"last_id"`
	PageLimit    int32       `json:"page_limit"`
}

type ListCertificatesPageByStatusAscRow struct {
	ID                uuid.UUID  `json:"id"`
	OrgID             uuid.UUID  `json:"org_id"`
	Name              string     `json:"name"`
	CommonName        string     `json:"common_name"`
	Sans              []string   `json:"sans"`
	VerificationRules []byte     `json:"verification_rules"`
	Overrides         []byte     `json:"overrides"`
	Status            string     `json:"status"`
	CurrentVersionID  *uuid.UUID `json:"current_version_id"`
	NextRenewAt       *time.Time `json:"next_renew_at"`
	FailureCount      int32      `json:"failure_count"`
	LastError         string     `json:"last_error"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	Managed           bool       `json:"managed"`
	AriWindowStart    *time.Time `json:"ari_window_start"`
	AriWindowEnd      *time.Time `json:"ari_window_end"`
	AriCheckedAt      *time.Time `json:"ari_checked_at"`
	AriRetryAfter     *time.Time `json:"ari_retry_after"`
	SortKey           string     `json:"sort_key"`
}

func (q *Queries) ListCertificatesPageByStatusAsc(ctx context.Context, arg ListCertificatesPageByStatusAscParams) ([]ListCertificatesPageByStatusAscRow, error) {
	rows, err := q.db.Query(ctx, listCertificatesPageByStatusAsc,
		arg.OrgIds,
		arg.StatusFilter,
		arg.QFilter,
		arg.HasCursor,
		arg.LastKey,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificatesPageByStatusAscRow{}
	for rows.Next() {
		var i ListCertificatesPageByStatusAscRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CommonName,
			&i.Sans,
			&i.VerificationRules,
			&i.Overrides,
			&i.Status,
			&i.CurrentVersionID,
			&i.NextRenewAt,
			&i.FailureCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Managed,
			&i.AriWindowStart,
			&i.AriWindowEnd,
			&i.AriCheckedAt,
			&i.AriRetryAfter,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesPageByStatusDesc = `-- name: ListCertificatesPageByStatusDesc :many
SELECT c.id, c.org_id, c.name, c.common_name, c.sans, c.verification_rules, c.overrides, c.status, c.current_version_id, c.next_renew_at, c.failure_count, c.last_error, c.created_at, c.updated_at, c.managed, c.ari_window_start, c.ari_window_end, c.ari_checked_at, c.ari_retry_after, c.status AS sort_key FROM certificates c
WHERE c.org_id = ANY($1::uuid[])
  AND ($2::text = '' OR c.status = $2)
  AND ($3::text = ''
       OR position(lower($3::text) in lower(c.name)) > 0
       OR position(lower($3::text) in lower(c.common_name)) > 0
       OR EXISTS (SELECT 1 FROM unnest(c.sans) AS s WHERE position(lower($3::text) in lower(s)) > 0))
  AND (NOT $4::bool OR (c.status, c.id) < ($5::text, $6::uuid))
ORDER BY c.status DESC, c.id DESC
LIMIT $7::int
`

type ListCertificatesPageByStatusDescParams struct {
	OrgIds       []uuid.UUID `json:"org_ids"`
	StatusFilter string      `json:"status_filter"`
	QFilter      string      `json:"q_filter"`
	HasCursor    bool        `json:"has_cursor"`
	LastKey      string      `json:"last_key"`
	LastID       uuid.UUID   `json:"last_id"`
	PageLimit    int32       `json:"page_limit"`
}

type ListCertificatesPageByStatusDescRow struct {
	ID                uuid.UUID  `json:"id"`
	OrgID             uuid.UUID  `json:"org_id"`
	Name              string     `json:"name"`
	CommonName        string     `json:"common_name"`
	Sans              []string   `json:"sans"`
	VerificationRules []byte     `json:"verification_rules"`
	Overrides         []byte     `json:"overrides"`
	Status            string     `json:"status"`
	CurrentVersionID  *uuid.UUID `json:"current_version_id"`
	NextRenewAt       *time.Time `json:"next_renew_at"`
	FailureCount      int32      `json:"failure_count"`
	LastError         string     `json:"last_error"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	Managed           bool       `json:"managed"`
	AriWindowStart    *time.Time `json:"ari_window_start"`
	AriWindowEnd      *time.Time `json:"ari_window_end"`
	AriCheckedAt      *time.Time `json:"ari_checked_at"`
	AriRetryAfter     *time.Time `json:"ari_retry_after"`
	SortKey           string     `json:"sort_key"`
}

func (q *Queries) ListCertificatesPageByStatusDesc(ctx context.Context, arg ListCertificatesPageByStatusDescParams) ([]ListCertificatesPageByStatusDescRow, error) {
	rows, err := q.db.Query(ctx, listCertificatesPageByStatusDesc,
		arg.OrgIds,
		arg.StatusFilter,
		arg.QFilter,
		arg.HasCursor,
		arg.LastKey,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificatesPageByStatusDescRow{}
	for rows.Next() {
		var i ListCertificatesPageByStatusDescRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CommonName,
			&i.Sans,
			&i.VerificationRules,
			&i.Overrides,
			&i.Status,
			&i.CurrentVersionID,
			&i.NextRenewAt,
			&i.FailureCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Managed,
			&i.AriWindowStart,
			&i.AriWindowEnd,
			&i.AriCheckedAt,
			&i.AriRetryAfter,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueCertificateIDs = `-- name: ListDueCertificateIDs :many
SELECT id FROM certificates
WHERE next_renew_at IS NOT NULL AND next_renew_at <= now()
ORDER BY next_renew_at
LIMIT $1
`

func (q *Queries) ListDueCertificateIDs(ctx context.Context, limit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDueCertificateIDs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCertificateFailed = `-- name: MarkCertificateFailed :exec
UPDATE certificates SET status = $2, failure_count = $3, last_error = $4, next_renew_at = $5, updated_at = now()
WHERE id = $1
`

type MarkCertificateFailedParams struct {
	ID           uuid.UUID  `json:"id"`
	Status       string     `json:"status"`
	FailureCount int32      `json:"failure_count"`
	LastError    string     `json:"last_error"`
	NextRenewAt  *time.Time `json:"next_renew_at"`
}

func (q *Queries) MarkCertificateFailed(ctx context.Context, arg MarkCertificateFailedParams) error {
	_, err := q.db.Exec(ctx, markCertificateFailed,
		arg.ID,
		arg.Status,
		arg.FailureCount,
		arg.LastError,
		arg.NextRenewAt,
	)
	return err
}

const markCertificateIssued = `-- name: MarkCertificateIssued :one
UPDATE certificates SET status = 'active', current_version_id = $2,
    next_renew_at = CASE WHEN common_name = $3 AND sans = $4
                          THEN $5::timestamptz ELSE now() END,
    failure_count = 0, last_error = '', updated_at = now()
WHERE id = $1
RETURNING next_renew_at
`

type MarkCertificateIssuedParams struct {
	ID               uuid.UUID  `json:"id"`
	CurrentVersionID *uuid.UUID `json:"current_version_id"`
	IssuedCommonName string     `json:"issued_common_name"`
	IssuedSans       []string   `json:"issued_sans"`
	NextRenewAt      time.Time  `json:"next_renew_at"`
}

// issued_common_name/issued_sans are the names the version being stored
// actually covers (as captured when the attempt started). If the row's
// current common_name/sans no longer match — an operator changed the
// certificate's names while this attempt was running — the CASE keeps
// next_renew_at at now() instead of the normal renewal date
// (next_renew_at), so the scheduler reissues for the new names within its
// next sweep instead of losing the edit for the certificate's whole
// lifetime. The comparison and the write happen in one statement (no
// separate FOR UPDATE read) so there is no window for a concurrent name
// change to race between reading and writing.
func (q *Queries) MarkCertificateIssued(ctx context.Context, arg MarkCertificateIssuedParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, markCertificateIssued,
		arg.ID,
		arg.CurrentVersionID,
		arg.IssuedCommonName,
		arg.IssuedSans,
		arg.NextRenewAt,
	)
	var next_renew_at *time.Time
	err := row.Scan(&next_renew_at)
	return next_renew_at, err
}

const markExpiredCertificates = `-- name: MarkExpiredCertificates :execrows
UPDATE certificates c SET status = 'expired', updated_at = now()
FROM certificate_versions v
WHERE v.id = c.current_version_id AND c.status IN ('active', 'failed') AND v.not_after < now()
`

func (q *Queries) MarkExpiredCertificates(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markExpiredCertificates)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCertificate = `-- name: UpdateCertificate :one
UPDATE certificates SET name = $3, common_name = $4, sans = $5, verification_rules = $6,
    overrides = $7, next_renew_at = CASE WHEN $8::bool THEN now() ELSE next_renew_at END,
    updated_at = now()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, common_name, sans, verification_rules, overrides, status, current_version_id, next_renew_at, failure_count, last_error, created_at, updated_at, managed, ari_window_start, ari_window_end, ari_checked_at, ari_retry_after
`

type UpdateCertificateParams struct {
	ID                uuid.UUID `json:"id"`
	OrgID             uuid.UUID `json:"org_id"`
	Name              string    `json:"name"`
	CommonName        string    `json:"common_name"`
	Sans              []string  `json:"sans"`
	VerificationRules []byte    `json:"verification_rules"`
	Overrides         []byte    `json:"overrides"`
	Reissue           bool      `json:"reissue"`
}

func (q *Queries) UpdateCertificate(ctx context.Context, arg UpdateCertificateParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, updateCertificate,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.CommonName,
		arg.Sans,
		arg.VerificationRules,
		arg.Overrides,
		arg.Reissue,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CommonName,
		&i.Sans,
		&i.VerificationRules,
		&i.Overrides,
		&i.Status,
		&i.CurrentVersionID,
		&i.NextRenewAt,
		&i.FailureCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Managed,
		&i.AriWindowStart,
		&i.AriWindowEnd,
		&i.AriCheckedAt,
		&i.AriRetryAfter,
	)
	return i, err
}

const upsertOrgIssuanceDefaults = `-- name: UpsertOrgIssuanceDefaults :exec
INSERT INTO issuance_defaults (org_id, config) VALUES ($1, $2)
ON CONFLICT (org_id) DO UPDATE SET config = EXCLUDED.config, updated_at = now()
`

type UpsertOrgIssuanceDefaultsParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	Config []byte    `json:"config"`
}

func (q *Queries) UpsertOrgIssuanceDefaults(ctx context.Context, arg UpsertOrgIssuanceDefaultsParams) error {
	_, err := q.db.Exec(ctx, upsertOrgIssuanceDefaults, arg.OrgID, arg.Config)
	return err
}
