// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: certificates.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCertificate = `-- name: CreateCertificate :one
INSERT INTO certificates (org_id, name, common_name, sans, verification_rules, overrides, next_renew_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
RETURNING id, org_id, name, common_name, sans, verification_rules, overrides, status, current_version_id, next_renew_at, failure_count, last_error, created_at, updated_at
`

type CreateCertificateParams struct {
	OrgID             uuid.UUID `json:"org_id"`
	Name              string    `json:"name"`
	CommonName        string    `json:"common_name"`
	Sans              []string  `json:"sans"`
	VerificationRules []byte    `json:"verification_rules"`
	Overrides         []byte    `json:"overrides"`
}

func (q *Queries) CreateCertificate(ctx context.Context, arg CreateCertificateParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, createCertificate,
		arg.OrgID,
		arg.Name,
		arg.CommonName,
		arg.Sans,
		arg.VerificationRules,
		arg.Overrides,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CommonName,
		&i.Sans,
		&i.VerificationRules,
		&i.Overrides,
		&i.Status,
		&i.CurrentVersionID,
		&i.NextRenewAt,
		&i.FailureCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCertificate = `-- name: DeleteCertificate :execrows
DELETE FROM certificates WHERE id = $1 AND org_id = $2
`

type DeleteCertificateParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteCertificate(ctx context.Context, arg DeleteCertificateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCertificate, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCertificate = `-- name: GetCertificate :one
SELECT id, org_id, name, common_name, sans, verification_rules, overrides, status, current_version_id, next_renew_at, failure_count, last_error, created_at, updated_at FROM certificates WHERE id = $1 AND org_id = $2
`

type GetCertificateParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetCertificate(ctx context.Context, arg GetCertificateParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, getCertificate, arg.ID, arg.OrgID)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CommonName,
		&i.Sans,
		&i.VerificationRules,
		&i.Overrides,
		&i.Status,
		&i.CurrentVersionID,
		&i.NextRenewAt,
		&i.FailureCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCertificateByID = `-- name: GetCertificateByID :one
SELECT id, org_id, name, common_name, sans, verification_rules, overrides, status, current_version_id, next_renew_at, failure_count, last_error, created_at, updated_at FROM certificates WHERE id = $1
`

func (q *Queries) GetCertificateByID(ctx context.Context, id uuid.UUID) (Certificate, error) {
	row := q.db.QueryRow(ctx, getCertificateByID, id)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CommonName,
		&i.Sans,
		&i.VerificationRules,
		&i.Overrides,
		&i.Status,
		&i.CurrentVersionID,
		&i.NextRenewAt,
		&i.FailureCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCertificateVersion = `-- name: GetCertificateVersion :one
SELECT id, cert_id, serial, not_before, not_after, sha256_fp, key_type, leaf_der, chain_der, private_key, source, ari_window, revoked_at, created_at FROM certificate_versions WHERE id = $1 AND cert_id = $2
`

type GetCertificateVersionParams struct {
	ID     uuid.UUID `json:"id"`
	CertID uuid.UUID `json:"cert_id"`
}

func (q *Queries) GetCertificateVersion(ctx context.Context, arg GetCertificateVersionParams) (CertificateVersion, error) {
	row := q.db.QueryRow(ctx, getCertificateVersion, arg.ID, arg.CertID)
	var i CertificateVersion
	err := row.Scan(
		&i.ID,
		&i.CertID,
		&i.Serial,
		&i.NotBefore,
		&i.NotAfter,
		&i.Sha256Fp,
		&i.KeyType,
		&i.LeafDer,
		&i.ChainDer,
		&i.PrivateKey,
		&i.Source,
		&i.AriWindow,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgIssuanceDefaults = `-- name: GetOrgIssuanceDefaults :one
SELECT config FROM issuance_defaults WHERE org_id = $1
`

func (q *Queries) GetOrgIssuanceDefaults(ctx context.Context, orgID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getOrgIssuanceDefaults, orgID)
	var config []byte
	err := row.Scan(&config)
	return config, err
}

const insertCertificateVersion = `-- name: InsertCertificateVersion :one
INSERT INTO certificate_versions (cert_id, serial, not_before, not_after, sha256_fp, key_type, leaf_der, chain_der, private_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, cert_id, serial, not_before, not_after, sha256_fp, key_type, source, revoked_at, created_at
`

type InsertCertificateVersionParams struct {
	CertID     uuid.UUID `json:"cert_id"`
	Serial     string    `json:"serial"`
	NotBefore  time.Time `json:"not_before"`
	NotAfter   time.Time `json:"not_after"`
	Sha256Fp   string    `json:"sha256_fp"`
	KeyType    string    `json:"key_type"`
	LeafDer    []byte    `json:"leaf_der"`
	ChainDer   [][]byte  `json:"chain_der"`
	PrivateKey []byte    `json:"private_key"`
}

type InsertCertificateVersionRow struct {
	ID        uuid.UUID  `json:"id"`
	CertID    uuid.UUID  `json:"cert_id"`
	Serial    string     `json:"serial"`
	NotBefore time.Time  `json:"not_before"`
	NotAfter  time.Time  `json:"not_after"`
	Sha256Fp  string     `json:"sha256_fp"`
	KeyType   string     `json:"key_type"`
	Source    string     `json:"source"`
	RevokedAt *time.Time `json:"revoked_at"`
	CreatedAt time.Time  `json:"created_at"`
}

func (q *Queries) InsertCertificateVersion(ctx context.Context, arg InsertCertificateVersionParams) (InsertCertificateVersionRow, error) {
	row := q.db.QueryRow(ctx, insertCertificateVersion,
		arg.CertID,
		arg.Serial,
		arg.NotBefore,
		arg.NotAfter,
		arg.Sha256Fp,
		arg.KeyType,
		arg.LeafDer,
		arg.ChainDer,
		arg.PrivateKey,
	)
	var i InsertCertificateVersionRow
	err := row.Scan(
		&i.ID,
		&i.CertID,
		&i.Serial,
		&i.NotBefore,
		&i.NotAfter,
		&i.Sha256Fp,
		&i.KeyType,
		&i.Source,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCertificateVersions = `-- name: ListCertificateVersions :many
SELECT id, cert_id, serial, not_before, not_after, sha256_fp, key_type, source, revoked_at, created_at
FROM certificate_versions WHERE cert_id = $1 ORDER BY created_at DESC
`

type ListCertificateVersionsRow struct {
	ID        uuid.UUID  `json:"id"`
	CertID    uuid.UUID  `json:"cert_id"`
	Serial    string     `json:"serial"`
	NotBefore time.Time  `json:"not_before"`
	NotAfter  time.Time  `json:"not_after"`
	Sha256Fp  string     `json:"sha256_fp"`
	KeyType   string     `json:"key_type"`
	Source    string     `json:"source"`
	RevokedAt *time.Time `json:"revoked_at"`
	CreatedAt time.Time  `json:"created_at"`
}

func (q *Queries) ListCertificateVersions(ctx context.Context, certID uuid.UUID) ([]ListCertificateVersionsRow, error) {
	rows, err := q.db.Query(ctx, listCertificateVersions, certID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificateVersionsRow{}
	for rows.Next() {
		var i ListCertificateVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CertID,
			&i.Serial,
			&i.NotBefore,
			&i.NotAfter,
			&i.Sha256Fp,
			&i.KeyType,
			&i.Source,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificates = `-- name: ListCertificates :many
SELECT id, org_id, name, common_name, sans, verification_rules, overrides, status, current_version_id, next_renew_at, failure_count, last_error, created_at, updated_at FROM certificates WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListCertificates(ctx context.Context, orgID uuid.UUID) ([]Certificate, error) {
	rows, err := q.db.Query(ctx, listCertificates, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Certificate{}
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CommonName,
			&i.Sans,
			&i.VerificationRules,
			&i.Overrides,
			&i.Status,
			&i.CurrentVersionID,
			&i.NextRenewAt,
			&i.FailureCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueCertificateIDs = `-- name: ListDueCertificateIDs :many
SELECT id FROM certificates
WHERE next_renew_at IS NOT NULL AND next_renew_at <= now()
ORDER BY next_renew_at
LIMIT $1
`

func (q *Queries) ListDueCertificateIDs(ctx context.Context, limit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDueCertificateIDs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCertificateFailed = `-- name: MarkCertificateFailed :exec
UPDATE certificates SET status = $2, failure_count = $3, last_error = $4, next_renew_at = $5, updated_at = now()
WHERE id = $1
`

type MarkCertificateFailedParams struct {
	ID           uuid.UUID  `json:"id"`
	Status       string     `json:"status"`
	FailureCount int32      `json:"failure_count"`
	LastError    string     `json:"last_error"`
	NextRenewAt  *time.Time `json:"next_renew_at"`
}

func (q *Queries) MarkCertificateFailed(ctx context.Context, arg MarkCertificateFailedParams) error {
	_, err := q.db.Exec(ctx, markCertificateFailed,
		arg.ID,
		arg.Status,
		arg.FailureCount,
		arg.LastError,
		arg.NextRenewAt,
	)
	return err
}

const markCertificateIssued = `-- name: MarkCertificateIssued :exec
UPDATE certificates SET status = 'active', current_version_id = $2, next_renew_at = $3,
    failure_count = 0, last_error = '', updated_at = now()
WHERE id = $1
`

type MarkCertificateIssuedParams struct {
	ID               uuid.UUID  `json:"id"`
	CurrentVersionID *uuid.UUID `json:"current_version_id"`
	NextRenewAt      *time.Time `json:"next_renew_at"`
}

func (q *Queries) MarkCertificateIssued(ctx context.Context, arg MarkCertificateIssuedParams) error {
	_, err := q.db.Exec(ctx, markCertificateIssued, arg.ID, arg.CurrentVersionID, arg.NextRenewAt)
	return err
}

const markExpiredCertificates = `-- name: MarkExpiredCertificates :execrows
UPDATE certificates c SET status = 'expired', updated_at = now()
FROM certificate_versions v
WHERE v.id = c.current_version_id AND c.status IN ('active', 'failed') AND v.not_after < now()
`

func (q *Queries) MarkExpiredCertificates(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markExpiredCertificates)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCertificate = `-- name: UpdateCertificate :one
UPDATE certificates SET name = $3, common_name = $4, sans = $5, verification_rules = $6,
    overrides = $7, next_renew_at = CASE WHEN $8::bool THEN now() ELSE next_renew_at END,
    updated_at = now()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, common_name, sans, verification_rules, overrides, status, current_version_id, next_renew_at, failure_count, last_error, created_at, updated_at
`

type UpdateCertificateParams struct {
	ID                uuid.UUID `json:"id"`
	OrgID             uuid.UUID `json:"org_id"`
	Name              string    `json:"name"`
	CommonName        string    `json:"common_name"`
	Sans              []string  `json:"sans"`
	VerificationRules []byte    `json:"verification_rules"`
	Overrides         []byte    `json:"overrides"`
	Reissue           bool      `json:"reissue"`
}

func (q *Queries) UpdateCertificate(ctx context.Context, arg UpdateCertificateParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, updateCertificate,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.CommonName,
		arg.Sans,
		arg.VerificationRules,
		arg.Overrides,
		arg.Reissue,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CommonName,
		&i.Sans,
		&i.VerificationRules,
		&i.Overrides,
		&i.Status,
		&i.CurrentVersionID,
		&i.NextRenewAt,
		&i.FailureCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrgIssuanceDefaults = `-- name: UpsertOrgIssuanceDefaults :exec
INSERT INTO issuance_defaults (org_id, config) VALUES ($1, $2)
ON CONFLICT (org_id) DO UPDATE SET config = EXCLUDED.config, updated_at = now()
`

type UpsertOrgIssuanceDefaultsParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	Config []byte    `json:"config"`
}

func (q *Queries) UpsertOrgIssuanceDefaults(ctx context.Context, arg UpsertOrgIssuanceDefaultsParams) error {
	_, err := q.db.Exec(ctx, upsertOrgIssuanceDefaults, arg.OrgID, arg.Config)
	return err
}
