// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: clients.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activateClient = `-- name: ActivateClient :one
UPDATE clients SET status = 'active', agent_cert_serial = $1,
       agent_cert_not_after = $2, agent_ca_id = $3,
       hostname = $4, os = $5, arch = $6,
       agent_version = $7, last_seen = now()
WHERE id = $8 RETURNING id, org_id, site_id, name, status, agent_cert_serial, agent_cert_not_after, agent_ca_id, hostname, os, arch, agent_version, capabilities, last_seen, desired_revision, applied_revision, created_at
`

type ActivateClientParams struct {
	AgentCertSerial   string     `json:"agent_cert_serial"`
	AgentCertNotAfter *time.Time `json:"agent_cert_not_after"`
	AgentCaID         *uuid.UUID `json:"agent_ca_id"`
	Hostname          string     `json:"hostname"`
	Os                string     `json:"os"`
	Arch              string     `json:"arch"`
	AgentVersion      string     `json:"agent_version"`
	ID                uuid.UUID  `json:"id"`
}

func (q *Queries) ActivateClient(ctx context.Context, arg ActivateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, activateClient,
		arg.AgentCertSerial,
		arg.AgentCertNotAfter,
		arg.AgentCaID,
		arg.Hostname,
		arg.Os,
		arg.Arch,
		arg.AgentVersion,
		arg.ID,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Name,
		&i.Status,
		&i.AgentCertSerial,
		&i.AgentCertNotAfter,
		&i.AgentCaID,
		&i.Hostname,
		&i.Os,
		&i.Arch,
		&i.AgentVersion,
		&i.Capabilities,
		&i.LastSeen,
		&i.DesiredRevision,
		&i.AppliedRevision,
		&i.CreatedAt,
	)
	return i, err
}

const clientCounts = `-- name: ClientCounts :many
SELECT g.client_id,
       count(*)::bigint AS grants,
       count(*) FILTER (WHERE d.state = 'drift')::bigint AS drift,
       count(*) FILTER (WHERE d.state = 'failed')::bigint AS failed
FROM client_cert_grants g
LEFT JOIN deployments d ON d.grant_id = g.id
WHERE g.client_id = ANY($1::uuid[]) AND g.removed_at IS NULL
GROUP BY g.client_id
`

type ClientCountsRow struct {
	ClientID *uuid.UUID `json:"client_id"`
	Grants   int64      `json:"grants"`
	Drift    int64      `json:"drift"`
	Failed   int64      `json:"failed"`
}

func (q *Queries) ClientCounts(ctx context.Context, ids []uuid.UUID) ([]ClientCountsRow, error) {
	rows, err := q.db.Query(ctx, clientCounts, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClientCountsRow{}
	for rows.Next() {
		var i ClientCountsRow
		if err := rows.Scan(
			&i.ClientID,
			&i.Grants,
			&i.Drift,
			&i.Failed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const consumeEnrollmentToken = `-- name: ConsumeEnrollmentToken :one
UPDATE enrollment_tokens SET used_at = now()
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING client_id
`

func (q *Queries) ConsumeEnrollmentToken(ctx context.Context, tokenHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeEnrollmentToken, tokenHash)
	var client_id uuid.UUID
	err := row.Scan(&client_id)
	return client_id, err
}

const createClient = `-- name: CreateClient :one
INSERT INTO clients (org_id, site_id, name) VALUES ($1, $2, $3) RETURNING id, org_id, site_id, name, status, agent_cert_serial, agent_cert_not_after, agent_ca_id, hostname, os, arch, agent_version, capabilities, last_seen, desired_revision, applied_revision, created_at
`

type CreateClientParams struct {
	OrgID  uuid.UUID  `json:"org_id"`
	SiteID *uuid.UUID `json:"site_id"`
	Name   string     `json:"name"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient, arg.OrgID, arg.SiteID, arg.Name)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Name,
		&i.Status,
		&i.AgentCertSerial,
		&i.AgentCertNotAfter,
		&i.AgentCaID,
		&i.Hostname,
		&i.Os,
		&i.Arch,
		&i.AgentVersion,
		&i.Capabilities,
		&i.LastSeen,
		&i.DesiredRevision,
		&i.AppliedRevision,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :execrows
DELETE FROM clients WHERE id = $1 AND org_id = $2 AND status IN ('pending', 'revoked')
`

type DeleteClientParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteClient(ctx context.Context, arg DeleteClientParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClient, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUnusedEnrollmentTokens = `-- name: DeleteUnusedEnrollmentTokens :exec
DELETE FROM enrollment_tokens WHERE client_id = $1 AND used_at IS NULL
`

func (q *Queries) DeleteUnusedEnrollmentTokens(ctx context.Context, clientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUnusedEnrollmentTokens, clientID)
	return err
}

const getClient = `-- name: GetClient :one
SELECT id, org_id, site_id, name, status, agent_cert_serial, agent_cert_not_after, agent_ca_id, hostname, os, arch, agent_version, capabilities, last_seen, desired_revision, applied_revision, created_at FROM clients WHERE id = $1 AND org_id = $2
`

type GetClientParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetClient(ctx context.Context, arg GetClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, getClient, arg.ID, arg.OrgID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Name,
		&i.Status,
		&i.AgentCertSerial,
		&i.AgentCertNotAfter,
		&i.AgentCaID,
		&i.Hostname,
		&i.Os,
		&i.Arch,
		&i.AgentVersion,
		&i.Capabilities,
		&i.LastSeen,
		&i.DesiredRevision,
		&i.AppliedRevision,
		&i.CreatedAt,
	)
	return i, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, org_id, site_id, name, status, agent_cert_serial, agent_cert_not_after, agent_ca_id, hostname, os, arch, agent_version, capabilities, last_seen, desired_revision, applied_revision, created_at FROM clients WHERE id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Name,
		&i.Status,
		&i.AgentCertSerial,
		&i.AgentCertNotAfter,
		&i.AgentCaID,
		&i.Hostname,
		&i.Os,
		&i.Arch,
		&i.AgentVersion,
		&i.Capabilities,
		&i.LastSeen,
		&i.DesiredRevision,
		&i.AppliedRevision,
		&i.CreatedAt,
	)
	return i, err
}

const insertEnrollmentToken = `-- name: InsertEnrollmentToken :exec
INSERT INTO enrollment_tokens (client_id, token_hash, expires_at, created_by) VALUES ($1, $2, $3, $4)
`

type InsertEnrollmentTokenParams struct {
	ClientID  uuid.UUID `json:"client_id"`
	TokenHash []byte    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedBy string    `json:"created_by"`
}

func (q *Queries) InsertEnrollmentToken(ctx context.Context, arg InsertEnrollmentTokenParams) error {
	_, err := q.db.Exec(ctx, insertEnrollmentToken,
		arg.ClientID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	return err
}

const listClients = `-- name: ListClients :many
SELECT k.id, k.org_id, k.site_id, k.name, k.status, k.agent_cert_serial, k.agent_cert_not_after, k.agent_ca_id,
       k.hostname, k.os, k.arch, k.agent_version, k.capabilities, k.last_seen, k.desired_revision,
       k.applied_revision, k.created_at, k.sort_key
FROM (
  SELECT c.id, c.org_id, c.site_id, c.name, c.status, c.agent_cert_serial, c.agent_cert_not_after, c.agent_ca_id, c.hostname, c.os, c.arch, c.agent_version, c.capabilities, c.last_seen, c.desired_revision, c.applied_revision, c.created_at, (CASE $1::text
      WHEN 'status' THEN c.status
      WHEN 'lastSeen' THEN COALESCE(to_char(c.last_seen AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US'), '')
      ELSE lower(c.name) END)::text AS sort_key
  FROM clients c
  WHERE c.org_id = ANY($2::uuid[])
    AND ($3::uuid IS NULL OR c.site_id = $3::uuid)
    AND ($4::text = '' OR c.status = $4::text)
    AND ($5::text = '' OR position($5::text IN lower(c.name || ' ' || c.hostname)) > 0)
) k
WHERE NOT $6::bool
   OR ($7::bool AND (k.sort_key, k.id) < ($8::text, $9::uuid))
   OR (NOT $7::bool AND (k.sort_key, k.id) > ($8::text, $9::uuid))
ORDER BY
  CASE WHEN $7::bool THEN k.sort_key END DESC,
  CASE WHEN $7::bool THEN k.id END DESC,
  CASE WHEN NOT $7::bool THEN k.sort_key END,
  CASE WHEN NOT $7::bool THEN k.id END
LIMIT $10::int
`

type ListClientsParams struct {
	Sort       string      `json:"sort"`
	OrgIds     []uuid.UUID `json:"org_ids"`
	SiteID     *uuid.UUID  `json:"site_id"`
	Status     string      `json:"status"`
	Q          string      `json:"q"`
	HasCursor  bool        `json:"has_cursor"`
	Descending bool        `json:"descending"`
	AfterKey   string      `json:"after_key"`
	AfterID    uuid.UUID   `json:"after_id"`
	PageLimit  int32       `json:"page_limit"`
}

type ListClientsRow struct {
	ID                uuid.UUID  `json:"id"`
	OrgID             uuid.UUID  `json:"org_id"`
	SiteID            *uuid.UUID `json:"site_id"`
	Name              string     `json:"name"`
	Status            string     `json:"status"`
	AgentCertSerial   string     `json:"agent_cert_serial"`
	AgentCertNotAfter *time.Time `json:"agent_cert_not_after"`
	AgentCaID         *uuid.UUID `json:"agent_ca_id"`
	Hostname          string     `json:"hostname"`
	Os                string     `json:"os"`
	Arch              string     `json:"arch"`
	AgentVersion      string     `json:"agent_version"`
	Capabilities      []string   `json:"capabilities"`
	LastSeen          *time.Time `json:"last_seen"`
	DesiredRevision   int64      `json:"desired_revision"`
	AppliedRevision   int64      `json:"applied_revision"`
	CreatedAt         time.Time  `json:"created_at"`
	SortKey           string     `json:"sort_key"`
}

func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]ListClientsRow, error) {
	rows, err := q.db.Query(ctx, listClients,
		arg.Sort,
		arg.OrgIds,
		arg.SiteID,
		arg.Status,
		arg.Q,
		arg.HasCursor,
		arg.Descending,
		arg.AfterKey,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientsRow{}
	for rows.Next() {
		var i ListClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SiteID,
			&i.Name,
			&i.Status,
			&i.AgentCertSerial,
			&i.AgentCertNotAfter,
			&i.AgentCaID,
			&i.Hostname,
			&i.Os,
			&i.Arch,
			&i.AgentVersion,
			&i.Capabilities,
			&i.LastSeen,
			&i.DesiredRevision,
			&i.AppliedRevision,
			&i.CreatedAt,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockClient = `-- name: LockClient :one
SELECT id, org_id, site_id, name, status, agent_cert_serial, agent_cert_not_after, agent_ca_id, hostname, os, arch, agent_version, capabilities, last_seen, desired_revision, applied_revision, created_at FROM clients WHERE id = $1 AND org_id = $2 FOR UPDATE
`

type LockClientParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) LockClient(ctx context.Context, arg LockClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, lockClient, arg.ID, arg.OrgID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Name,
		&i.Status,
		&i.AgentCertSerial,
		&i.AgentCertNotAfter,
		&i.AgentCaID,
		&i.Hostname,
		&i.Os,
		&i.Arch,
		&i.AgentVersion,
		&i.Capabilities,
		&i.LastSeen,
		&i.DesiredRevision,
		&i.AppliedRevision,
		&i.CreatedAt,
	)
	return i, err
}

const lockClientByID = `-- name: LockClientByID :one
SELECT id, org_id, site_id, name, status, agent_cert_serial, agent_cert_not_after, agent_ca_id, hostname, os, arch, agent_version, capabilities, last_seen, desired_revision, applied_revision, created_at FROM clients WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, lockClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Name,
		&i.Status,
		&i.AgentCertSerial,
		&i.AgentCertNotAfter,
		&i.AgentCaID,
		&i.Hostname,
		&i.Os,
		&i.Arch,
		&i.AgentVersion,
		&i.Capabilities,
		&i.LastSeen,
		&i.DesiredRevision,
		&i.AppliedRevision,
		&i.CreatedAt,
	)
	return i, err
}

const lockClientKeyShare = `-- name: LockClientKeyShare :one
SELECT id FROM clients WHERE id = $1 FOR KEY SHARE
`

// FOR KEY SHARE counterpart to LockClient; see LockDNSCredentialKeyShare.
// A certificate or org-defaults write referencing this client as a rule's
// clientId takes this lock first, so DeleteClient's FOR UPDATE lock on the
// same row blocks until that transaction ends.
func (q *Queries) LockClientKeyShare(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockClientKeyShare, id)
	err := row.Scan(&id)
	return id, err
}

const lockClientsByID = `-- name: LockClientsByID :many
SELECT id FROM clients WHERE id = ANY($1::uuid[]) ORDER BY id FOR UPDATE
`

// Locks the given clients FOR UPDATE in id order (a fixed order across
// every caller, regardless of the order ids arrive in), before any
// deployment row is written for one of their grants: render calls this
// first, so every path that renders a deployment locks clients before
// deployments, ruling out the client-then-deployment vs
// deployment-then-client deadlock between a grant write and a resync.
func (q *Queries) LockClientsByID(ctx context.Context, ids []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockClientsByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingTokens = `-- name: PendingTokens :many
SELECT client_id, expires_at FROM enrollment_tokens
WHERE client_id = ANY($1::uuid[]) AND used_at IS NULL AND expires_at > now()
`

type PendingTokensRow struct {
	ClientID  uuid.UUID `json:"client_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) PendingTokens(ctx context.Context, ids []uuid.UUID) ([]PendingTokensRow, error) {
	rows, err := q.db.Query(ctx, pendingTokens, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingTokensRow{}
	for rows.Next() {
		var i PendingTokensRow
		if err := rows.Scan(&i.ClientID, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewClientCert = `-- name: RenewClientCert :one
UPDATE clients SET agent_cert_serial = $1, agent_cert_not_after = $2,
       agent_ca_id = $3, last_seen = now()
WHERE id = $4 AND status = 'active' AND agent_cert_serial = $5
RETURNING id, org_id, site_id, name, status, agent_cert_serial, agent_cert_not_after, agent_ca_id, hostname, os, arch, agent_version, capabilities, last_seen, desired_revision, applied_revision, created_at
`

type RenewClientCertParams struct {
	AgentCertSerial   string     `json:"agent_cert_serial"`
	AgentCertNotAfter *time.Time `json:"agent_cert_not_after"`
	AgentCaID         *uuid.UUID `json:"agent_ca_id"`
	ID                uuid.UUID  `json:"id"`
	OldSerial         string     `json:"old_serial"`
}

func (q *Queries) RenewClientCert(ctx context.Context, arg RenewClientCertParams) (Client, error) {
	row := q.db.QueryRow(ctx, renewClientCert,
		arg.AgentCertSerial,
		arg.AgentCertNotAfter,
		arg.AgentCaID,
		arg.ID,
		arg.OldSerial,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Name,
		&i.Status,
		&i.AgentCertSerial,
		&i.AgentCertNotAfter,
		&i.AgentCaID,
		&i.Hostname,
		&i.Os,
		&i.Arch,
		&i.AgentVersion,
		&i.Capabilities,
		&i.LastSeen,
		&i.DesiredRevision,
		&i.AppliedRevision,
		&i.CreatedAt,
	)
	return i, err
}

const setClientPending = `-- name: SetClientPending :one
UPDATE clients SET status = 'pending', agent_cert_serial = '', agent_cert_not_after = NULL, agent_ca_id = NULL
WHERE id = $1 RETURNING id, org_id, site_id, name, status, agent_cert_serial, agent_cert_not_after, agent_ca_id, hostname, os, arch, agent_version, capabilities, last_seen, desired_revision, applied_revision, created_at
`

func (q *Queries) SetClientPending(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, setClientPending, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Name,
		&i.Status,
		&i.AgentCertSerial,
		&i.AgentCertNotAfter,
		&i.AgentCaID,
		&i.Hostname,
		&i.Os,
		&i.Arch,
		&i.AgentVersion,
		&i.Capabilities,
		&i.LastSeen,
		&i.DesiredRevision,
		&i.AppliedRevision,
		&i.CreatedAt,
	)
	return i, err
}

const setClientRevoked = `-- name: SetClientRevoked :one
UPDATE clients SET status = 'revoked' WHERE id = $1 RETURNING id, org_id, site_id, name, status, agent_cert_serial, agent_cert_not_after, agent_ca_id, hostname, os, arch, agent_version, capabilities, last_seen, desired_revision, applied_revision, created_at
`

func (q *Queries) SetClientRevoked(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, setClientRevoked, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Name,
		&i.Status,
		&i.AgentCertSerial,
		&i.AgentCertNotAfter,
		&i.AgentCaID,
		&i.Hostname,
		&i.Os,
		&i.Arch,
		&i.AgentVersion,
		&i.Capabilities,
		&i.LastSeen,
		&i.DesiredRevision,
		&i.AppliedRevision,
		&i.CreatedAt,
	)
	return i, err
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients SET name = $1, site_id = $2
WHERE id = $3 AND org_id = $4 RETURNING id, org_id, site_id, name, status, agent_cert_serial, agent_cert_not_after, agent_ca_id, hostname, os, arch, agent_version, capabilities, last_seen, desired_revision, applied_revision, created_at
`

type UpdateClientParams struct {
	Name   string     `json:"name"`
	SiteID *uuid.UUID `json:"site_id"`
	ID     uuid.UUID  `json:"id"`
	OrgID  uuid.UUID  `json:"org_id"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.Name,
		arg.SiteID,
		arg.ID,
		arg.OrgID,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Name,
		&i.Status,
		&i.AgentCertSerial,
		&i.AgentCertNotAfter,
		&i.AgentCaID,
		&i.Hostname,
		&i.Os,
		&i.Arch,
		&i.AgentVersion,
		&i.Capabilities,
		&i.LastSeen,
		&i.DesiredRevision,
		&i.AppliedRevision,
		&i.CreatedAt,
	)
	return i, err
}

const updateClientFacts = `-- name: UpdateClientFacts :one
UPDATE clients SET hostname = $2, os = $3, arch = $4, agent_version = $5, capabilities = $6, last_seen = now()
WHERE id = $1 RETURNING id, org_id, site_id, name, status, agent_cert_serial, agent_cert_not_after, agent_ca_id, hostname, os, arch, agent_version, capabilities, last_seen, desired_revision, applied_revision, created_at
`

type UpdateClientFactsParams struct {
	ID           uuid.UUID `json:"id"`
	Hostname     string    `json:"hostname"`
	Os           string    `json:"os"`
	Arch         string    `json:"arch"`
	AgentVersion string    `json:"agent_version"`
	Capabilities []string  `json:"capabilities"`
}

func (q *Queries) UpdateClientFacts(ctx context.Context, arg UpdateClientFactsParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClientFacts,
		arg.ID,
		arg.Hostname,
		arg.Os,
		arg.Arch,
		arg.AgentVersion,
		arg.Capabilities,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Name,
		&i.Status,
		&i.AgentCertSerial,
		&i.AgentCertNotAfter,
		&i.AgentCaID,
		&i.Hostname,
		&i.Os,
		&i.Arch,
		&i.AgentVersion,
		&i.Capabilities,
		&i.LastSeen,
		&i.DesiredRevision,
		&i.AppliedRevision,
		&i.CreatedAt,
	)
	return i, err
}
