// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: delivery.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createDeployTarget = `-- name: CreateDeployTarget :one
INSERT INTO deploy_targets (org_id, name, type, config) VALUES ($1, $2, $3, $4) RETURNING id, org_id, name, type, runs_on, config, created_at, updated_at
`

type CreateDeployTargetParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	Name   string    `json:"name"`
	Type   string    `json:"type"`
	Config []byte    `json:"config"`
}

func (q *Queries) CreateDeployTarget(ctx context.Context, arg CreateDeployTargetParams) (DeployTarget, error) {
	row := q.db.QueryRow(ctx, createDeployTarget,
		arg.OrgID,
		arg.Name,
		arg.Type,
		arg.Config,
	)
	var i DeployTarget
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.RunsOn,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createHook = `-- name: CreateHook :one
INSERT INTO hooks (org_id, name, phase, argv, timeout_seconds) VALUES ($1, $2, $3, $4, $5) RETURNING id, org_id, name, phase, argv, timeout_seconds, created_at, updated_at
`

type CreateHookParams struct {
	OrgID          uuid.UUID `json:"org_id"`
	Name           string    `json:"name"`
	Phase          string    `json:"phase"`
	Argv           []string  `json:"argv"`
	TimeoutSeconds int32     `json:"timeout_seconds"`
}

func (q *Queries) CreateHook(ctx context.Context, arg CreateHookParams) (Hook, error) {
	row := q.db.QueryRow(ctx, createHook,
		arg.OrgID,
		arg.Name,
		arg.Phase,
		arg.Argv,
		arg.TimeoutSeconds,
	)
	var i Hook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Phase,
		&i.Argv,
		&i.TimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLayout = `-- name: CreateLayout :one
INSERT INTO output_specs (org_id, name, files) VALUES ($1, $2, $3) RETURNING id, org_id, name, files, created_at, updated_at, password, extra_cert_ids
`

type CreateLayoutParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Name  string    `json:"name"`
	Files []byte    `json:"files"`
}

func (q *Queries) CreateLayout(ctx context.Context, arg CreateLayoutParams) (OutputSpec, error) {
	row := q.db.QueryRow(ctx, createLayout, arg.OrgID, arg.Name, arg.Files)
	var i OutputSpec
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Files,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.ExtraCertIds,
	)
	return i, err
}

const deleteDeployTarget = `-- name: DeleteDeployTarget :execrows
DELETE FROM deploy_targets WHERE id = $1 AND org_id = $2
`

type DeleteDeployTargetParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteDeployTarget(ctx context.Context, arg DeleteDeployTargetParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeployTarget, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteHook = `-- name: DeleteHook :execrows
DELETE FROM hooks WHERE id = $1 AND org_id = $2
`

type DeleteHookParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteHook(ctx context.Context, arg DeleteHookParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHook, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLayout = `-- name: DeleteLayout :execrows
DELETE FROM output_specs WHERE id = $1 AND org_id = $2
`

type DeleteLayoutParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteLayout(ctx context.Context, arg DeleteLayoutParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLayout, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deployTargetDependents = `-- name: DeployTargetDependents :many
SELECT c.name AS client_name, ce.name AS certificate_name, (g.removed_at IS NOT NULL)::bool AS removing
FROM client_cert_grants g
JOIN clients c ON c.id = g.client_id
JOIN certificates ce ON ce.id = g.cert_id
JOIN deploy_targets t ON t.id = g.deploy_target_id
WHERE g.deploy_target_id = $1 AND t.org_id = $2
ORDER BY c.name, ce.name LIMIT 6
`

type DeployTargetDependentsParams struct {
	ID    *uuid.UUID `json:"id"`
	OrgID uuid.UUID  `json:"org_id"`
}

type DeployTargetDependentsRow struct {
	ClientName      string `json:"client_name"`
	CertificateName string `json:"certificate_name"`
	Removing        bool   `json:"removing"`
}

func (q *Queries) DeployTargetDependents(ctx context.Context, arg DeployTargetDependentsParams) ([]DeployTargetDependentsRow, error) {
	rows, err := q.db.Query(ctx, deployTargetDependents, arg.ID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployTargetDependentsRow{}
	for rows.Next() {
		var i DeployTargetDependentsRow
		if err := rows.Scan(&i.ClientName, &i.CertificateName, &i.Removing); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deployTargetGrantCounts = `-- name: DeployTargetGrantCounts :many
SELECT t.id, count(g.id)::bigint AS grants
FROM deploy_targets t LEFT JOIN client_cert_grants g ON g.deploy_target_id = t.id AND g.removed_at IS NULL
WHERE t.id = ANY($1::uuid[]) GROUP BY t.id
`

type DeployTargetGrantCountsRow struct {
	ID     uuid.UUID `json:"id"`
	Grants int64     `json:"grants"`
}

func (q *Queries) DeployTargetGrantCounts(ctx context.Context, ids []uuid.UUID) ([]DeployTargetGrantCountsRow, error) {
	rows, err := q.db.Query(ctx, deployTargetGrantCounts, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployTargetGrantCountsRow{}
	for rows.Next() {
		var i DeployTargetGrantCountsRow
		if err := rows.Scan(&i.ID, &i.Grants); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeployTarget = `-- name: GetDeployTarget :one
SELECT id, org_id, name, type, runs_on, config, created_at, updated_at FROM deploy_targets WHERE id = $1 AND org_id = $2
`

type GetDeployTargetParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetDeployTarget(ctx context.Context, arg GetDeployTargetParams) (DeployTarget, error) {
	row := q.db.QueryRow(ctx, getDeployTarget, arg.ID, arg.OrgID)
	var i DeployTarget
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.RunsOn,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHook = `-- name: GetHook :one
SELECT id, org_id, name, phase, argv, timeout_seconds, created_at, updated_at FROM hooks WHERE id = $1 AND org_id = $2
`

type GetHookParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetHook(ctx context.Context, arg GetHookParams) (Hook, error) {
	row := q.db.QueryRow(ctx, getHook, arg.ID, arg.OrgID)
	var i Hook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Phase,
		&i.Argv,
		&i.TimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLayout = `-- name: GetLayout :one
SELECT id, org_id, name, files, created_at, updated_at, password, extra_cert_ids FROM output_specs WHERE id = $1 AND org_id = $2
`

type GetLayoutParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetLayout(ctx context.Context, arg GetLayoutParams) (OutputSpec, error) {
	row := q.db.QueryRow(ctx, getLayout, arg.ID, arg.OrgID)
	var i OutputSpec
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Files,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.ExtraCertIds,
	)
	return i, err
}

const hookDependents = `-- name: HookDependents :many
SELECT c.name AS client_name, ce.name AS certificate_name, (g.removed_at IS NOT NULL)::bool AS removing
FROM client_cert_grants g JOIN clients c ON c.id = g.client_id JOIN certificates ce ON ce.id = g.cert_id
WHERE $1::uuid = ANY(g.hook_ids)
  AND EXISTS (SELECT 1 FROM hooks h WHERE h.id = $1::uuid AND h.org_id = $2)
ORDER BY c.name, ce.name LIMIT 6
`

type HookDependentsParams struct {
	HookID uuid.UUID `json:"hook_id"`
	OrgID  uuid.UUID `json:"org_id"`
}

type HookDependentsRow struct {
	ClientName      string `json:"client_name"`
	CertificateName string `json:"certificate_name"`
	Removing        bool   `json:"removing"`
}

func (q *Queries) HookDependents(ctx context.Context, arg HookDependentsParams) ([]HookDependentsRow, error) {
	rows, err := q.db.Query(ctx, hookDependents, arg.HookID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HookDependentsRow{}
	for rows.Next() {
		var i HookDependentsRow
		if err := rows.Scan(&i.ClientName, &i.CertificateName, &i.Removing); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hookGrantCounts = `-- name: HookGrantCounts :many
SELECT h.id, count(g.id)::bigint AS grants
FROM hooks h LEFT JOIN client_cert_grants g ON h.id = ANY(g.hook_ids) AND g.removed_at IS NULL
WHERE h.id = ANY($1::uuid[]) GROUP BY h.id
`

type HookGrantCountsRow struct {
	ID     uuid.UUID `json:"id"`
	Grants int64     `json:"grants"`
}

func (q *Queries) HookGrantCounts(ctx context.Context, ids []uuid.UUID) ([]HookGrantCountsRow, error) {
	rows, err := q.db.Query(ctx, hookGrantCounts, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HookGrantCountsRow{}
	for rows.Next() {
		var i HookGrantCountsRow
		if err := rows.Scan(&i.ID, &i.Grants); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const layoutDependents = `-- name: LayoutDependents :many
SELECT c.name AS client_name, ce.name AS certificate_name, (g.removed_at IS NOT NULL)::bool AS removing
FROM client_cert_grants g
JOIN clients c ON c.id = g.client_id
JOIN certificates ce ON ce.id = g.cert_id
JOIN output_specs o ON o.id = g.output_spec_id
WHERE g.output_spec_id = $1 AND o.org_id = $2
ORDER BY c.name, ce.name LIMIT 6
`

type LayoutDependentsParams struct {
	ID    *uuid.UUID `json:"id"`
	OrgID uuid.UUID  `json:"org_id"`
}

type LayoutDependentsRow struct {
	ClientName      string `json:"client_name"`
	CertificateName string `json:"certificate_name"`
	Removing        bool   `json:"removing"`
}

func (q *Queries) LayoutDependents(ctx context.Context, arg LayoutDependentsParams) ([]LayoutDependentsRow, error) {
	rows, err := q.db.Query(ctx, layoutDependents, arg.ID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LayoutDependentsRow{}
	for rows.Next() {
		var i LayoutDependentsRow
		if err := rows.Scan(&i.ClientName, &i.CertificateName, &i.Removing); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const layoutGrantCounts = `-- name: LayoutGrantCounts :many
SELECT o.id, count(g.id)::bigint AS grants
FROM output_specs o LEFT JOIN client_cert_grants g ON g.output_spec_id = o.id AND g.removed_at IS NULL
WHERE o.id = ANY($1::uuid[]) GROUP BY o.id
`

type LayoutGrantCountsRow struct {
	ID     uuid.UUID `json:"id"`
	Grants int64     `json:"grants"`
}

func (q *Queries) LayoutGrantCounts(ctx context.Context, ids []uuid.UUID) ([]LayoutGrantCountsRow, error) {
	rows, err := q.db.Query(ctx, layoutGrantCounts, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LayoutGrantCountsRow{}
	for rows.Next() {
		var i LayoutGrantCountsRow
		if err := rows.Scan(&i.ID, &i.Grants); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployTargets = `-- name: ListDeployTargets :many
SELECT id, org_id, name, type, runs_on, config, created_at, updated_at FROM deploy_targets WHERE org_id = $1 ORDER BY lower(name), id
`

func (q *Queries) ListDeployTargets(ctx context.Context, orgID uuid.UUID) ([]DeployTarget, error) {
	rows, err := q.db.Query(ctx, listDeployTargets, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployTarget{}
	for rows.Next() {
		var i DeployTarget
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Type,
			&i.RunsOn,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHooks = `-- name: ListHooks :many
SELECT id, org_id, name, phase, argv, timeout_seconds, created_at, updated_at FROM hooks WHERE org_id = $1 ORDER BY lower(name), id
`

func (q *Queries) ListHooks(ctx context.Context, orgID uuid.UUID) ([]Hook, error) {
	rows, err := q.db.Query(ctx, listHooks, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hook{}
	for rows.Next() {
		var i Hook
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Phase,
			&i.Argv,
			&i.TimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLayouts = `-- name: ListLayouts :many
SELECT id, org_id, name, files, created_at, updated_at, password, extra_cert_ids FROM output_specs WHERE org_id = $1 ORDER BY lower(name), id
`

func (q *Queries) ListLayouts(ctx context.Context, orgID uuid.UUID) ([]OutputSpec, error) {
	rows, err := q.db.Query(ctx, listLayouts, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutputSpec{}
	for rows.Next() {
		var i OutputSpec
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Files,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Password,
			&i.ExtraCertIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockHook = `-- name: LockHook :one
SELECT id, org_id, name, phase, argv, timeout_seconds, created_at, updated_at FROM hooks WHERE id = $1 AND org_id = $2 FOR UPDATE
`

type LockHookParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Locks the hook row FOR UPDATE before DeleteHook re-checks HookDependents,
// so a concurrent grant create/update that locks this row FOR SHARE
// (LockHooksInOrg) either finishes and is seen by the dependents re-check,
// or blocks behind this delete and later finds the hook gone.
func (q *Queries) LockHook(ctx context.Context, arg LockHookParams) (Hook, error) {
	row := q.db.QueryRow(ctx, lockHook, arg.ID, arg.OrgID)
	var i Hook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Phase,
		&i.Argv,
		&i.TimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeployTarget = `-- name: UpdateDeployTarget :one
UPDATE deploy_targets SET name = $1, config = $2, updated_at = now()
WHERE id = $3 AND org_id = $4 RETURNING id, org_id, name, type, runs_on, config, created_at, updated_at
`

type UpdateDeployTargetParams struct {
	Name   string    `json:"name"`
	Config []byte    `json:"config"`
	ID     uuid.UUID `json:"id"`
	OrgID  uuid.UUID `json:"org_id"`
}

func (q *Queries) UpdateDeployTarget(ctx context.Context, arg UpdateDeployTargetParams) (DeployTarget, error) {
	row := q.db.QueryRow(ctx, updateDeployTarget,
		arg.Name,
		arg.Config,
		arg.ID,
		arg.OrgID,
	)
	var i DeployTarget
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.RunsOn,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHook = `-- name: UpdateHook :one
UPDATE hooks SET name = $1, phase = $2, argv = $3,
       timeout_seconds = $4, updated_at = now()
WHERE id = $5 AND org_id = $6 RETURNING id, org_id, name, phase, argv, timeout_seconds, created_at, updated_at
`

type UpdateHookParams struct {
	Name           string    `json:"name"`
	Phase          string    `json:"phase"`
	Argv           []string  `json:"argv"`
	TimeoutSeconds int32     `json:"timeout_seconds"`
	ID             uuid.UUID `json:"id"`
	OrgID          uuid.UUID `json:"org_id"`
}

func (q *Queries) UpdateHook(ctx context.Context, arg UpdateHookParams) (Hook, error) {
	row := q.db.QueryRow(ctx, updateHook,
		arg.Name,
		arg.Phase,
		arg.Argv,
		arg.TimeoutSeconds,
		arg.ID,
		arg.OrgID,
	)
	var i Hook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Phase,
		&i.Argv,
		&i.TimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLayout = `-- name: UpdateLayout :one
UPDATE output_specs SET name = $1, files = $2, updated_at = now()
WHERE id = $3 AND org_id = $4 RETURNING id, org_id, name, files, created_at, updated_at, password, extra_cert_ids
`

type UpdateLayoutParams struct {
	Name  string    `json:"name"`
	Files []byte    `json:"files"`
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) UpdateLayout(ctx context.Context, arg UpdateLayoutParams) (OutputSpec, error) {
	row := q.db.QueryRow(ctx, updateLayout,
		arg.Name,
		arg.Files,
		arg.ID,
		arg.OrgID,
	)
	var i OutputSpec
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Files,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.ExtraCertIds,
	)
	return i, err
}
