// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: delivery.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createDeployTarget = `-- name: CreateDeployTarget :one
INSERT INTO deploy_targets (org_id, name, type, runs_on, config, secret_cfg, stored_secret_keys)
VALUES ($1, $2, $3, $4, $5, $6, COALESCE($7::text[], '{}')) RETURNING id, org_id, name, type, runs_on, config, created_at, updated_at, secret_cfg, stored_secret_keys
`

type CreateDeployTargetParams struct {
	OrgID            uuid.UUID `json:"org_id"`
	Name             string    `json:"name"`
	Type             string    `json:"type"`
	RunsOn           string    `json:"runs_on"`
	Config           []byte    `json:"config"`
	SecretCfg        []byte    `json:"secret_cfg"`
	StoredSecretKeys []string  `json:"stored_secret_keys"`
}

func (q *Queries) CreateDeployTarget(ctx context.Context, arg CreateDeployTargetParams) (DeployTarget, error) {
	row := q.db.QueryRow(ctx, createDeployTarget,
		arg.OrgID,
		arg.Name,
		arg.Type,
		arg.RunsOn,
		arg.Config,
		arg.SecretCfg,
		arg.StoredSecretKeys,
	)
	var i DeployTarget
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.RunsOn,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecretCfg,
		&i.StoredSecretKeys,
	)
	return i, err
}

const createHook = `-- name: CreateHook :one
INSERT INTO hooks (org_id, name, phase, argv, timeout_seconds) VALUES ($1, $2, $3, $4, $5) RETURNING id, org_id, name, phase, argv, timeout_seconds, created_at, updated_at
`

type CreateHookParams struct {
	OrgID          uuid.UUID `json:"org_id"`
	Name           string    `json:"name"`
	Phase          string    `json:"phase"`
	Argv           []string  `json:"argv"`
	TimeoutSeconds int32     `json:"timeout_seconds"`
}

func (q *Queries) CreateHook(ctx context.Context, arg CreateHookParams) (Hook, error) {
	row := q.db.QueryRow(ctx, createHook,
		arg.OrgID,
		arg.Name,
		arg.Phase,
		arg.Argv,
		arg.TimeoutSeconds,
	)
	var i Hook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Phase,
		&i.Argv,
		&i.TimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLayout = `-- name: CreateLayout :one
INSERT INTO output_specs (org_id, name, files, password, extra_cert_ids) VALUES ($1, $2, $3, $4, $5) RETURNING id, org_id, name, files, created_at, updated_at, password, extra_cert_ids
`

type CreateLayoutParams struct {
	OrgID        uuid.UUID   `json:"org_id"`
	Name         string      `json:"name"`
	Files        []byte      `json:"files"`
	Password     []byte      `json:"password"`
	ExtraCertIds []uuid.UUID `json:"extra_cert_ids"`
}

func (q *Queries) CreateLayout(ctx context.Context, arg CreateLayoutParams) (OutputSpec, error) {
	row := q.db.QueryRow(ctx, createLayout,
		arg.OrgID,
		arg.Name,
		arg.Files,
		arg.Password,
		arg.ExtraCertIds,
	)
	var i OutputSpec
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Files,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.ExtraCertIds,
	)
	return i, err
}

const deleteDeployTarget = `-- name: DeleteDeployTarget :execrows
DELETE FROM deploy_targets WHERE id = $1 AND org_id = $2
`

type DeleteDeployTargetParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteDeployTarget(ctx context.Context, arg DeleteDeployTargetParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeployTarget, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteHook = `-- name: DeleteHook :execrows
DELETE FROM hooks WHERE id = $1 AND org_id = $2
`

type DeleteHookParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteHook(ctx context.Context, arg DeleteHookParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHook, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLayout = `-- name: DeleteLayout :execrows
DELETE FROM output_specs WHERE id = $1 AND org_id = $2
`

type DeleteLayoutParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteLayout(ctx context.Context, arg DeleteLayoutParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLayout, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deployTargetDependents = `-- name: DeployTargetDependents :many
SELECT COALESCE(c.name, t.name) AS client_name, ce.name AS certificate_name, (g.removed_at IS NOT NULL)::bool AS removing
FROM client_cert_grants g
LEFT JOIN clients c ON c.id = g.client_id
JOIN certificates ce ON ce.id = g.cert_id
JOIN deploy_targets t ON t.id = g.deploy_target_id
WHERE g.deploy_target_id = $1 AND t.org_id = $2
ORDER BY COALESCE(c.name, t.name), ce.name LIMIT 6
`

type DeployTargetDependentsParams struct {
	ID    *uuid.UUID `json:"id"`
	OrgID uuid.UUID  `json:"org_id"`
}

type DeployTargetDependentsRow struct {
	ClientName      string `json:"client_name"`
	CertificateName string `json:"certificate_name"`
	Removing        bool   `json:"removing"`
}

// Final review finding 2: client_id is LEFT JOINed (a server grant has
// none) so a target used only by server grants still lists its dependents;
// client_name names the target itself for a server grant (there is no
// client to name — the target is the very thing being deleted).
func (q *Queries) DeployTargetDependents(ctx context.Context, arg DeployTargetDependentsParams) ([]DeployTargetDependentsRow, error) {
	rows, err := q.db.Query(ctx, deployTargetDependents, arg.ID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployTargetDependentsRow{}
	for rows.Next() {
		var i DeployTargetDependentsRow
		if err := rows.Scan(&i.ClientName, &i.CertificateName, &i.Removing); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deployTargetForUpdate = `-- name: DeployTargetForUpdate :one
SELECT id, org_id, name, type, runs_on, config, created_at, updated_at, secret_cfg, stored_secret_keys FROM deploy_targets WHERE id = $1 AND org_id = $2 FOR UPDATE
`

type DeployTargetForUpdateParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Phase 7A Task 1: read+lock a target row FOR UPDATE ahead of an update
// that decides whether to keep stored secrets unchanged (the same
// LockLayout convention: internal/kek/rewrap.go's concurrent CAS on
// secret_cfg cannot land between this read and the later write and be
// silently clobbered by a stale, pre-rewrap blob).
func (q *Queries) DeployTargetForUpdate(ctx context.Context, arg DeployTargetForUpdateParams) (DeployTarget, error) {
	row := q.db.QueryRow(ctx, deployTargetForUpdate, arg.ID, arg.OrgID)
	var i DeployTarget
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.RunsOn,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecretCfg,
		&i.StoredSecretKeys,
	)
	return i, err
}

const deployTargetGrantCounts = `-- name: DeployTargetGrantCounts :many
SELECT t.id, count(g.id)::bigint AS grants
FROM deploy_targets t LEFT JOIN client_cert_grants g ON g.deploy_target_id = t.id AND g.removed_at IS NULL
WHERE t.id = ANY($1::uuid[]) GROUP BY t.id
`

type DeployTargetGrantCountsRow struct {
	ID     uuid.UUID `json:"id"`
	Grants int64     `json:"grants"`
}

func (q *Queries) DeployTargetGrantCounts(ctx context.Context, ids []uuid.UUID) ([]DeployTargetGrantCountsRow, error) {
	rows, err := q.db.Query(ctx, deployTargetGrantCounts, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployTargetGrantCountsRow{}
	for rows.Next() {
		var i DeployTargetGrantCountsRow
		if err := rows.Scan(&i.ID, &i.Grants); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeployTarget = `-- name: GetDeployTarget :one
SELECT id, org_id, name, type, runs_on, config, created_at, updated_at, secret_cfg, stored_secret_keys FROM deploy_targets WHERE id = $1 AND org_id = $2
`

type GetDeployTargetParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetDeployTarget(ctx context.Context, arg GetDeployTargetParams) (DeployTarget, error) {
	row := q.db.QueryRow(ctx, getDeployTarget, arg.ID, arg.OrgID)
	var i DeployTarget
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.RunsOn,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecretCfg,
		&i.StoredSecretKeys,
	)
	return i, err
}

const getHook = `-- name: GetHook :one
SELECT id, org_id, name, phase, argv, timeout_seconds, created_at, updated_at FROM hooks WHERE id = $1 AND org_id = $2
`

type GetHookParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetHook(ctx context.Context, arg GetHookParams) (Hook, error) {
	row := q.db.QueryRow(ctx, getHook, arg.ID, arg.OrgID)
	var i Hook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Phase,
		&i.Argv,
		&i.TimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLayout = `-- name: GetLayout :one
SELECT id, org_id, name, files, created_at, updated_at, password, extra_cert_ids FROM output_specs WHERE id = $1 AND org_id = $2
`

type GetLayoutParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetLayout(ctx context.Context, arg GetLayoutParams) (OutputSpec, error) {
	row := q.db.QueryRow(ctx, getLayout, arg.ID, arg.OrgID)
	var i OutputSpec
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Files,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.ExtraCertIds,
	)
	return i, err
}

const hookDependents = `-- name: HookDependents :many
SELECT c.name AS client_name, ce.name AS certificate_name, (g.removed_at IS NOT NULL)::bool AS removing
FROM client_cert_grants g JOIN clients c ON c.id = g.client_id JOIN certificates ce ON ce.id = g.cert_id
WHERE $1::uuid = ANY(g.hook_ids)
  AND EXISTS (SELECT 1 FROM hooks h WHERE h.id = $1::uuid AND h.org_id = $2)
ORDER BY c.name, ce.name LIMIT 6
`

type HookDependentsParams struct {
	HookID uuid.UUID `json:"hook_id"`
	OrgID  uuid.UUID `json:"org_id"`
}

type HookDependentsRow struct {
	ClientName      string `json:"client_name"`
	CertificateName string `json:"certificate_name"`
	Removing        bool   `json:"removing"`
}

func (q *Queries) HookDependents(ctx context.Context, arg HookDependentsParams) ([]HookDependentsRow, error) {
	rows, err := q.db.Query(ctx, hookDependents, arg.HookID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HookDependentsRow{}
	for rows.Next() {
		var i HookDependentsRow
		if err := rows.Scan(&i.ClientName, &i.CertificateName, &i.Removing); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hookGrantCounts = `-- name: HookGrantCounts :many
SELECT h.id, count(g.id)::bigint AS grants
FROM hooks h LEFT JOIN client_cert_grants g ON h.id = ANY(g.hook_ids) AND g.removed_at IS NULL
WHERE h.id = ANY($1::uuid[]) GROUP BY h.id
`

type HookGrantCountsRow struct {
	ID     uuid.UUID `json:"id"`
	Grants int64     `json:"grants"`
}

func (q *Queries) HookGrantCounts(ctx context.Context, ids []uuid.UUID) ([]HookGrantCountsRow, error) {
	rows, err := q.db.Query(ctx, hookGrantCounts, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HookGrantCountsRow{}
	for rows.Next() {
		var i HookGrantCountsRow
		if err := rows.Scan(&i.ID, &i.Grants); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const layoutDependents = `-- name: LayoutDependents :many
SELECT COALESCE(c.name, t.name) AS client_name, ce.name AS certificate_name, (g.removed_at IS NOT NULL)::bool AS removing
FROM client_cert_grants g
LEFT JOIN clients c ON c.id = g.client_id
LEFT JOIN deploy_targets t ON t.id = g.deploy_target_id
JOIN certificates ce ON ce.id = g.cert_id
JOIN output_specs o ON o.id = g.output_spec_id
WHERE g.output_spec_id = $1 AND o.org_id = $2
ORDER BY COALESCE(c.name, t.name), ce.name LIMIT 6
`

type LayoutDependentsParams struct {
	ID    *uuid.UUID `json:"id"`
	OrgID uuid.UUID  `json:"org_id"`
}

type LayoutDependentsRow struct {
	ClientName      string `json:"client_name"`
	CertificateName string `json:"certificate_name"`
	Removing        bool   `json:"removing"`
}

// Final review finding 2: client_id is LEFT JOINed (a server grant has
// none) so a layout used only by server grants still lists its dependents
// instead of silently reporting none; client_name names the deploy target
// for a server grant (there is no client to name).
func (q *Queries) LayoutDependents(ctx context.Context, arg LayoutDependentsParams) ([]LayoutDependentsRow, error) {
	rows, err := q.db.Query(ctx, layoutDependents, arg.ID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LayoutDependentsRow{}
	for rows.Next() {
		var i LayoutDependentsRow
		if err := rows.Scan(&i.ClientName, &i.CertificateName, &i.Removing); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const layoutGrantCounts = `-- name: LayoutGrantCounts :many
SELECT o.id, count(g.id)::bigint AS grants
FROM output_specs o LEFT JOIN client_cert_grants g ON g.output_spec_id = o.id AND g.removed_at IS NULL
WHERE o.id = ANY($1::uuid[]) GROUP BY o.id
`

type LayoutGrantCountsRow struct {
	ID     uuid.UUID `json:"id"`
	Grants int64     `json:"grants"`
}

func (q *Queries) LayoutGrantCounts(ctx context.Context, ids []uuid.UUID) ([]LayoutGrantCountsRow, error) {
	rows, err := q.db.Query(ctx, layoutGrantCounts, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LayoutGrantCountsRow{}
	for rows.Next() {
		var i LayoutGrantCountsRow
		if err := rows.Scan(&i.ID, &i.Grants); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const layoutKeylessGrantCertificate = `-- name: LayoutKeylessGrantCertificate :one
SELECT ce.name FROM client_cert_grants g
JOIN certificates ce ON ce.id = g.cert_id
JOIN certificate_versions v ON v.id = ce.current_version_id
WHERE g.output_spec_id = $1 AND g.removed_at IS NULL AND v.private_key IS NULL
ORDER BY ce.name LIMIT 1
`

// The name of one certificate (the first, by name) with a live grant on
// this layout whose current version has no stored key. Used by
// UpdateLayout (R10 mirror, 4A final review finding 1): an update that
// makes the layout need a key (delivery.NeedsKey on the new files) must be
// refused with 422 when any of its live grants' certificates would then
// have nothing to render a key from, rather than storing the update and
// only discovering ErrNoKey later, opaquely, from the Resync render.
// pgx.ErrNoRows means none found (nothing to refuse).
func (q *Queries) LayoutKeylessGrantCertificate(ctx context.Context, id *uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, layoutKeylessGrantCertificate, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const layoutsListingExtraCert = `-- name: LayoutsListingExtraCert :many
SELECT name FROM output_specs
WHERE org_id = $1 AND $2::uuid = ANY(extra_cert_ids)
ORDER BY lower(name) LIMIT 6
`

type LayoutsListingExtraCertParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	CertID uuid.UUID `json:"cert_id"`
}

// Layouts (any org, but callers scope by org_id) that bundle cert_id as an
// extra certificate; DeleteCertificate 409s naming these instead of
// deleting a certificate a layout still renders.
func (q *Queries) LayoutsListingExtraCert(ctx context.Context, arg LayoutsListingExtraCertParams) ([]string, error) {
	rows, err := q.db.Query(ctx, layoutsListingExtraCert, arg.OrgID, arg.CertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployTargets = `-- name: ListDeployTargets :many
SELECT id, org_id, name, type, runs_on, config, created_at, updated_at, secret_cfg, stored_secret_keys FROM deploy_targets WHERE org_id = $1 ORDER BY lower(name), id
`

func (q *Queries) ListDeployTargets(ctx context.Context, orgID uuid.UUID) ([]DeployTarget, error) {
	rows, err := q.db.Query(ctx, listDeployTargets, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployTarget{}
	for rows.Next() {
		var i DeployTarget
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Type,
			&i.RunsOn,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SecretCfg,
			&i.StoredSecretKeys,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHooks = `-- name: ListHooks :many
SELECT id, org_id, name, phase, argv, timeout_seconds, created_at, updated_at FROM hooks WHERE org_id = $1 ORDER BY lower(name), id
`

func (q *Queries) ListHooks(ctx context.Context, orgID uuid.UUID) ([]Hook, error) {
	rows, err := q.db.Query(ctx, listHooks, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hook{}
	for rows.Next() {
		var i Hook
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Phase,
			&i.Argv,
			&i.TimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLayouts = `-- name: ListLayouts :many
SELECT id, org_id, name, files, created_at, updated_at, password, extra_cert_ids FROM output_specs WHERE org_id = $1 ORDER BY lower(name), id
`

func (q *Queries) ListLayouts(ctx context.Context, orgID uuid.UUID) ([]OutputSpec, error) {
	rows, err := q.db.Query(ctx, listLayouts, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutputSpec{}
	for rows.Next() {
		var i OutputSpec
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Files,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Password,
			&i.ExtraCertIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCertsForExtra = `-- name: LockCertsForExtra :many
SELECT id, current_version_id FROM certificates
WHERE id = ANY($1::uuid[]) AND org_id = $2
FOR KEY SHARE
`

type LockCertsForExtraParams struct {
	Ids   []uuid.UUID `json:"ids"`
	OrgID uuid.UUID   `json:"org_id"`
}

type LockCertsForExtraRow struct {
	ID               uuid.UUID  `json:"id"`
	CurrentVersionID *uuid.UUID `json:"current_version_id"`
}

// Locks FOR KEY SHARE the candidate extra certificates a layout write
// references (scoped to the org), so a concurrent certificate delete
// (api.DeleteCertificate's FOR UPDATE lock) serializes against this layout
// write instead of racing it into a dangling extra_cert_ids entry. Returns
// current_version_id so the caller can also check each has one, in the
// same round trip.
func (q *Queries) LockCertsForExtra(ctx context.Context, arg LockCertsForExtraParams) ([]LockCertsForExtraRow, error) {
	rows, err := q.db.Query(ctx, lockCertsForExtra, arg.Ids, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockCertsForExtraRow{}
	for rows.Next() {
		var i LockCertsForExtraRow
		if err := rows.Scan(&i.ID, &i.CurrentVersionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockHook = `-- name: LockHook :one
SELECT id, org_id, name, phase, argv, timeout_seconds, created_at, updated_at FROM hooks WHERE id = $1 AND org_id = $2 FOR UPDATE
`

type LockHookParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Locks the hook row FOR UPDATE before DeleteHook re-checks HookDependents,
// so a concurrent grant create/update that locks this row FOR SHARE
// (LockHooksInOrg) either finishes and is seen by the dependents re-check,
// or blocks behind this delete and later finds the hook gone.
func (q *Queries) LockHook(ctx context.Context, arg LockHookParams) (Hook, error) {
	row := q.db.QueryRow(ctx, lockHook, arg.ID, arg.OrgID)
	var i Hook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Phase,
		&i.Argv,
		&i.TimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockLayout = `-- name: LockLayout :one
SELECT id, org_id, name, files, created_at, updated_at, password, extra_cert_ids FROM output_specs WHERE id = $1 AND org_id = $2 FOR UPDATE
`

type LockLayoutParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Final review finding 1: UpdateLayout reads the row FOR UPDATE (not plain
// GetLayout) before deciding whether to keep the stored password
// unchanged, so a concurrent rewrap's CAS on this same row's password
// column (internal/kek/rewrap.go) cannot commit between this read and
// UpdateLayout's own write — which would otherwise write the stale,
// pre-rewrap blob back over it, losing the rewrap
// (TestRewrapCASLosesRaceSafely). UpdateLayout already runs in its own
// transaction, so this is the same row, only a stronger lock.
func (q *Queries) LockLayout(ctx context.Context, arg LockLayoutParams) (OutputSpec, error) {
	row := q.db.QueryRow(ctx, lockLayout, arg.ID, arg.OrgID)
	var i OutputSpec
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Files,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.ExtraCertIds,
	)
	return i, err
}

const targetKeylessGrantCertificate = `-- name: TargetKeylessGrantCertificate :one
SELECT ce.name FROM client_cert_grants g
JOIN certificates ce ON ce.id = g.cert_id
JOIN certificate_versions v ON v.id = ce.current_version_id
WHERE g.deploy_target_id = $1 AND g.removed_at IS NULL AND g.client_id IS NULL AND v.private_key IS NULL
ORDER BY ce.name LIMIT 1
`

// UpdateDeployTarget's own version of LayoutKeylessGrantCertificate (final
// review finding 3): the name of one certificate (first, by name) with a
// live server grant on this target whose current version has no stored
// key. Used when an update turns includeKey on, so the update is refused
// (422) before storing a config that would make the next deploy fail with
// no key to render, instead of discovering it opaquely at deploy time.
// client_id IS NULL: a server grant only (see LiveGrantIDsForCert's own
// comment on this filter) — an agent-run target has no includeKey at all.
// pgx.ErrNoRows means none found (nothing to refuse).
func (q *Queries) TargetKeylessGrantCertificate(ctx context.Context, id *uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, targetKeylessGrantCertificate, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const updateDeployTarget = `-- name: UpdateDeployTarget :one
UPDATE deploy_targets SET name = $1, config = $2, secret_cfg = $3,
       stored_secret_keys = COALESCE($4::text[], '{}'), updated_at = now()
WHERE id = $5 AND org_id = $6 RETURNING id, org_id, name, type, runs_on, config, created_at, updated_at, secret_cfg, stored_secret_keys
`

type UpdateDeployTargetParams struct {
	Name             string    `json:"name"`
	Config           []byte    `json:"config"`
	SecretCfg        []byte    `json:"secret_cfg"`
	StoredSecretKeys []string  `json:"stored_secret_keys"`
	ID               uuid.UUID `json:"id"`
	OrgID            uuid.UUID `json:"org_id"`
}

func (q *Queries) UpdateDeployTarget(ctx context.Context, arg UpdateDeployTargetParams) (DeployTarget, error) {
	row := q.db.QueryRow(ctx, updateDeployTarget,
		arg.Name,
		arg.Config,
		arg.SecretCfg,
		arg.StoredSecretKeys,
		arg.ID,
		arg.OrgID,
	)
	var i DeployTarget
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.RunsOn,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecretCfg,
		&i.StoredSecretKeys,
	)
	return i, err
}

const updateHook = `-- name: UpdateHook :one
UPDATE hooks SET name = $1, phase = $2, argv = $3,
       timeout_seconds = $4, updated_at = now()
WHERE id = $5 AND org_id = $6 RETURNING id, org_id, name, phase, argv, timeout_seconds, created_at, updated_at
`

type UpdateHookParams struct {
	Name           string    `json:"name"`
	Phase          string    `json:"phase"`
	Argv           []string  `json:"argv"`
	TimeoutSeconds int32     `json:"timeout_seconds"`
	ID             uuid.UUID `json:"id"`
	OrgID          uuid.UUID `json:"org_id"`
}

func (q *Queries) UpdateHook(ctx context.Context, arg UpdateHookParams) (Hook, error) {
	row := q.db.QueryRow(ctx, updateHook,
		arg.Name,
		arg.Phase,
		arg.Argv,
		arg.TimeoutSeconds,
		arg.ID,
		arg.OrgID,
	)
	var i Hook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Phase,
		&i.Argv,
		&i.TimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLayout = `-- name: UpdateLayout :one
UPDATE output_specs SET name = $1, files = $2, password = $3,
       extra_cert_ids = $4, updated_at = now()
WHERE id = $5 AND org_id = $6 RETURNING id, org_id, name, files, created_at, updated_at, password, extra_cert_ids
`

type UpdateLayoutParams struct {
	Name         string      `json:"name"`
	Files        []byte      `json:"files"`
	Password     []byte      `json:"password"`
	ExtraCertIds []uuid.UUID `json:"extra_cert_ids"`
	ID           uuid.UUID   `json:"id"`
	OrgID        uuid.UUID   `json:"org_id"`
}

func (q *Queries) UpdateLayout(ctx context.Context, arg UpdateLayoutParams) (OutputSpec, error) {
	row := q.db.QueryRow(ctx, updateLayout,
		arg.Name,
		arg.Files,
		arg.Password,
		arg.ExtraCertIds,
		arg.ID,
		arg.OrgID,
	)
	var i OutputSpec
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Files,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.ExtraCertIds,
	)
	return i, err
}
