// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: dns_credentials.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countDNSCredentialUsers = `-- name: CountDNSCredentialUsers :one
SELECT (
    (SELECT count(*) FROM certificates c
      WHERE c.verification_rules @> jsonb_build_array(jsonb_build_object('dnsCredentialId', $1::uuid::text))
         OR c.overrides->'verificationRules' @> jsonb_build_array(jsonb_build_object('dnsCredentialId', $1::uuid::text)))
  + (SELECT count(*) FROM issuance_defaults d
      WHERE d.config->'verificationRules' @> jsonb_build_array(jsonb_build_object('dnsCredentialId', $1::uuid::text)))
)::bigint AS users
`

// Certificates or org defaults whose rules reference the credential.
func (q *Queries) CountDNSCredentialUsers(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDNSCredentialUsers, id)
	var users int64
	err := row.Scan(&users)
	return users, err
}

const createDNSCredential = `-- name: CreateDNSCredential :one
INSERT INTO dns_provider_credentials (org_id, name, provider_code, public_cfg, secret_cfg)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, name, provider_code, public_cfg, secret_cfg, created_at, updated_at
`

type CreateDNSCredentialParams struct {
	OrgID        uuid.UUID `json:"org_id"`
	Name         string    `json:"name"`
	ProviderCode string    `json:"provider_code"`
	PublicCfg    []byte    `json:"public_cfg"`
	SecretCfg    []byte    `json:"secret_cfg"`
}

func (q *Queries) CreateDNSCredential(ctx context.Context, arg CreateDNSCredentialParams) (DnsProviderCredential, error) {
	row := q.db.QueryRow(ctx, createDNSCredential,
		arg.OrgID,
		arg.Name,
		arg.ProviderCode,
		arg.PublicCfg,
		arg.SecretCfg,
	)
	var i DnsProviderCredential
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ProviderCode,
		&i.PublicCfg,
		&i.SecretCfg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDNSCredential = `-- name: DeleteDNSCredential :execrows
DELETE FROM dns_provider_credentials WHERE id = $1 AND org_id = $2
`

type DeleteDNSCredentialParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteDNSCredential(ctx context.Context, arg DeleteDNSCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDNSCredential, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDNSCredential = `-- name: GetDNSCredential :one
SELECT id, org_id, name, provider_code, public_cfg, secret_cfg, created_at, updated_at FROM dns_provider_credentials WHERE id = $1 AND org_id = $2
`

type GetDNSCredentialParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetDNSCredential(ctx context.Context, arg GetDNSCredentialParams) (DnsProviderCredential, error) {
	row := q.db.QueryRow(ctx, getDNSCredential, arg.ID, arg.OrgID)
	var i DnsProviderCredential
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ProviderCode,
		&i.PublicCfg,
		&i.SecretCfg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDNSCredentials = `-- name: ListDNSCredentials :many
SELECT id, org_id, name, provider_code, public_cfg, secret_cfg, created_at, updated_at FROM dns_provider_credentials WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListDNSCredentials(ctx context.Context, orgID uuid.UUID) ([]DnsProviderCredential, error) {
	rows, err := q.db.Query(ctx, listDNSCredentials, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsProviderCredential{}
	for rows.Next() {
		var i DnsProviderCredential
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.ProviderCode,
			&i.PublicCfg,
			&i.SecretCfg,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDNSCredential = `-- name: UpdateDNSCredential :one
UPDATE dns_provider_credentials SET name = $3, public_cfg = $4, secret_cfg = $5, updated_at = now()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, provider_code, public_cfg, secret_cfg, created_at, updated_at
`

type UpdateDNSCredentialParams struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"org_id"`
	Name      string    `json:"name"`
	PublicCfg []byte    `json:"public_cfg"`
	SecretCfg []byte    `json:"secret_cfg"`
}

func (q *Queries) UpdateDNSCredential(ctx context.Context, arg UpdateDNSCredentialParams) (DnsProviderCredential, error) {
	row := q.db.QueryRow(ctx, updateDNSCredential,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.PublicCfg,
		arg.SecretCfg,
	)
	var i DnsProviderCredential
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ProviderCode,
		&i.PublicCfg,
		&i.SecretCfg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
