// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: issuers.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countAccountUsers = `-- name: CountAccountUsers :one
SELECT (
    (SELECT count(*) FROM certificates c WHERE c.overrides->>'accountId' = $1::uuid::text)
  + (SELECT count(*) FROM issuance_defaults d WHERE d.config->>'accountId' = $1::uuid::text)
)::bigint AS users
`

func (q *Queries) CountAccountUsers(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountUsers, id)
	var users int64
	err := row.Scan(&users)
	return users, err
}

const countCAUsers = `-- name: CountCAUsers :one
SELECT (
    (SELECT count(*) FROM acme_accounts a WHERE a.ca_id = $1::uuid)
  + (SELECT count(*) FROM certificates c WHERE c.overrides->>'caId' = $1::uuid::text)
  + (SELECT count(*) FROM issuance_defaults d WHERE d.config->>'caId' = $1::uuid::text)
)::bigint AS users
`

func (q *Queries) CountCAUsers(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCAUsers, id)
	var users int64
	err := row.Scan(&users)
	return users, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO acme_accounts (org_id, ca_id, email, account_key, registration_uri)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, ca_id, email, account_key, registration_uri, status, created_at
`

type CreateAccountParams struct {
	OrgID           uuid.UUID `json:"org_id"`
	CaID            uuid.UUID `json:"ca_id"`
	Email           string    `json:"email"`
	AccountKey      []byte    `json:"account_key"`
	RegistrationUri string    `json:"registration_uri"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (AcmeAccount, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.OrgID,
		arg.CaID,
		arg.Email,
		arg.AccountKey,
		arg.RegistrationUri,
	)
	var i AcmeAccount
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CaID,
		&i.Email,
		&i.AccountKey,
		&i.RegistrationUri,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createCA = `-- name: CreateCA :one
INSERT INTO cas (org_id, name, preset, directory_url, trust_bundle_pem, eab_kid, eab_hmac, resolvers)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, name, type, preset, directory_url, trust_bundle_pem, eab_kid, eab_hmac, resolvers, shared, created_at, updated_at
`

type CreateCAParams struct {
	OrgID          uuid.UUID `json:"org_id"`
	Name           string    `json:"name"`
	Preset         string    `json:"preset"`
	DirectoryUrl   string    `json:"directory_url"`
	TrustBundlePem string    `json:"trust_bundle_pem"`
	EabKid         string    `json:"eab_kid"`
	EabHmac        []byte    `json:"eab_hmac"`
	Resolvers      []string  `json:"resolvers"`
}

func (q *Queries) CreateCA(ctx context.Context, arg CreateCAParams) (Ca, error) {
	row := q.db.QueryRow(ctx, createCA,
		arg.OrgID,
		arg.Name,
		arg.Preset,
		arg.DirectoryUrl,
		arg.TrustBundlePem,
		arg.EabKid,
		arg.EabHmac,
		arg.Resolvers,
	)
	var i Ca
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.Preset,
		&i.DirectoryUrl,
		&i.TrustBundlePem,
		&i.EabKid,
		&i.EabHmac,
		&i.Resolvers,
		&i.Shared,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM acme_accounts WHERE id = $1 AND org_id = $2
`

type DeleteAccountParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCA = `-- name: DeleteCA :execrows
DELETE FROM cas WHERE id = $1 AND org_id = $2
`

type DeleteCAParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteCA(ctx context.Context, arg DeleteCAParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCA, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccount = `-- name: GetAccount :one
SELECT id, org_id, ca_id, email, account_key, registration_uri, status, created_at FROM acme_accounts WHERE id = $1 AND org_id = $2
`

type GetAccountParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (AcmeAccount, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.ID, arg.OrgID)
	var i AcmeAccount
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CaID,
		&i.Email,
		&i.AccountKey,
		&i.RegistrationUri,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, org_id, ca_id, email, account_key, registration_uri, status, created_at FROM acme_accounts WHERE id = $1
`

// Ignores org scope: used only to check that an account referenced by the
// global issuance_defaults settings section still exists (and which CA it
// belongs to).
func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (AcmeAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i AcmeAccount
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CaID,
		&i.Email,
		&i.AccountKey,
		&i.RegistrationUri,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCA = `-- name: GetCA :one
SELECT id, org_id, name, type, preset, directory_url, trust_bundle_pem, eab_kid, eab_hmac, resolvers, shared, created_at, updated_at FROM cas WHERE id = $1 AND org_id = $2
`

type GetCAParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetCA(ctx context.Context, arg GetCAParams) (Ca, error) {
	row := q.db.QueryRow(ctx, getCA, arg.ID, arg.OrgID)
	var i Ca
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.Preset,
		&i.DirectoryUrl,
		&i.TrustBundlePem,
		&i.EabKid,
		&i.EabHmac,
		&i.Resolvers,
		&i.Shared,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCAByID = `-- name: GetCAByID :one
SELECT id, org_id, name, type, preset, directory_url, trust_bundle_pem, eab_kid, eab_hmac, resolvers, shared, created_at, updated_at FROM cas WHERE id = $1
`

// Ignores org scope: used only to check that a CA referenced by the global
// issuance_defaults settings section (which is not org-scoped) still exists.
func (q *Queries) GetCAByID(ctx context.Context, id uuid.UUID) (Ca, error) {
	row := q.db.QueryRow(ctx, getCAByID, id)
	var i Ca
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.Preset,
		&i.DirectoryUrl,
		&i.TrustBundlePem,
		&i.EabKid,
		&i.EabHmac,
		&i.Resolvers,
		&i.Shared,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, org_id, ca_id, email, account_key, registration_uri, status, created_at FROM acme_accounts WHERE org_id = $1 ORDER BY email
`

func (q *Queries) ListAccounts(ctx context.Context, orgID uuid.UUID) ([]AcmeAccount, error) {
	rows, err := q.db.Query(ctx, listAccounts, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcmeAccount{}
	for rows.Next() {
		var i AcmeAccount
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CaID,
			&i.Email,
			&i.AccountKey,
			&i.RegistrationUri,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCAs = `-- name: ListCAs :many
SELECT id, org_id, name, type, preset, directory_url, trust_bundle_pem, eab_kid, eab_hmac, resolvers, shared, created_at, updated_at FROM cas WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListCAs(ctx context.Context, orgID uuid.UUID) ([]Ca, error) {
	rows, err := q.db.Query(ctx, listCAs, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ca{}
	for rows.Next() {
		var i Ca
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Type,
			&i.Preset,
			&i.DirectoryUrl,
			&i.TrustBundlePem,
			&i.EabKid,
			&i.EabHmac,
			&i.Resolvers,
			&i.Shared,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCA = `-- name: UpdateCA :one
UPDATE cas SET name = $3, preset = $4, directory_url = $5, trust_bundle_pem = $6,
    eab_kid = $7, eab_hmac = $8, resolvers = $9, updated_at = now()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, type, preset, directory_url, trust_bundle_pem, eab_kid, eab_hmac, resolvers, shared, created_at, updated_at
`

type UpdateCAParams struct {
	ID             uuid.UUID `json:"id"`
	OrgID          uuid.UUID `json:"org_id"`
	Name           string    `json:"name"`
	Preset         string    `json:"preset"`
	DirectoryUrl   string    `json:"directory_url"`
	TrustBundlePem string    `json:"trust_bundle_pem"`
	EabKid         string    `json:"eab_kid"`
	EabHmac        []byte    `json:"eab_hmac"`
	Resolvers      []string  `json:"resolvers"`
}

func (q *Queries) UpdateCA(ctx context.Context, arg UpdateCAParams) (Ca, error) {
	row := q.db.QueryRow(ctx, updateCA,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Preset,
		arg.DirectoryUrl,
		arg.TrustBundlePem,
		arg.EabKid,
		arg.EabHmac,
		arg.Resolvers,
	)
	var i Ca
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.Preset,
		&i.DirectoryUrl,
		&i.TrustBundlePem,
		&i.EabKid,
		&i.EabHmac,
		&i.Resolvers,
		&i.Shared,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
