// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: metrics.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const metricsCertificateNotAfter = `-- name: MetricsCertificateNotAfter :many
SELECT o.slug AS org, c.id AS certificate, v.not_after AS not_after
FROM certificates c
JOIN orgs o ON o.id = c.org_id
JOIN certificate_versions v ON v.id = c.current_version_id
WHERE c.current_version_id IS NOT NULL
`

type MetricsCertificateNotAfterRow struct {
	Org         string    `json:"org"`
	Certificate uuid.UUID `json:"certificate"`
	NotAfter    time.Time `json:"not_after"`
}

// Cardinality note (binding requirement): one row per certificate that has
// an issued version, labelled by the certificate's own id — bounded by the
// number of certificates, not by name (free text) or version history.
func (q *Queries) MetricsCertificateNotAfter(ctx context.Context) ([]MetricsCertificateNotAfterRow, error) {
	rows, err := q.db.Query(ctx, metricsCertificateNotAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricsCertificateNotAfterRow{}
	for rows.Next() {
		var i MetricsCertificateNotAfterRow
		if err := rows.Scan(&i.Org, &i.Certificate, &i.NotAfter); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const metricsCertificatesByStatus = `-- name: MetricsCertificatesByStatus :many

SELECT o.slug AS org, c.status AS status, count(*) AS count
FROM certificates c
JOIN orgs o ON o.id = c.org_id
GROUP BY o.slug, c.status
`

type MetricsCertificatesByStatusRow struct {
	Org    string `json:"org"`
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

// Phase 6A Task 8: the database-backed series Collector queries once per
// scrape (cached CacheTTL). river_job is river's own table, outside this
// schema, so its stats are queried directly in collector.go instead of
// here; backup.status and crypto.rewrap (Deviations R6/Task 5) are plain
// settings.Store reads, not sqlc queries.
func (q *Queries) MetricsCertificatesByStatus(ctx context.Context) ([]MetricsCertificatesByStatusRow, error) {
	rows, err := q.db.Query(ctx, metricsCertificatesByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricsCertificatesByStatusRow{}
	for rows.Next() {
		var i MetricsCertificatesByStatusRow
		if err := rows.Scan(&i.Org, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const metricsCertificatesDueRenewal = `-- name: MetricsCertificatesDueRenewal :many
SELECT o.slug AS org, count(*) AS count
FROM certificates c
JOIN orgs o ON o.id = c.org_id
WHERE c.managed AND c.next_renew_at IS NOT NULL AND c.next_renew_at <= now()
GROUP BY o.slug
`

type MetricsCertificatesDueRenewalRow struct {
	Org   string `json:"org"`
	Count int64  `json:"count"`
}

func (q *Queries) MetricsCertificatesDueRenewal(ctx context.Context) ([]MetricsCertificatesDueRenewalRow, error) {
	rows, err := q.db.Query(ctx, metricsCertificatesDueRenewal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricsCertificatesDueRenewalRow{}
	for rows.Next() {
		var i MetricsCertificatesDueRenewalRow
		if err := rows.Scan(&i.Org, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const metricsClientsByStatus = `-- name: MetricsClientsByStatus :many
SELECT o.slug AS org,
       (CASE
           WHEN c.status = 'active' AND c.last_seen >= $1::timestamptz THEN 'online'
           WHEN c.status = 'active' THEN 'offline'
           ELSE c.status
       END)::text AS status,
       count(*) AS count
FROM clients c
JOIN orgs o ON o.id = c.org_id
GROUP BY 1, 2
`

type MetricsClientsByStatusRow struct {
	Org    string `json:"org"`
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

// online = active and seen within the "agents" section's offlineAfterSeconds
// (collector.go's own onlineCutoff, mirroring agents.Service.OnlineCutoff);
// pending/revoked pass through unchanged.
func (q *Queries) MetricsClientsByStatus(ctx context.Context, onlineCutoff time.Time) ([]MetricsClientsByStatusRow, error) {
	rows, err := q.db.Query(ctx, metricsClientsByStatus, onlineCutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricsClientsByStatusRow{}
	for rows.Next() {
		var i MetricsClientsByStatusRow
		if err := rows.Scan(&i.Org, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const metricsDeploymentsByStatus = `-- name: MetricsDeploymentsByStatus :many
SELECT o.slug AS org, d.state AS status, count(*) AS count
FROM deployments d
JOIN client_cert_grants g ON g.id = d.grant_id
JOIN clients c ON c.id = g.client_id
JOIN orgs o ON o.id = c.org_id
WHERE g.removed_at IS NULL
GROUP BY o.slug, d.state
UNION ALL
SELECT o.slug AS org,
       (CASE sd.status WHEN 'deployed' THEN 'ok' ELSE sd.status END)::text AS status,
       count(*) AS count
FROM server_deployments sd
JOIN client_cert_grants g ON g.id = sd.grant_id
JOIN deploy_targets t ON t.id = g.deploy_target_id
JOIN orgs o ON o.id = t.org_id
WHERE g.removed_at IS NULL
GROUP BY o.slug, sd.status
`

type MetricsDeploymentsByStatusRow struct {
	Org    string `json:"org"`
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

// Agent-run grants (deployments.state is already pending/ok/failed/drift)
// unioned with server-run grants (server_deployments.status has no drift
// state; deployed maps to ok, matching the agent side's own terminal
// success state). Two rows for the same (org, status) pair are summed in
// Go, not here, since the two SELECTs group independently.
func (q *Queries) MetricsDeploymentsByStatus(ctx context.Context) ([]MetricsDeploymentsByStatusRow, error) {
	rows, err := q.db.Query(ctx, metricsDeploymentsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricsDeploymentsByStatusRow{}
	for rows.Next() {
		var i MetricsDeploymentsByStatusRow
		if err := rows.Scan(&i.Org, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const metricsMonitorsByState = `-- name: MetricsMonitorsByState :many
SELECT o.slug AS org, m.state AS state, count(*) AS count
FROM external_monitors m
JOIN orgs o ON o.id = m.org_id
GROUP BY o.slug, m.state
`

type MetricsMonitorsByStateRow struct {
	Org   string `json:"org"`
	State string `json:"state"`
	Count int64  `json:"count"`
}

func (q *Queries) MetricsMonitorsByState(ctx context.Context) ([]MetricsMonitorsByStateRow, error) {
	rows, err := q.db.Query(ctx, metricsMonitorsByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricsMonitorsByStateRow{}
	for rows.Next() {
		var i MetricsMonitorsByStateRow
		if err := rows.Scan(&i.Org, &i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
