// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type AcmeAccount struct {
	ID              uuid.UUID `json:"id"`
	OrgID           uuid.UUID `json:"org_id"`
	CaID            uuid.UUID `json:"ca_id"`
	Email           string    `json:"email"`
	AccountKey      []byte    `json:"account_key"`
	RegistrationUri string    `json:"registration_uri"`
	Status          string    `json:"status"`
	CreatedAt       time.Time `json:"created_at"`
}

type AgentCa struct {
	ID        uuid.UUID `json:"id"`
	CertDer   []byte    `json:"cert_der"`
	Key       []byte    `json:"key"`
	Status    string    `json:"status"`
	NotBefore time.Time `json:"not_before"`
	NotAfter  time.Time `json:"not_after"`
	CreatedAt time.Time `json:"created_at"`
}

type ApiKey struct {
	ID         uuid.UUID  `json:"id"`
	Name       string     `json:"name"`
	Prefix     string     `json:"prefix"`
	SecretHash []byte     `json:"secret_hash"`
	Scopes     []string   `json:"scopes"`
	OrgID      *uuid.UUID `json:"org_id"`
	CreatedBy  uuid.UUID  `json:"created_by"`
	ExpiresAt  *time.Time `json:"expires_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
	CreatedAt  time.Time  `json:"created_at"`
}

type AuditEvent struct {
	ID           int64      `json:"id"`
	Ts           time.Time  `json:"ts"`
	ActorType    string     `json:"actor_type"`
	ActorID      string     `json:"actor_id"`
	Action       string     `json:"action"`
	ResourceType string     `json:"resource_type"`
	ResourceID   string     `json:"resource_id"`
	OrgID        *uuid.UUID `json:"org_id"`
	Ip           string     `json:"ip"`
	Details      []byte     `json:"details"`
	PrevHash     []byte     `json:"prev_hash"`
	Hash         []byte     `json:"hash"`
	HashAlg      string     `json:"hash_alg"`
}

type Ca struct {
	ID             uuid.UUID  `json:"id"`
	OrgID          uuid.UUID  `json:"org_id"`
	Name           string     `json:"name"`
	Type           string     `json:"type"`
	Preset         string     `json:"preset"`
	DirectoryUrl   string     `json:"directory_url"`
	TrustBundlePem string     `json:"trust_bundle_pem"`
	EabKid         string     `json:"eab_kid"`
	EabHmac        []byte     `json:"eab_hmac"`
	Resolvers      []string   `json:"resolvers"`
	Shared         bool       `json:"shared"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	Config         []byte     `json:"config"`
	SecretCfg      []byte     `json:"secret_cfg"`
	NotBefore      *time.Time `json:"not_before"`
	NotAfter       *time.Time `json:"not_after"`
	CrlNumber      int64      `json:"crl_number"`
}

type Certificate struct {
	ID                uuid.UUID  `json:"id"`
	OrgID             uuid.UUID  `json:"org_id"`
	Name              string     `json:"name"`
	CommonName        string     `json:"common_name"`
	Sans              []string   `json:"sans"`
	VerificationRules []byte     `json:"verification_rules"`
	Overrides         []byte     `json:"overrides"`
	Status            string     `json:"status"`
	CurrentVersionID  *uuid.UUID `json:"current_version_id"`
	NextRenewAt       *time.Time `json:"next_renew_at"`
	FailureCount      int32      `json:"failure_count"`
	LastError         string     `json:"last_error"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	Managed           bool       `json:"managed"`
	AriWindowStart    *time.Time `json:"ari_window_start"`
	AriWindowEnd      *time.Time `json:"ari_window_end"`
	AriCheckedAt      *time.Time `json:"ari_checked_at"`
	AriRetryAfter     *time.Time `json:"ari_retry_after"`
}

type CertificateVersion struct {
	ID         uuid.UUID  `json:"id"`
	CertID     uuid.UUID  `json:"cert_id"`
	Serial     string     `json:"serial"`
	NotBefore  time.Time  `json:"not_before"`
	NotAfter   time.Time  `json:"not_after"`
	Sha256Fp   string     `json:"sha256_fp"`
	KeyType    string     `json:"key_type"`
	LeafDer    []byte     `json:"leaf_der"`
	ChainDer   [][]byte   `json:"chain_der"`
	PrivateKey []byte     `json:"private_key"`
	Source     string     `json:"source"`
	AriWindow  []byte     `json:"ari_window"`
	RevokedAt  *time.Time `json:"revoked_at"`
	CreatedAt  time.Time  `json:"created_at"`
	CaID       *uuid.UUID `json:"ca_id"`
}

type Client struct {
	ID                uuid.UUID  `json:"id"`
	OrgID             uuid.UUID  `json:"org_id"`
	SiteID            *uuid.UUID `json:"site_id"`
	Name              string     `json:"name"`
	Status            string     `json:"status"`
	AgentCertSerial   string     `json:"agent_cert_serial"`
	AgentCertNotAfter *time.Time `json:"agent_cert_not_after"`
	AgentCaID         *uuid.UUID `json:"agent_ca_id"`
	Hostname          string     `json:"hostname"`
	Os                string     `json:"os"`
	Arch              string     `json:"arch"`
	AgentVersion      string     `json:"agent_version"`
	Capabilities      []string   `json:"capabilities"`
	LastSeen          *time.Time `json:"last_seen"`
	DesiredRevision   int64      `json:"desired_revision"`
	AppliedRevision   int64      `json:"applied_revision"`
	CreatedAt         time.Time  `json:"created_at"`
}

type ClientCertGrant struct {
	ID              uuid.UUID   `json:"id"`
	ClientID        *uuid.UUID  `json:"client_id"`
	CertID          uuid.UUID   `json:"cert_id"`
	Delivery        string      `json:"delivery"`
	OutputSpecID    *uuid.UUID  `json:"output_spec_id"`
	DeployTargetID  *uuid.UUID  `json:"deploy_target_id"`
	HookIds         []uuid.UUID `json:"hook_ids"`
	AutoRemediate   bool        `json:"auto_remediate"`
	RemovedAt       *time.Time  `json:"removed_at"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	RemovedRevision int64       `json:"removed_revision"`
	RedeploySeq     int64       `json:"redeploy_seq"`
}

type DeployTarget struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"org_id"`
	Name      string    `json:"name"`
	Type      string    `json:"type"`
	RunsOn    string    `json:"runs_on"`
	Config    []byte    `json:"config"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	SecretCfg []byte    `json:"secret_cfg"`
}

type Deployment struct {
	ID              uuid.UUID   `json:"id"`
	GrantID         uuid.UUID   `json:"grant_id"`
	VersionID       *uuid.UUID  `json:"version_id"`
	State           string      `json:"state"`
	Expected        []byte      `json:"expected"`
	Installed       []byte      `json:"installed"`
	Error           string      `json:"error"`
	ReportedAt      *time.Time  `json:"reported_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	ExtraVersionIds []uuid.UUID `json:"extra_version_ids"`
	StateChangedAt  time.Time   `json:"state_changed_at"`
}

type DnsProviderCredential struct {
	ID           uuid.UUID `json:"id"`
	OrgID        uuid.UUID `json:"org_id"`
	Name         string    `json:"name"`
	ProviderCode string    `json:"provider_code"`
	PublicCfg    []byte    `json:"public_cfg"`
	SecretCfg    []byte    `json:"secret_cfg"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type EnrollmentToken struct {
	ID        uuid.UUID  `json:"id"`
	ClientID  uuid.UUID  `json:"client_id"`
	TokenHash []byte     `json:"token_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
	CreatedBy string     `json:"created_by"`
	CreatedAt time.Time  `json:"created_at"`
}

type ExternalMonitor struct {
	ID              uuid.UUID  `json:"id"`
	OrgID           uuid.UUID  `json:"org_id"`
	Name            string     `json:"name"`
	Host            string     `json:"host"`
	Port            int32      `json:"port"`
	Sni             *string    `json:"sni"`
	IntervalSeconds int32      `json:"interval_seconds"`
	ExpectedCertID  *uuid.UUID `json:"expected_cert_id"`
	Enabled         bool       `json:"enabled"`
	State           string     `json:"state"`
	StateChangedAt  time.Time  `json:"state_changed_at"`
	LastCheckedAt   *time.Time `json:"last_checked_at"`
	NextCheckAt     time.Time  `json:"next_check_at"`
	LastFingerprint string     `json:"last_fingerprint"`
	LastNotAfter    *time.Time `json:"last_not_after"`
	LastIssuer      string     `json:"last_issuer"`
	LastError       string     `json:"last_error"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

type Hook struct {
	ID             uuid.UUID `json:"id"`
	OrgID          uuid.UUID `json:"org_id"`
	Name           string    `json:"name"`
	Phase          string    `json:"phase"`
	Argv           []string  `json:"argv"`
	TimeoutSeconds int32     `json:"timeout_seconds"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type HookRun struct {
	ID         uuid.UUID  `json:"id"`
	ClientID   uuid.UUID  `json:"client_id"`
	GrantID    *uuid.UUID `json:"grant_id"`
	HookID     *uuid.UUID `json:"hook_id"`
	Phase      string     `json:"phase"`
	Argv       []string   `json:"argv"`
	ExitCode   int32      `json:"exit_code"`
	DurationMs int64      `json:"duration_ms"`
	Stdout     string     `json:"stdout"`
	Stderr     string     `json:"stderr"`
	RanAt      time.Time  `json:"ran_at"`
}

type IssuanceAttempt struct {
	ID            uuid.UUID  `json:"id"`
	CertID        uuid.UUID  `json:"cert_id"`
	StartedAt     time.Time  `json:"started_at"`
	FinishedAt    *time.Time `json:"finished_at"`
	Outcome       string     `json:"outcome"`
	AcmeErrorType string     `json:"acme_error_type"`
	RetryAfter    *time.Time `json:"retry_after"`
	Steps         []byte     `json:"steps"`
	Log           string     `json:"log"`
}

type IssuanceDefault struct {
	OrgID     uuid.UUID `json:"org_id"`
	Config    []byte    `json:"config"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ManualDnsPending struct {
	ID          uuid.UUID  `json:"id"`
	AttemptID   uuid.UUID  `json:"attempt_id"`
	CertID      uuid.UUID  `json:"cert_id"`
	Domain      string     `json:"domain"`
	Fqdn        string     `json:"fqdn"`
	Value       string     `json:"value"`
	Ttl         int32      `json:"ttl"`
	ExpiresAt   time.Time  `json:"expires_at"`
	ConfirmedAt *time.Time `json:"confirmed_at"`
	CreatedAt   time.Time  `json:"created_at"`
}

type NotificationChannel struct {
	ID          uuid.UUID `json:"id"`
	OrgID       uuid.UUID `json:"org_id"`
	Name        string    `json:"name"`
	Type        string    `json:"type"`
	Config      []byte    `json:"config"`
	SecretCfg   []byte    `json:"secret_cfg"`
	Events      []string  `json:"events"`
	MinSeverity string    `json:"min_severity"`
	AllOrgs     bool      `json:"all_orgs"`
	Enabled     bool      `json:"enabled"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type NotificationDelivery struct {
	EventID     uuid.UUID  `json:"event_id"`
	ChannelID   uuid.UUID  `json:"channel_id"`
	Attempts    int32      `json:"attempts"`
	Status      string     `json:"status"`
	LastError   string     `json:"last_error"`
	DeliveredAt *time.Time `json:"delivered_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type NotificationEvent struct {
	ID           uuid.UUID  `json:"id"`
	OrgID        *uuid.UUID `json:"org_id"`
	Kind         string     `json:"kind"`
	Severity     string     `json:"severity"`
	ResourceType string     `json:"resource_type"`
	ResourceID   string     `json:"resource_id"`
	ResourceName string     `json:"resource_name"`
	Summary      string     `json:"summary"`
	Details      []byte     `json:"details"`
	DedupeKey    string     `json:"dedupe_key"`
	At           time.Time  `json:"at"`
}

type Org struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type OutputSpec struct {
	ID           uuid.UUID   `json:"id"`
	OrgID        uuid.UUID   `json:"org_id"`
	Name         string      `json:"name"`
	Files        []byte      `json:"files"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	Password     []byte      `json:"password"`
	ExtraCertIds []uuid.UUID `json:"extra_cert_ids"`
}

type RateLedger struct {
	ID               uuid.UUID  `json:"id"`
	CaID             uuid.UUID  `json:"ca_id"`
	Kind             string     `json:"kind"`
	RegisteredDomain string     `json:"registered_domain"`
	NamesHash        string     `json:"names_hash"`
	CertID           *uuid.UUID `json:"cert_id"`
	At               time.Time  `json:"at"`
}

type RoleBinding struct {
	ID          uuid.UUID  `json:"id"`
	SubjectType string     `json:"subject_type"`
	Subject     string     `json:"subject"`
	Role        string     `json:"role"`
	OrgID       *uuid.UUID `json:"org_id"`
	SiteID      *uuid.UUID `json:"site_id"`
	CreatedAt   time.Time  `json:"created_at"`
}

type ServerDeployment struct {
	GrantID        uuid.UUID  `json:"grant_id"`
	VersionID      *uuid.UUID `json:"version_id"`
	Status         string     `json:"status"`
	LastError      string     `json:"last_error"`
	DeployedAt     *time.Time `json:"deployed_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	StateChangedAt time.Time  `json:"state_changed_at"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Csrf      string    `json:"csrf"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Setting struct {
	Key       string    `json:"key"`
	Value     []byte    `json:"value"`
	Secret    []byte    `json:"secret"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Site struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"org_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID                uuid.UUID  `json:"id"`
	OidcIssuer        *string    `json:"oidc_issuer"`
	OidcSub           *string    `json:"oidc_sub"`
	Email             *string    `json:"email"`
	DisplayName       string     `json:"display_name"`
	LocalPasswordHash *string    `json:"local_password_hash"`
	Disabled          bool       `json:"disabled"`
	LastLogin         *time.Time `json:"last_login"`
	CreatedAt         time.Time  `json:"created_at"`
	OidcGroups        []string   `json:"oidc_groups"`
}
