// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notify.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id, org_id, name, type, config, secret_cfg, events, min_severity, all_orgs, enabled, created_at, updated_at FROM notification_channels WHERE id = $1
`

func (q *Queries) GetNotificationChannel(ctx context.Context, id uuid.UUID) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannel, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.SecretCfg,
		&i.Events,
		&i.MinSeverity,
		&i.AllOrgs,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationDelivery = `-- name: GetNotificationDelivery :one
SELECT event_id, channel_id, attempts, status, last_error, delivered_at, updated_at FROM notification_deliveries WHERE event_id = $1 AND channel_id = $2
`

type GetNotificationDeliveryParams struct {
	EventID   uuid.UUID `json:"event_id"`
	ChannelID uuid.UUID `json:"channel_id"`
}

func (q *Queries) GetNotificationDelivery(ctx context.Context, arg GetNotificationDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, getNotificationDelivery, arg.EventID, arg.ChannelID)
	var i NotificationDelivery
	err := row.Scan(
		&i.EventID,
		&i.ChannelID,
		&i.Attempts,
		&i.Status,
		&i.LastError,
		&i.DeliveredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationEvent = `-- name: GetNotificationEvent :one
SELECT id, org_id, kind, severity, resource_type, resource_id, resource_name, summary, details, dedupe_key, at FROM notification_events WHERE id = $1
`

func (q *Queries) GetNotificationEvent(ctx context.Context, id uuid.UUID) (NotificationEvent, error) {
	row := q.db.QueryRow(ctx, getNotificationEvent, id)
	var i NotificationEvent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Kind,
		&i.Severity,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceName,
		&i.Summary,
		&i.Details,
		&i.DedupeKey,
		&i.At,
	)
	return i, err
}

const insertNotificationDelivery = `-- name: InsertNotificationDelivery :exec
INSERT INTO notification_deliveries (event_id, channel_id) VALUES ($1, $2)
ON CONFLICT (event_id, channel_id) DO NOTHING
`

type InsertNotificationDeliveryParams struct {
	EventID   uuid.UUID `json:"event_id"`
	ChannelID uuid.UUID `json:"channel_id"`
}

func (q *Queries) InsertNotificationDelivery(ctx context.Context, arg InsertNotificationDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertNotificationDelivery, arg.EventID, arg.ChannelID)
	return err
}

const insertNotificationEvent = `-- name: InsertNotificationEvent :one
INSERT INTO notification_events (org_id, kind, severity, resource_type, resource_id, resource_name, summary, details, dedupe_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (dedupe_key) DO NOTHING
RETURNING id
`

type InsertNotificationEventParams struct {
	OrgID        *uuid.UUID `json:"org_id"`
	Kind         string     `json:"kind"`
	Severity     string     `json:"severity"`
	ResourceType string     `json:"resource_type"`
	ResourceID   string     `json:"resource_id"`
	ResourceName string     `json:"resource_name"`
	Summary      string     `json:"summary"`
	Details      []byte     `json:"details"`
	DedupeKey    string     `json:"dedupe_key"`
}

// Emit's exact-once guard (Shared contract's Dedupe keys row): a UNIQUE
// violation on dedupe_key is swallowed here via ON CONFLICT DO NOTHING, so
// Emit sees zero rows back and treats the event as an already-fired
// duplicate instead of erroring.
func (q *Queries) InsertNotificationEvent(ctx context.Context, arg InsertNotificationEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertNotificationEvent,
		arg.OrgID,
		arg.Kind,
		arg.Severity,
		arg.ResourceType,
		arg.ResourceID,
		arg.ResourceName,
		arg.Summary,
		arg.Details,
		arg.DedupeKey,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const markNotificationDeliveryDelivered = `-- name: MarkNotificationDeliveryDelivered :exec
UPDATE notification_deliveries SET attempts = $3, status = 'delivered', last_error = '', delivered_at = now(), updated_at = now()
WHERE event_id = $1 AND channel_id = $2
`

type MarkNotificationDeliveryDeliveredParams struct {
	EventID   uuid.UUID `json:"event_id"`
	ChannelID uuid.UUID `json:"channel_id"`
	Attempts  int32     `json:"attempts"`
}

func (q *Queries) MarkNotificationDeliveryDelivered(ctx context.Context, arg MarkNotificationDeliveryDeliveredParams) error {
	_, err := q.db.Exec(ctx, markNotificationDeliveryDelivered, arg.EventID, arg.ChannelID, arg.Attempts)
	return err
}

const markNotificationDeliveryFailed = `-- name: MarkNotificationDeliveryFailed :exec
UPDATE notification_deliveries SET attempts = $3, status = $4, last_error = $5, updated_at = now()
WHERE event_id = $1 AND channel_id = $2
`

type MarkNotificationDeliveryFailedParams struct {
	EventID   uuid.UUID `json:"event_id"`
	ChannelID uuid.UUID `json:"channel_id"`
	Attempts  int32     `json:"attempts"`
	Status    string    `json:"status"`
	LastError string    `json:"last_error"`
}

// status is 'failed' once the worker's own attempt count has reached the
// job's MaxAttempts, else 'pending' (still retryable) — DeliverWorker
// decides which and passes it in, since only it knows river's MaxAttempts.
func (q *Queries) MarkNotificationDeliveryFailed(ctx context.Context, arg MarkNotificationDeliveryFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationDeliveryFailed,
		arg.EventID,
		arg.ChannelID,
		arg.Attempts,
		arg.Status,
		arg.LastError,
	)
	return err
}

const matchingChannels = `-- name: MatchingChannels :many
SELECT id FROM notification_channels
WHERE enabled
  AND (org_id = $1 OR all_orgs)
  AND (cardinality(events) = 0 OR $2::text = ANY(events))
  AND (CASE min_severity WHEN 'critical' THEN 2 WHEN 'warning' THEN 1 ELSE 0 END)
      <= (CASE $3::text WHEN 'critical' THEN 2 WHEN 'warning' THEN 1 ELSE 0 END)
FOR KEY SHARE
`

type MatchingChannelsParams struct {
	OrgID    *uuid.UUID `json:"org_id"`
	Kind     string     `json:"kind"`
	Severity string     `json:"severity"`
}

// Emit's channel match (task-3 brief): enabled, org-owned or all_orgs, an
// empty events list or an explicit kind match, and a minSeverity at or
// below the event's own severity. A global event (org_id NULL) matches
// all_orgs channels only: "org_id = NULL" is never true in SQL, so the OR
// falls through to all_orgs alone with no special-casing needed. FOR KEY
// SHARE locks each matched channel row so a concurrent channel delete
// (which takes FOR UPDATE) serializes against this emit instead of racing
// it (global-constraints Locking row).
func (q *Queries) MatchingChannels(ctx context.Context, arg MatchingChannelsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, matchingChannels, arg.OrgID, arg.Kind, arg.Severity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
