// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: rate_ledger.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countLedgerByCA = `-- name: CountLedgerByCA :one
SELECT count(*) FROM rate_ledger
WHERE ca_id = $1 AND kind = $2 AND at > $3
`

type CountLedgerByCAParams struct {
	CaID uuid.UUID `json:"ca_id"`
	Kind string    `json:"kind"`
	At   time.Time `json:"at"`
}

// Counts kind's rows for the whole CA (newOrdersPer3Hours; registered_domain
// is always ” for new_order rows).
func (q *Queries) CountLedgerByCA(ctx context.Context, arg CountLedgerByCAParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLedgerByCA, arg.CaID, arg.Kind, arg.At)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLedgerByDomain = `-- name: CountLedgerByDomain :one
SELECT count(*) FROM rate_ledger
WHERE ca_id = $1 AND kind = $2 AND registered_domain = $3 AND at > $4
`

type CountLedgerByDomainParams struct {
	CaID             uuid.UUID `json:"ca_id"`
	Kind             string    `json:"kind"`
	RegisteredDomain string    `json:"registered_domain"`
	At               time.Time `json:"at"`
}

// Counts kind's rows scoped to one registered domain (certsPerRegistered
// DomainPerWeek, failedValidationsPerHour). CA-wide: not org-scoped. at > $4
// (not >=), fix round 1: a row exactly window-old must not still count, or
// a retry exactly at RetryAt (oldest+window) would wrongly see it blocked
// again.
func (q *Queries) CountLedgerByDomain(ctx context.Context, arg CountLedgerByDomainParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLedgerByDomain,
		arg.CaID,
		arg.Kind,
		arg.RegisteredDomain,
		arg.At,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLedgerByNames = `-- name: CountLedgerByNames :one
SELECT count(*) FROM rate_ledger
WHERE ca_id = $1 AND kind = $2 AND names_hash = $3 AND registered_domain = $4 AND at > $5
`

type CountLedgerByNamesParams struct {
	CaID             uuid.UUID `json:"ca_id"`
	Kind             string    `json:"kind"`
	NamesHash        string    `json:"names_hash"`
	RegisteredDomain string    `json:"registered_domain"`
	At               time.Time `json:"at"`
}

// Counts cert_issued rows for one names_hash, restricted to the registered
// domain that was first (sorted) among the certificate's names, so a
// multi-domain issuance's several per-domain rows are counted once
// (duplicateCertsPerWeek). CA-wide: not org-scoped.
func (q *Queries) CountLedgerByNames(ctx context.Context, arg CountLedgerByNamesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLedgerByNames,
		arg.CaID,
		arg.Kind,
		arg.NamesHash,
		arg.RegisteredDomain,
		arg.At,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertLedgerRow = `-- name: InsertLedgerRow :exec
INSERT INTO rate_ledger (ca_id, kind, registered_domain, names_hash, cert_id, at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertLedgerRowParams struct {
	CaID             uuid.UUID  `json:"ca_id"`
	Kind             string     `json:"kind"`
	RegisteredDomain string     `json:"registered_domain"`
	NamesHash        string     `json:"names_hash"`
	CertID           *uuid.UUID `json:"cert_id"`
	At               time.Time  `json:"at"`
}

// Records one rate-ledger event. new_order rows carry registered_domain=”
// and names_hash=”; cert_issued rows carry one row per registered domain
// of the certificate (same names_hash and cert_id on every row); failed_
// validation rows carry registered_domain alone.
func (q *Queries) InsertLedgerRow(ctx context.Context, arg InsertLedgerRowParams) error {
	_, err := q.db.Exec(ctx, insertLedgerRow,
		arg.CaID,
		arg.Kind,
		arg.RegisteredDomain,
		arg.NamesHash,
		arg.CertID,
		arg.At,
	)
	return err
}

const ledgerDomainsInWindow = `-- name: LedgerDomainsInWindow :many
SELECT DISTINCT rl.registered_domain FROM rate_ledger rl
JOIN certificates c ON c.id = rl.cert_id
WHERE rl.ca_id = $1 AND rl.at > $2 AND c.org_id = $3
ORDER BY rl.registered_domain
`

type LedgerDomainsInWindowParams struct {
	CaID  uuid.UUID `json:"ca_id"`
	At    time.Time `json:"at"`
	OrgID uuid.UUID `json:"org_id"`
}

// The distinct registered domains with any rate-ledger activity in the
// window (fix round 1: every kind, not just cert_issued — a
// failed_validation row carries cert_id too, and a certificate that has
// only ever failed must still be discoverable), scoped to certificates the
// calling org owns (GetRateLedger's item scopes); new_order rows carry no
// cert_id and so never match this join at all. The counts themselves stay
// CA-wide (queried separately, unscoped by org).
func (q *Queries) LedgerDomainsInWindow(ctx context.Context, arg LedgerDomainsInWindowParams) ([]string, error) {
	rows, err := q.db.Query(ctx, ledgerDomainsInWindow, arg.CaID, arg.At, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var registered_domain string
		if err := rows.Scan(&registered_domain); err != nil {
			return nil, err
		}
		items = append(items, registered_domain)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestLedgerByCA = `-- name: OldestLedgerByCA :one
SELECT min(at)::timestamptz FROM rate_ledger
WHERE ca_id = $1 AND kind = $2 AND at > $3
`

type OldestLedgerByCAParams struct {
	CaID uuid.UUID `json:"ca_id"`
	Kind string    `json:"kind"`
	At   time.Time `json:"at"`
}

// OldestLedgerByDomain's counterpart for CountLedgerByCA.
func (q *Queries) OldestLedgerByCA(ctx context.Context, arg OldestLedgerByCAParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, oldestLedgerByCA, arg.CaID, arg.Kind, arg.At)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}

const oldestLedgerByDomain = `-- name: OldestLedgerByDomain :one
SELECT min(at)::timestamptz FROM rate_ledger
WHERE ca_id = $1 AND kind = $2 AND registered_domain = $3 AND at > $4
`

type OldestLedgerByDomainParams struct {
	CaID             uuid.UUID `json:"ca_id"`
	Kind             string    `json:"kind"`
	RegisteredDomain string    `json:"registered_domain"`
	At               time.Time `json:"at"`
}

// The oldest row still inside the window CountLedgerByDomain just counted;
// its limit's RetryAt is this plus the window length. NULL when the count
// is 0.
func (q *Queries) OldestLedgerByDomain(ctx context.Context, arg OldestLedgerByDomainParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, oldestLedgerByDomain,
		arg.CaID,
		arg.Kind,
		arg.RegisteredDomain,
		arg.At,
	)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}

const oldestLedgerByNames = `-- name: OldestLedgerByNames :one
SELECT min(at)::timestamptz FROM rate_ledger
WHERE ca_id = $1 AND kind = $2 AND names_hash = $3 AND registered_domain = $4 AND at > $5
`

type OldestLedgerByNamesParams struct {
	CaID             uuid.UUID `json:"ca_id"`
	Kind             string    `json:"kind"`
	NamesHash        string    `json:"names_hash"`
	RegisteredDomain string    `json:"registered_domain"`
	At               time.Time `json:"at"`
}

// OldestLedgerByDomain's counterpart for CountLedgerByNames.
func (q *Queries) OldestLedgerByNames(ctx context.Context, arg OldestLedgerByNamesParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, oldestLedgerByNames,
		arg.CaID,
		arg.Kind,
		arg.NamesHash,
		arg.RegisteredDomain,
		arg.At,
	)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}

const pruneLedger = `-- name: PruneLedger :execrows
DELETE FROM rate_ledger WHERE at < $1
`

// Deletes rows older than the retention cutoff (now - 30d); run by the
// 5-minute certforge_schedule job.
func (q *Queries) PruneLedger(ctx context.Context, at time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneLedger, at)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
