// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: role_bindings.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRoleBinding = `-- name: CreateRoleBinding :exec
INSERT INTO role_bindings (subject_type, subject, role, org_id, site_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type CreateRoleBindingParams struct {
	SubjectType string     `json:"subject_type"`
	Subject     string     `json:"subject"`
	Role        string     `json:"role"`
	OrgID       *uuid.UUID `json:"org_id"`
	SiteID      *uuid.UUID `json:"site_id"`
}

func (q *Queries) CreateRoleBinding(ctx context.Context, arg CreateRoleBindingParams) error {
	_, err := q.db.Exec(ctx, createRoleBinding,
		arg.SubjectType,
		arg.Subject,
		arg.Role,
		arg.OrgID,
		arg.SiteID,
	)
	return err
}

const deleteRoleBinding = `-- name: DeleteRoleBinding :exec
DELETE FROM role_bindings WHERE id = $1
`

func (q *Queries) DeleteRoleBinding(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoleBinding, id)
	return err
}

const getRoleBinding = `-- name: GetRoleBinding :one
SELECT id, subject_type, subject, role, org_id, site_id, created_at FROM role_bindings WHERE id = $1
`

func (q *Queries) GetRoleBinding(ctx context.Context, id uuid.UUID) (RoleBinding, error) {
	row := q.db.QueryRow(ctx, getRoleBinding, id)
	var i RoleBinding
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.Subject,
		&i.Role,
		&i.OrgID,
		&i.SiteID,
		&i.CreatedAt,
	)
	return i, err
}

const insertRoleBinding = `-- name: InsertRoleBinding :one
INSERT INTO role_bindings (subject_type, subject, role, org_id) VALUES ($1, $2, $3, $4) RETURNING id, subject_type, subject, role, org_id, site_id, created_at
`

type InsertRoleBindingParams struct {
	SubjectType string     `json:"subject_type"`
	Subject     string     `json:"subject"`
	Role        string     `json:"role"`
	OrgID       *uuid.UUID `json:"org_id"`
}

func (q *Queries) InsertRoleBinding(ctx context.Context, arg InsertRoleBindingParams) (RoleBinding, error) {
	row := q.db.QueryRow(ctx, insertRoleBinding,
		arg.SubjectType,
		arg.Subject,
		arg.Role,
		arg.OrgID,
	)
	var i RoleBinding
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.Subject,
		&i.Role,
		&i.OrgID,
		&i.SiteID,
		&i.CreatedAt,
	)
	return i, err
}

const listRoleBindingsForPrincipal = `-- name: ListRoleBindingsForPrincipal :many
SELECT id, subject_type, subject, role, org_id, site_id, created_at FROM role_bindings
WHERE (subject_type = 'user' AND subject = $1::text)
   OR (subject_type = 'oidc_group' AND subject = ANY($2::text[]))
ORDER BY created_at, id
`

type ListRoleBindingsForPrincipalParams struct {
	UserID string   `json:"user_id"`
	Groups []string `json:"groups"`
}

func (q *Queries) ListRoleBindingsForPrincipal(ctx context.Context, arg ListRoleBindingsForPrincipalParams) ([]RoleBinding, error) {
	rows, err := q.db.Query(ctx, listRoleBindingsForPrincipal, arg.UserID, arg.Groups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleBinding{}
	for rows.Next() {
		var i RoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.Subject,
			&i.Role,
			&i.OrgID,
			&i.SiteID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleBindingsForUser = `-- name: ListRoleBindingsForUser :many
SELECT id, subject_type, subject, role, org_id, site_id, created_at FROM role_bindings WHERE subject_type = 'user' AND subject = $1 ORDER BY created_at, id
`

func (q *Queries) ListRoleBindingsForUser(ctx context.Context, subject string) ([]RoleBinding, error) {
	rows, err := q.db.Query(ctx, listRoleBindingsForUser, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleBinding{}
	for rows.Next() {
		var i RoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.Subject,
			&i.Role,
			&i.OrgID,
			&i.SiteID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleBindingsWithLabels = `-- name: ListRoleBindingsWithLabels :many
SELECT rb.id, rb.subject_type, rb.subject, rb.role, rb.org_id, rb.created_at,
       COALESCE(u.display_name, k.name, '')::text AS subject_label
FROM role_bindings rb
LEFT JOIN users u ON rb.subject_type = 'user' AND u.id::text = rb.subject
LEFT JOIN api_keys k ON rb.subject_type = 'apikey' AND k.id::text = rb.subject
WHERE rb.site_id IS NULL
ORDER BY rb.created_at, rb.id
`

type ListRoleBindingsWithLabelsRow struct {
	ID           uuid.UUID  `json:"id"`
	SubjectType  string     `json:"subject_type"`
	Subject      string     `json:"subject"`
	Role         string     `json:"role"`
	OrgID        *uuid.UUID `json:"org_id"`
	CreatedAt    time.Time  `json:"created_at"`
	SubjectLabel string     `json:"subject_label"`
}

func (q *Queries) ListRoleBindingsWithLabels(ctx context.Context) ([]ListRoleBindingsWithLabelsRow, error) {
	rows, err := q.db.Query(ctx, listRoleBindingsWithLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoleBindingsWithLabelsRow{}
	for rows.Next() {
		var i ListRoleBindingsWithLabelsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.Subject,
			&i.Role,
			&i.OrgID,
			&i.CreatedAt,
			&i.SubjectLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGlobalAdminUsers = `-- name: LockGlobalAdminUsers :many
SELECT u.id, u.oidc_issuer, u.oidc_sub, u.email, u.display_name, u.local_password_hash, u.disabled, u.last_login, u.created_at, u.oidc_groups FROM users u
JOIN role_bindings rb ON rb.subject_type = 'user' AND rb.subject = u.id::text
WHERE rb.role = 'admin' AND rb.org_id IS NULL
ORDER BY u.id, rb.id
FOR UPDATE OF u, rb
`

// Users holding a global (org-less) admin role binding, locked in a stable
// order so concurrent callers serialize instead of both reading a stale
// "another admin exists" answer. Locks both the user row and its binding
// row: under READ COMMITTED, only a row an UPDATE actually touches is
// re-checked by a concurrent locker, so locking `u` alone never blocks a
// concurrent DELETE of `rb` (the binding row itself) -- two guarded
// operations could both pass and leave zero enabled global admins.
func (q *Queries) LockGlobalAdminUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, lockGlobalAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.OidcIssuer,
			&i.OidcSub,
			&i.Email,
			&i.DisplayName,
			&i.LocalPasswordHash,
			&i.Disabled,
			&i.LastLogin,
			&i.CreatedAt,
			&i.OidcGroups,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
