// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: role_bindings.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createRoleBinding = `-- name: CreateRoleBinding :exec
INSERT INTO role_bindings (subject_type, subject, role, org_id, site_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type CreateRoleBindingParams struct {
	SubjectType string     `json:"subject_type"`
	Subject     string     `json:"subject"`
	Role        string     `json:"role"`
	OrgID       *uuid.UUID `json:"org_id"`
	SiteID      *uuid.UUID `json:"site_id"`
}

func (q *Queries) CreateRoleBinding(ctx context.Context, arg CreateRoleBindingParams) error {
	_, err := q.db.Exec(ctx, createRoleBinding,
		arg.SubjectType,
		arg.Subject,
		arg.Role,
		arg.OrgID,
		arg.SiteID,
	)
	return err
}

const listRoleBindingsForUser = `-- name: ListRoleBindingsForUser :many
SELECT id, subject_type, subject, role, org_id, site_id, created_at FROM role_bindings WHERE subject_type = 'user' AND subject = $1 ORDER BY created_at, id
`

func (q *Queries) ListRoleBindingsForUser(ctx context.Context, subject string) ([]RoleBinding, error) {
	rows, err := q.db.Query(ctx, listRoleBindingsForUser, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleBinding{}
	for rows.Next() {
		var i RoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.Subject,
			&i.Role,
			&i.OrgID,
			&i.SiteID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
