// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: server_deployments.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const liveServerGrantIDsForCert = `-- name: LiveServerGrantIDsForCert :many
SELECT id FROM client_cert_grants WHERE cert_id = $1 AND removed_at IS NULL AND client_id IS NULL
`

// Dispatcher.OnVersion's own version of LiveGrantIDsForCert: every live
// server grant of cert_id, never agents.Service's.
func (q *Queries) LiveServerGrantIDsForCert(ctx context.Context, certID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, liveServerGrantIDsForCert, certID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveServerGrantsForExtraCert = `-- name: LiveServerGrantsForExtraCert :many
SELECT g.id, ce.current_version_id FROM client_cert_grants g
JOIN output_specs o ON o.id = g.output_spec_id
JOIN certificates ce ON ce.id = g.cert_id
WHERE g.removed_at IS NULL AND g.client_id IS NULL AND $1::uuid = ANY(o.extra_cert_ids)
`

type LiveServerGrantsForExtraCertRow struct {
	ID               uuid.UUID  `json:"id"`
	CurrentVersionID *uuid.UUID `json:"current_version_id"`
}

// Dispatcher.OnVersion's own version of agents' LiveGrantIDsForExtraCert
// (final review finding 5): live server grants whose layout bundles
// cert_id as an extra certificate, with each grant's own certificate's
// current_version_id — the version to redeploy is the grant's own
// certificate's current version, not cert_id's (cert_id here is only the
// extra certificate whose new version triggered this).
func (q *Queries) LiveServerGrantsForExtraCert(ctx context.Context, certID uuid.UUID) ([]LiveServerGrantsForExtraCertRow, error) {
	rows, err := q.db.Query(ctx, liveServerGrantsForExtraCert, certID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LiveServerGrantsForExtraCertRow{}
	for rows.Next() {
		var i LiveServerGrantsForExtraCertRow
		if err := rows.Scan(&i.ID, &i.CurrentVersionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockServerGrantForSweep = `-- name: LockServerGrantForSweep :one
SELECT ce.current_version_id,
       (ce.current_version_id IS NOT NULL
        AND (sd.grant_id IS NULL
             OR sd.version_id IS DISTINCT FROM ce.current_version_id
             OR (sd.status = 'pending' AND sd.updated_at < now() - interval '15 minutes')
             OR (sd.status = 'failed' AND sd.updated_at < now() - interval '6 hours')))::boolean AS stale
FROM client_cert_grants g
JOIN certificates ce ON ce.id = g.cert_id
LEFT JOIN server_deployments sd ON sd.grant_id = g.id
WHERE g.id = $1 AND g.removed_at IS NULL AND g.client_id IS NULL
FOR UPDATE OF ce
`

type LockServerGrantForSweepRow struct {
	CurrentVersionID *uuid.UUID `json:"current_version_id"`
	Stale            bool       `json:"stale"`
}

// SweepDeployments' per-grant re-check, inside its enqueue transaction: locks
// the grant's certificate row (so a concurrent version cannot move
// current_version_id under it) and returns the version as of now plus
// whether the grant is still stale by StaleServerDeployments' own rule.
// No row: the grant was removed (or is client-owned) since the stale read.
func (q *Queries) LockServerGrantForSweep(ctx context.Context, grantID uuid.UUID) (LockServerGrantForSweepRow, error) {
	row := q.db.QueryRow(ctx, lockServerGrantForSweep, grantID)
	var i LockServerGrantForSweepRow
	err := row.Scan(&i.CurrentVersionID, &i.Stale)
	return i, err
}

const markServerDeploymentDeployed = `-- name: MarkServerDeploymentDeployed :exec
UPDATE server_deployments SET status = 'deployed', deployed_at = now(), last_error = '', updated_at = now(),
       state_changed_at = CASE WHEN status IS DISTINCT FROM 'deployed' THEN now() ELSE state_changed_at END
WHERE grant_id = $1 AND version_id = $2 AND deploy_seq = $3
`

type MarkServerDeploymentDeployedParams struct {
	GrantID   uuid.UUID  `json:"grant_id"`
	VersionID *uuid.UUID `json:"version_id"`
	DeploySeq int64      `json:"deploy_seq"`
}

// version_id is additionally checked (batch-5 review): a job for an older
// version that finishes after a newer one has already taken over (pending
// or deployed) must not overwrite server_deployments with stale state —
// Dispatcher.Deploy also checks this before doing any work, so the
// condition here is defense in depth against the same race, not the only
// guard. state_changed_at: same CASE convention as UpsertServerDeploymentPending.
func (q *Queries) MarkServerDeploymentDeployed(ctx context.Context, arg MarkServerDeploymentDeployedParams) error {
	_, err := q.db.Exec(ctx, markServerDeploymentDeployed, arg.GrantID, arg.VersionID, arg.DeploySeq)
	return err
}

const markServerDeploymentFailed = `-- name: MarkServerDeploymentFailed :exec
UPDATE server_deployments SET status = 'failed', last_error = $1, updated_at = now(),
       state_changed_at = CASE WHEN status IS DISTINCT FROM 'failed' THEN now() ELSE state_changed_at END
WHERE grant_id = $2 AND version_id = $3 AND deploy_seq = $4
`

type MarkServerDeploymentFailedParams struct {
	LastError string     `json:"last_error"`
	GrantID   uuid.UUID  `json:"grant_id"`
	VersionID *uuid.UUID `json:"version_id"`
	DeploySeq int64      `json:"deploy_seq"`
}

// last_error is the caller's own redacted, truncated (<=1000 chars) text
// (internal/deploy.Dispatcher); never raw enough to carry a Vault token.
// version_id is checked the same way as MarkServerDeploymentDeployed.
// state_changed_at: same CASE convention (final review fix wave, finding
// 1) — a job that fails repeatedly for the same still-failed status does
// not keep pushing this forward, which is exactly what
// ScanFailedServerDeployments needs to age a persistently-failing
// deployment out of the retention window instead of re-emitting forever.
func (q *Queries) MarkServerDeploymentFailed(ctx context.Context, arg MarkServerDeploymentFailedParams) error {
	_, err := q.db.Exec(ctx, markServerDeploymentFailed,
		arg.LastError,
		arg.GrantID,
		arg.VersionID,
		arg.DeploySeq,
	)
	return err
}

const serverDeployGrant = `-- name: ServerDeployGrant :one
SELECT g.id, g.cert_id, g.deploy_target_id, t.org_id, o.slug AS org_slug, t.type AS target_type, t.config AS target_config,
       t.secret_cfg AS target_secret_cfg, t.name AS target_name,
       ce.name AS certificate_name, ce.common_name AS certificate_common_name, ce.sans AS certificate_sans,
       ce.current_version_id, ol.files AS layout_files, ol.password AS layout_password, ol.extra_cert_ids AS layout_extra_cert_ids,
       sd.version_id AS pending_version_id, sd.deploy_seq AS pending_deploy_seq
FROM client_cert_grants g
JOIN deploy_targets t ON t.id = g.deploy_target_id
JOIN orgs o ON o.id = t.org_id
JOIN certificates ce ON ce.id = g.cert_id
LEFT JOIN output_specs ol ON ol.id = g.output_spec_id
LEFT JOIN server_deployments sd ON sd.grant_id = g.id
WHERE g.id = $1 AND g.client_id IS NULL AND g.removed_at IS NULL
`

type ServerDeployGrantRow struct {
	ID                    uuid.UUID   `json:"id"`
	CertID                uuid.UUID   `json:"cert_id"`
	DeployTargetID        *uuid.UUID  `json:"deploy_target_id"`
	OrgID                 uuid.UUID   `json:"org_id"`
	OrgSlug               string      `json:"org_slug"`
	TargetType            string      `json:"target_type"`
	TargetConfig          []byte      `json:"target_config"`
	TargetSecretCfg       []byte      `json:"target_secret_cfg"`
	TargetName            string      `json:"target_name"`
	CertificateName       string      `json:"certificate_name"`
	CertificateCommonName string      `json:"certificate_common_name"`
	CertificateSans       []string    `json:"certificate_sans"`
	CurrentVersionID      *uuid.UUID  `json:"current_version_id"`
	LayoutFiles           []byte      `json:"layout_files"`
	LayoutPassword        []byte      `json:"layout_password"`
	LayoutExtraCertIds    []uuid.UUID `json:"layout_extra_cert_ids"`
	PendingVersionID      *uuid.UUID  `json:"pending_version_id"`
	PendingDeploySeq      *int64      `json:"pending_deploy_seq"`
}

// Everything DeployWorker needs for one grant_id, in a single round trip:
// the target's type/config and its org's slug, the certificate's identity
// and current version, its layout (if any), and the deployment's own
// pending_version_id (batch-5 review: Dispatcher.Deploy compares this
// against the job's own versionID and bails out, doing nothing, when they
// differ — a stale job for an older version that finishes after a newer
// one has already taken over must never overwrite it). Excludes a removed
// or client-owned grant (pgx.ErrNoRows there means "nothing left to
// deploy", not an error: the worker treats it as done).
// Phase 7A Task 1: t.secret_cfg (a registry Target's Parse needs the
// stored secrets to deploy) and t.name AS target_name (targets.Redact and
// deploy.failed both name the target, never its raw config) are added for
// the registry-driven dispatcher (Task 5).
func (q *Queries) ServerDeployGrant(ctx context.Context, id uuid.UUID) (ServerDeployGrantRow, error) {
	row := q.db.QueryRow(ctx, serverDeployGrant, id)
	var i ServerDeployGrantRow
	err := row.Scan(
		&i.ID,
		&i.CertID,
		&i.DeployTargetID,
		&i.OrgID,
		&i.OrgSlug,
		&i.TargetType,
		&i.TargetConfig,
		&i.TargetSecretCfg,
		&i.TargetName,
		&i.CertificateName,
		&i.CertificateCommonName,
		&i.CertificateSans,
		&i.CurrentVersionID,
		&i.LayoutFiles,
		&i.LayoutPassword,
		&i.LayoutExtraCertIds,
		&i.PendingVersionID,
		&i.PendingDeploySeq,
	)
	return i, err
}

const staleServerDeployments = `-- name: StaleServerDeployments :many
SELECT g.id, ce.current_version_id FROM client_cert_grants g
JOIN certificates ce ON ce.id = g.cert_id
LEFT JOIN server_deployments sd ON sd.grant_id = g.id
WHERE g.removed_at IS NULL AND g.client_id IS NULL AND ce.current_version_id IS NOT NULL
  AND (sd.grant_id IS NULL
       OR sd.version_id IS DISTINCT FROM ce.current_version_id
       OR (sd.status = 'pending' AND sd.updated_at < now() - interval '15 minutes')
       OR (sd.status = 'failed' AND sd.updated_at < now() - interval '6 hours'))
ORDER BY sd.updated_at NULLS FIRST
LIMIT 200
`

type StaleServerDeploymentsRow struct {
	ID               uuid.UUID  `json:"id"`
	CurrentVersionID *uuid.UUID `json:"current_version_id"`
}

// Dispatcher.SweepDeployments' safety net: live server grants whose
// deployment is missing or not on the certificate's current version, or
// that sit pending for over 15 minutes (a dropped river job) or failed for
// over 6 hours (so a permanently failing target is not re-armed every cycle). Bounded.
func (q *Queries) StaleServerDeployments(ctx context.Context) ([]StaleServerDeploymentsRow, error) {
	rows, err := q.db.Query(ctx, staleServerDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaleServerDeploymentsRow{}
	for rows.Next() {
		var i StaleServerDeploymentsRow
		if err := rows.Scan(&i.ID, &i.CurrentVersionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertServerDeploymentPending = `-- name: UpsertServerDeploymentPending :one

INSERT INTO server_deployments (grant_id, version_id, status, last_error, updated_at, state_changed_at, deploy_seq)
VALUES ($1, $2, 'pending', '', now(), now(), 1)
ON CONFLICT (grant_id) DO UPDATE SET version_id = EXCLUDED.version_id, status = 'pending',
       last_error = '', updated_at = now(), deploy_seq = server_deployments.deploy_seq + 1,
       state_changed_at = CASE WHEN server_deployments.status IS DISTINCT FROM 'pending' THEN now() ELSE server_deployments.state_changed_at END
RETURNING deploy_seq
`

type UpsertServerDeploymentPendingParams struct {
	GrantID   uuid.UUID  `json:"grant_id"`
	VersionID *uuid.UUID `json:"version_id"`
}

// server_deployments: a server grant's own deploy state (Task 11), the
// way deployments/agent reports do for an agent-run grant.
// Called whenever a server grant's target version changes (create, a new
// certificate version via Dispatcher.OnVersion, or an explicit redeploy):
// version_id is the version about to be deployed (nil for a certificate
// with no version yet, C3), status resets to pending and any previous
// error is cleared. deployed_at is left untouched (ON CONFLICT's SET list
// omits it): the last successful deploy time survives a new pending cycle.
// state_changed_at (final review fix wave, finding 1) moves with status
// the same way deployments.state_changed_at does — CASE against the row's
// own pre-update status, so a redeploy onto the same still-pending status
// (an OnVersion for a version that never got picked up) does not reset it.
// deploy_seq is bumped on every call and returned: it rides in the job args
// (making a re-enqueue of the same version distinct from a running job) and
// guards both Mark* queries against a stale job.
func (q *Queries) UpsertServerDeploymentPending(ctx context.Context, arg UpsertServerDeploymentPendingParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertServerDeploymentPending, arg.GrantID, arg.VersionID)
	var deploy_seq int64
	err := row.Scan(&deploy_seq)
	return deploy_seq, err
}
