// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: server_deployments.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const liveServerGrantIDsForCert = `-- name: LiveServerGrantIDsForCert :many
SELECT id FROM client_cert_grants WHERE cert_id = $1 AND removed_at IS NULL AND client_id IS NULL
`

// Dispatcher.OnVersion's own version of LiveGrantIDsForCert: every live
// server grant of cert_id, never agents.Service's.
func (q *Queries) LiveServerGrantIDsForCert(ctx context.Context, certID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, liveServerGrantIDsForCert, certID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markServerDeploymentDeployed = `-- name: MarkServerDeploymentDeployed :exec
UPDATE server_deployments SET status = 'deployed', deployed_at = now(), last_error = '', updated_at = now()
WHERE grant_id = $1
`

func (q *Queries) MarkServerDeploymentDeployed(ctx context.Context, grantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markServerDeploymentDeployed, grantID)
	return err
}

const markServerDeploymentFailed = `-- name: MarkServerDeploymentFailed :exec
UPDATE server_deployments SET status = 'failed', last_error = $1, updated_at = now()
WHERE grant_id = $2
`

type MarkServerDeploymentFailedParams struct {
	LastError string    `json:"last_error"`
	GrantID   uuid.UUID `json:"grant_id"`
}

// last_error is the caller's own redacted, truncated (<=1000 chars) text
// (internal/deploy.Dispatcher); never raw enough to carry a Vault token.
func (q *Queries) MarkServerDeploymentFailed(ctx context.Context, arg MarkServerDeploymentFailedParams) error {
	_, err := q.db.Exec(ctx, markServerDeploymentFailed, arg.LastError, arg.GrantID)
	return err
}

const serverDeployGrant = `-- name: ServerDeployGrant :one
SELECT g.id, g.cert_id, g.deploy_target_id, t.org_id, o.slug AS org_slug, t.type AS target_type, t.config AS target_config,
       ce.name AS certificate_name, ce.common_name AS certificate_common_name, ce.sans AS certificate_sans,
       ce.current_version_id, ol.files AS layout_files, ol.password AS layout_password, ol.extra_cert_ids AS layout_extra_cert_ids
FROM client_cert_grants g
JOIN deploy_targets t ON t.id = g.deploy_target_id
JOIN orgs o ON o.id = t.org_id
JOIN certificates ce ON ce.id = g.cert_id
LEFT JOIN output_specs ol ON ol.id = g.output_spec_id
WHERE g.id = $1 AND g.client_id IS NULL AND g.removed_at IS NULL
`

type ServerDeployGrantRow struct {
	ID                    uuid.UUID   `json:"id"`
	CertID                uuid.UUID   `json:"cert_id"`
	DeployTargetID        *uuid.UUID  `json:"deploy_target_id"`
	OrgID                 uuid.UUID   `json:"org_id"`
	OrgSlug               string      `json:"org_slug"`
	TargetType            string      `json:"target_type"`
	TargetConfig          []byte      `json:"target_config"`
	CertificateName       string      `json:"certificate_name"`
	CertificateCommonName string      `json:"certificate_common_name"`
	CertificateSans       []string    `json:"certificate_sans"`
	CurrentVersionID      *uuid.UUID  `json:"current_version_id"`
	LayoutFiles           []byte      `json:"layout_files"`
	LayoutPassword        []byte      `json:"layout_password"`
	LayoutExtraCertIds    []uuid.UUID `json:"layout_extra_cert_ids"`
}

// Everything DeployWorker needs for one grant_id, in a single round trip:
// the target's type/config and its org's slug, the certificate's identity
// and current version, and its layout (if any). Excludes a removed or
// client-owned grant (pgx.ErrNoRows there means "nothing left to deploy",
// not an error: the worker treats it as done).
func (q *Queries) ServerDeployGrant(ctx context.Context, id uuid.UUID) (ServerDeployGrantRow, error) {
	row := q.db.QueryRow(ctx, serverDeployGrant, id)
	var i ServerDeployGrantRow
	err := row.Scan(
		&i.ID,
		&i.CertID,
		&i.DeployTargetID,
		&i.OrgID,
		&i.OrgSlug,
		&i.TargetType,
		&i.TargetConfig,
		&i.CertificateName,
		&i.CertificateCommonName,
		&i.CertificateSans,
		&i.CurrentVersionID,
		&i.LayoutFiles,
		&i.LayoutPassword,
		&i.LayoutExtraCertIds,
	)
	return i, err
}

const upsertServerDeploymentPending = `-- name: UpsertServerDeploymentPending :exec

INSERT INTO server_deployments (grant_id, version_id, status, last_error, updated_at)
VALUES ($1, $2, 'pending', '', now())
ON CONFLICT (grant_id) DO UPDATE SET version_id = EXCLUDED.version_id, status = 'pending',
       last_error = '', updated_at = now()
`

type UpsertServerDeploymentPendingParams struct {
	GrantID   uuid.UUID  `json:"grant_id"`
	VersionID *uuid.UUID `json:"version_id"`
}

// server_deployments: a server grant's own deploy state (Task 11), the
// way deployments/agent reports do for an agent-run grant.
// Called whenever a server grant's target version changes (create, a new
// certificate version via Dispatcher.OnVersion, or an explicit redeploy):
// version_id is the version about to be deployed (nil for a certificate
// with no version yet, C3), status resets to pending and any previous
// error is cleared. deployed_at is left untouched (ON CONFLICT's SET list
// omits it): the last successful deploy time survives a new pending cycle.
func (q *Queries) UpsertServerDeploymentPending(ctx context.Context, arg UpsertServerDeploymentPendingParams) error {
	_, err := q.db.Exec(ctx, upsertServerDeploymentPending, arg.GrantID, arg.VersionID)
	return err
}
