// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, csrf, expires_at) VALUES ($1, $2, $3, $4) RETURNING id, user_id, csrf, expires_at, created_at
`

type CreateSessionParams struct {
	ID        string    `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Csrf      string    `json:"csrf"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Csrf,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Csrf,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= $1::timestamptz
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT id, user_id, csrf, expires_at, created_at FROM sessions WHERE id = $1 AND expires_at > $2::timestamptz
`

type GetActiveSessionParams struct {
	ID  string    `json:"id"`
	Now time.Time `json:"now"`
}

func (q *Queries) GetActiveSession(ctx context.Context, arg GetActiveSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSession, arg.ID, arg.Now)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Csrf,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
