// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: settings.sql

package sqlcgen

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT key, value, secret, updated_at FROM settings WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Secret,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSettingSecret = `-- name: UpsertSettingSecret :exec
INSERT INTO settings (key, secret, updated_at) VALUES ($1, $2, now())
ON CONFLICT (key) DO UPDATE SET secret = EXCLUDED.secret, updated_at = now()
`

type UpsertSettingSecretParams struct {
	Key    string `json:"key"`
	Secret []byte `json:"secret"`
}

func (q *Queries) UpsertSettingSecret(ctx context.Context, arg UpsertSettingSecretParams) error {
	_, err := q.db.Exec(ctx, upsertSettingSecret, arg.Key, arg.Secret)
	return err
}

const upsertSettingValue = `-- name: UpsertSettingValue :exec
INSERT INTO settings (key, value, updated_at) VALUES ($1, $2, now())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
`

type UpsertSettingValueParams struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) UpsertSettingValue(ctx context.Context, arg UpsertSettingValueParams) error {
	_, err := q.db.Exec(ctx, upsertSettingValue, arg.Key, arg.Value)
	return err
}
