// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sites.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createSite = `-- name: CreateSite :one
INSERT INTO sites (org_id, name) VALUES ($1, $2) RETURNING id, org_id, name, created_at
`

type CreateSiteParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Name  string    `json:"name"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite, arg.OrgID, arg.Name)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSite = `-- name: DeleteSite :execrows
DELETE FROM sites WHERE id = $1 AND org_id = $2
`

type DeleteSiteParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteSite(ctx context.Context, arg DeleteSiteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSite, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSite = `-- name: GetSite :one
SELECT id, org_id, name, created_at FROM sites WHERE id = $1 AND org_id = $2
`

type GetSiteParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetSite(ctx context.Context, arg GetSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, getSite, arg.ID, arg.OrgID)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listSites = `-- name: ListSites :many
SELECT id, org_id, name, created_at FROM sites WHERE org_id = $1 ORDER BY lower(name), id
`

func (q *Queries) ListSites(ctx context.Context, orgID uuid.UUID) ([]Site, error) {
	rows, err := q.db.Query(ctx, listSites, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSiteName = `-- name: UpdateSiteName :one
UPDATE sites SET name = $1 WHERE id = $2 AND org_id = $3 RETURNING id, org_id, name, created_at
`

type UpdateSiteNameParams struct {
	Name  string    `json:"name"`
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) UpdateSiteName(ctx context.Context, arg UpdateSiteNameParams) (Site, error) {
	row := q.db.QueryRow(ctx, updateSiteName, arg.Name, arg.ID, arg.OrgID)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
