// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sites.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countSiteClients = `-- name: CountSiteClients :one
SELECT count(*) FROM clients WHERE site_id = $1 AND org_id = $2
`

type CountSiteClientsParams struct {
	SiteID *uuid.UUID `json:"site_id"`
	OrgID  uuid.UUID  `json:"org_id"`
}

func (q *Queries) CountSiteClients(ctx context.Context, arg CountSiteClientsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSiteClients, arg.SiteID, arg.OrgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSite = `-- name: CreateSite :one
INSERT INTO sites (org_id, name) VALUES ($1, $2) RETURNING id, org_id, name, created_at
`

type CreateSiteParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Name  string    `json:"name"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite, arg.OrgID, arg.Name)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSite = `-- name: DeleteSite :execrows
DELETE FROM sites WHERE id = $1 AND org_id = $2
`

type DeleteSiteParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteSite(ctx context.Context, arg DeleteSiteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSite, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSite = `-- name: GetSite :one
SELECT id, org_id, name, created_at FROM sites WHERE id = $1 AND org_id = $2
`

type GetSiteParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetSite(ctx context.Context, arg GetSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, getSite, arg.ID, arg.OrgID)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listSitesWithClientCount = `-- name: ListSitesWithClientCount :many
SELECT s.id, s.org_id, s.name, s.created_at, count(c.id) AS client_count
FROM sites s LEFT JOIN clients c ON c.site_id = s.id AND c.org_id = s.org_id
WHERE s.org_id = $1
GROUP BY s.id
ORDER BY lower(s.name), s.id
`

type ListSitesWithClientCountRow struct {
	ID          uuid.UUID `json:"id"`
	OrgID       uuid.UUID `json:"org_id"`
	Name        string    `json:"name"`
	CreatedAt   time.Time `json:"created_at"`
	ClientCount int64     `json:"client_count"`
}

func (q *Queries) ListSitesWithClientCount(ctx context.Context, orgID uuid.UUID) ([]ListSitesWithClientCountRow, error) {
	rows, err := q.db.Query(ctx, listSitesWithClientCount, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSitesWithClientCountRow{}
	for rows.Next() {
		var i ListSitesWithClientCountRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CreatedAt,
			&i.ClientCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSiteName = `-- name: UpdateSiteName :one
UPDATE sites SET name = $1 WHERE id = $2 AND org_id = $3 RETURNING id, org_id, name, created_at
`

type UpdateSiteNameParams struct {
	Name  string    `json:"name"`
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) UpdateSiteName(ctx context.Context, arg UpdateSiteNameParams) (Site, error) {
	row := q.db.QueryRow(ctx, updateSiteName, arg.Name, arg.ID, arg.OrgID)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
