// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sync.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bumpRedeploySeqs = `-- name: BumpRedeploySeqs :exec
UPDATE client_cert_grants SET redeploy_seq = redeploy_seq + 1, updated_at = now()
WHERE id = ANY($1::uuid[])
`

// Bumped by an explicit Redeploy and by server-side auto-remediation (a
// heartbeat or report drift with auto_remediate): the agent is
// level-triggered on the assignment (versionId, redeploySeq, and the file
// list), never on-disk bytes, so this is what forces a redeploy when
// nothing about the rendered files themselves changed.
func (q *Queries) BumpRedeploySeqs(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, bumpRedeploySeqs, ids)
	return err
}

const clientAssignments = `-- name: ClientAssignments :many
SELECT g.id, g.cert_id, ce.name AS certificate_name, ce.common_name AS certificate_common_name,
       ce.sans AS certificate_sans, g.delivery, g.hook_ids, g.removed_at, g.redeploy_seq,
       d.version_id, d.expected, cv.sha256_fp AS fingerprint, t.type AS target_type, t.config AS target_config,
       t.secret_cfg AS target_secret_cfg
FROM client_cert_grants g
JOIN certificates ce ON ce.id = g.cert_id
JOIN deployments d ON d.grant_id = g.id
LEFT JOIN certificate_versions cv ON cv.id = d.version_id
LEFT JOIN deploy_targets t ON t.id = g.deploy_target_id
WHERE g.client_id = $1
ORDER BY g.created_at, g.id
`

type ClientAssignmentsRow struct {
	ID                    uuid.UUID   `json:"id"`
	CertID                uuid.UUID   `json:"cert_id"`
	CertificateName       string      `json:"certificate_name"`
	CertificateCommonName string      `json:"certificate_common_name"`
	CertificateSans       []string    `json:"certificate_sans"`
	Delivery              string      `json:"delivery"`
	HookIds               []uuid.UUID `json:"hook_ids"`
	RemovedAt             *time.Time  `json:"removed_at"`
	RedeploySeq           int64       `json:"redeploy_seq"`
	VersionID             *uuid.UUID  `json:"version_id"`
	Expected              []byte      `json:"expected"`
	Fingerprint           *string     `json:"fingerprint"`
	TargetType            *string     `json:"target_type"`
	TargetConfig          []byte      `json:"target_config"`
	TargetSecretCfg       []byte      `json:"target_secret_cfg"`
}

// t.secret_cfg AS target_secret_cfg (Phase 7A Task 6): agents.Service.Assignments
// opens it and merges it back into the target's public config
// (targets.Merge) before sending Target.Config to the agent — the same
// fully resolved shape a server-side Request.Config carries
// (Dispatcher.Deploy) — so a registry-driven FileTarget's Files/Paths/
// Reload see any secret fields it has, not just traefik/vault-kv's own
// (neither has one today).
func (q *Queries) ClientAssignments(ctx context.Context, clientID *uuid.UUID) ([]ClientAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, clientAssignments, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClientAssignmentsRow{}
	for rows.Next() {
		var i ClientAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CertID,
			&i.CertificateName,
			&i.CertificateCommonName,
			&i.CertificateSans,
			&i.Delivery,
			&i.HookIds,
			&i.RemovedAt,
			&i.RedeploySeq,
			&i.VersionID,
			&i.Expected,
			&i.Fingerprint,
			&i.TargetType,
			&i.TargetConfig,
			&i.TargetSecretCfg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clientDeployments = `-- name: ClientDeployments :many
SELECT g.id AS grant_id, g.cert_id, g.delivery, g.auto_remediate, g.removed_at, g.removed_revision, d.state, d.version_id, d.expected
FROM client_cert_grants g JOIN deployments d ON d.grant_id = g.id
WHERE g.client_id = $1
ORDER BY g.id
FOR UPDATE OF d
`

type ClientDeploymentsRow struct {
	GrantID         uuid.UUID  `json:"grant_id"`
	CertID          uuid.UUID  `json:"cert_id"`
	Delivery        string     `json:"delivery"`
	AutoRemediate   bool       `json:"auto_remediate"`
	RemovedAt       *time.Time `json:"removed_at"`
	RemovedRevision int64      `json:"removed_revision"`
	State           string     `json:"state"`
	VersionID       *uuid.UUID `json:"version_id"`
	Expected        []byte     `json:"expected"`
}

func (q *Queries) ClientDeployments(ctx context.Context, clientID *uuid.UUID) ([]ClientDeploymentsRow, error) {
	rows, err := q.db.Query(ctx, clientDeployments, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClientDeploymentsRow{}
	for rows.Next() {
		var i ClientDeploymentsRow
		if err := rows.Scan(
			&i.GrantID,
			&i.CertID,
			&i.Delivery,
			&i.AutoRemediate,
			&i.RemovedAt,
			&i.RemovedRevision,
			&i.State,
			&i.VersionID,
			&i.Expected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantForBundle = `-- name: GrantForBundle :one
SELECT g.id, g.cert_id, ce.name AS certificate_name, d.version_id, o.files AS layout_files,
       o.password AS layout_password, o.extra_cert_ids AS layout_extra_cert_ids, d.extra_version_ids,
       t.type AS target_type
FROM client_cert_grants g
JOIN certificates ce ON ce.id = g.cert_id
JOIN deployments d ON d.grant_id = g.id
LEFT JOIN output_specs o ON o.id = g.output_spec_id
LEFT JOIN deploy_targets t ON t.id = g.deploy_target_id
WHERE g.id = $1 AND g.client_id = $2 AND g.removed_at IS NULL
`

type GrantForBundleParams struct {
	ID       uuid.UUID  `json:"id"`
	ClientID *uuid.UUID `json:"client_id"`
}

type GrantForBundleRow struct {
	ID                 uuid.UUID   `json:"id"`
	CertID             uuid.UUID   `json:"cert_id"`
	CertificateName    string      `json:"certificate_name"`
	VersionID          *uuid.UUID  `json:"version_id"`
	LayoutFiles        []byte      `json:"layout_files"`
	LayoutPassword     []byte      `json:"layout_password"`
	LayoutExtraCertIds []uuid.UUID `json:"layout_extra_cert_ids"`
	ExtraVersionIds    []uuid.UUID `json:"extra_version_ids"`
	TargetType         *string     `json:"target_type"`
}

// extra_version_ids (from the deployment, the last render) pairs with
// layout_extra_cert_ids (from the layout, live) to render the bundle from
// the versions actually last rendered, never the extra certificates'
// current versions: see agents.Service.Bundle.
func (q *Queries) GrantForBundle(ctx context.Context, arg GrantForBundleParams) (GrantForBundleRow, error) {
	row := q.db.QueryRow(ctx, grantForBundle, arg.ID, arg.ClientID)
	var i GrantForBundleRow
	err := row.Scan(
		&i.ID,
		&i.CertID,
		&i.CertificateName,
		&i.VersionID,
		&i.LayoutFiles,
		&i.LayoutPassword,
		&i.LayoutExtraCertIds,
		&i.ExtraVersionIds,
		&i.TargetType,
	)
	return i, err
}

const hooksByIDs = `-- name: HooksByIDs :many
SELECT id, phase, argv, timeout_seconds FROM hooks WHERE id = ANY($1::uuid[])
`

type HooksByIDsRow struct {
	ID             uuid.UUID `json:"id"`
	Phase          string    `json:"phase"`
	Argv           []string  `json:"argv"`
	TimeoutSeconds int32     `json:"timeout_seconds"`
}

func (q *Queries) HooksByIDs(ctx context.Context, ids []uuid.UUID) ([]HooksByIDsRow, error) {
	rows, err := q.db.Query(ctx, hooksByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HooksByIDsRow{}
	for rows.Next() {
		var i HooksByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Phase,
			&i.Argv,
			&i.TimeoutSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertHookRun = `-- name: InsertHookRun :exec
INSERT INTO hook_runs (client_id, grant_id, hook_id, phase, argv, exit_code, duration_ms, stdout, stderr)
VALUES ($1, $2::uuid,
        (SELECT h.id FROM hooks h
         WHERE h.id = $3::uuid AND h.org_id = $4
           AND EXISTS (SELECT 1 FROM client_cert_grants g WHERE g.id = $2::uuid AND h.id = ANY(g.hook_ids))),
        $5, $6::text[], $7, $8, $9, $10)
`

type InsertHookRunParams struct {
	ClientID   uuid.UUID `json:"client_id"`
	GrantID    uuid.UUID `json:"grant_id"`
	HookID     uuid.UUID `json:"hook_id"`
	OrgID      uuid.UUID `json:"org_id"`
	Phase      string    `json:"phase"`
	Argv       []string  `json:"argv"`
	ExitCode   int32     `json:"exit_code"`
	DurationMs int64     `json:"duration_ms"`
	Stdout     string    `json:"stdout"`
	Stderr     string    `json:"stderr"`
}

// hook_id is kept only when the agent-supplied id is one of the grant's own
// hooks in the client's org; anything else is stored as NULL so a foreign
// hook's name can never show up in this org's hook run history.
func (q *Queries) InsertHookRun(ctx context.Context, arg InsertHookRunParams) error {
	_, err := q.db.Exec(ctx, insertHookRun,
		arg.ClientID,
		arg.GrantID,
		arg.HookID,
		arg.OrgID,
		arg.Phase,
		arg.Argv,
		arg.ExitCode,
		arg.DurationMs,
		arg.Stdout,
		arg.Stderr,
	)
	return err
}

const listHookRuns = `-- name: ListHookRuns :many
SELECT r.id, r.client_id, r.grant_id, r.hook_id, r.phase, r.argv, r.exit_code, r.duration_ms, r.stdout, r.stderr, r.ran_at,
       COALESCE(h.name, '')::text AS hook_name
FROM hook_runs r LEFT JOIN hooks h ON h.id = r.hook_id
WHERE r.client_id = $1
  AND (NOT $2::bool OR (r.ran_at, r.id) < ($3::timestamptz, $4::uuid))
ORDER BY r.ran_at DESC, r.id DESC
LIMIT $5::int
`

type ListHookRunsParams struct {
	ClientID  uuid.UUID `json:"client_id"`
	HasCursor bool      `json:"has_cursor"`
	BeforeTs  time.Time `json:"before_ts"`
	BeforeID  uuid.UUID `json:"before_id"`
	PageLimit int32     `json:"page_limit"`
}

type ListHookRunsRow struct {
	ID         uuid.UUID  `json:"id"`
	ClientID   uuid.UUID  `json:"client_id"`
	GrantID    *uuid.UUID `json:"grant_id"`
	HookID     *uuid.UUID `json:"hook_id"`
	Phase      string     `json:"phase"`
	Argv       []string   `json:"argv"`
	ExitCode   int32      `json:"exit_code"`
	DurationMs int64      `json:"duration_ms"`
	Stdout     string     `json:"stdout"`
	Stderr     string     `json:"stderr"`
	RanAt      time.Time  `json:"ran_at"`
	HookName   string     `json:"hook_name"`
}

func (q *Queries) ListHookRuns(ctx context.Context, arg ListHookRunsParams) ([]ListHookRunsRow, error) {
	rows, err := q.db.Query(ctx, listHookRuns,
		arg.ClientID,
		arg.HasCursor,
		arg.BeforeTs,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHookRunsRow{}
	for rows.Next() {
		var i ListHookRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.GrantID,
			&i.HookID,
			&i.Phase,
			&i.Argv,
			&i.ExitCode,
			&i.DurationMs,
			&i.Stdout,
			&i.Stderr,
			&i.RanAt,
			&i.HookName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneHookRuns = `-- name: PruneHookRuns :execrows
DELETE FROM hook_runs WHERE ran_at < $1
`

// Deletes hook runs older than the retention cutoff; run by the 5-minute
// certforge_schedule job.
func (q *Queries) PruneHookRuns(ctx context.Context, ranAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneHookRuns, ranAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAppliedRevision = `-- name: SetAppliedRevision :exec
UPDATE clients SET applied_revision = GREATEST(applied_revision, LEAST($1::bigint, desired_revision)),
       last_seen = now()
WHERE id = $2
`

type SetAppliedRevisionParams struct {
	Revision int64     `json:"revision"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) SetAppliedRevision(ctx context.Context, arg SetAppliedRevisionParams) error {
	_, err := q.db.Exec(ctx, setAppliedRevision, arg.Revision, arg.ID)
	return err
}

const setDeploymentState = `-- name: SetDeploymentState :exec
UPDATE deployments SET state = $1, installed = $2, error = $3,
       reported_at = now(), updated_at = now(),
       state_changed_at = CASE WHEN state IS DISTINCT FROM $1 THEN now() ELSE state_changed_at END
WHERE grant_id = $4
`

type SetDeploymentStateParams struct {
	State     string    `json:"state"`
	Installed []byte    `json:"installed"`
	Error     string    `json:"error"`
	GrantID   uuid.UUID `json:"grant_id"`
}

// state_changed_at (final review fix wave, finding 1) moves only when
// state actually transitions — the CASE compares against the row's own
// pre-update state, which Postgres evaluates every SET expression
// against regardless of clause order. updated_at still moves on every
// report (agents.sync's own staleness/ordering uses it); the two are
// deliberately no longer the same signal.
func (q *Queries) SetDeploymentState(ctx context.Context, arg SetDeploymentStateParams) error {
	_, err := q.db.Exec(ctx, setDeploymentState,
		arg.State,
		arg.Installed,
		arg.Error,
		arg.GrantID,
	)
	return err
}

const touchClient = `-- name: TouchClient :exec
UPDATE clients SET last_seen = now() WHERE id = $1
`

func (q *Queries) TouchClient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchClient, id)
	return err
}
