/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppNoOrganizationRouteImport } from './routes/_app/no-organization'
import { Route as AppOOrgRouteRouteImport } from './routes/_app/o/$org/route'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsSectionRouteImport } from './routes/_app/settings/$section'
import { Route as AppOOrgIndexRouteImport } from './routes/_app/o/$org/index'
import { Route as AppOOrgAuditRouteImport } from './routes/_app/o/$org/audit'
import { Route as AppOOrgIssuersRouteRouteImport } from './routes/_app/o/$org/issuers/route'
import { Route as AppOOrgOverviewRouteImport } from './routes/_app/o/$org/overview'
import { Route as AppOOrgCertificatesIndexRouteImport } from './routes/_app/o/$org/certificates/index'
import { Route as AppOOrgCertificatesNewRouteImport } from './routes/_app/o/$org/certificates/new'
import { Route as AppOOrgClientsIndexRouteImport } from './routes/_app/o/$org/clients/index'
import { Route as AppOOrgClientsNewRouteImport } from './routes/_app/o/$org/clients/new'
import { Route as AppOOrgIssuersIndexRouteImport } from './routes/_app/o/$org/issuers/index'
import { Route as AppOOrgIssuersAccountsRouteImport } from './routes/_app/o/$org/issuers/accounts'
import { Route as AppOOrgIssuersCasRouteImport } from './routes/_app/o/$org/issuers/cas'
import { Route as AppOOrgIssuersDnsRouteImport } from './routes/_app/o/$org/issuers/dns'
import { Route as AppOOrgCertificatesIdIndexRouteImport } from './routes/_app/o/$org/certificates/$id/index'
import { Route as AppOOrgCertificatesIdTabRouteImport } from './routes/_app/o/$org/certificates/$id/$tab'
import { Route as AppOOrgCertificatesIdEditRouteImport } from './routes/_app/o/$org/certificates/$id/edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppNoOrganizationRoute = AppNoOrganizationRouteImport.update({
  id: '/no-organization',
  path: '/no-organization',
  getParentRoute: () => AppRoute,
} as any)
const AppOOrgRouteRoute = AppOOrgRouteRouteImport.update({
  id: '/o/$org',
  path: '/o/$org',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSectionRoute = AppSettingsSectionRouteImport.update({
  id: '/settings/$section',
  path: '/settings/$section',
  getParentRoute: () => AppRoute,
} as any)
const AppOOrgIndexRoute = AppOOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOOrgRouteRoute,
} as any)
const AppOOrgAuditRoute = AppOOrgAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppOOrgRouteRoute,
} as any)
const AppOOrgIssuersRouteRoute = AppOOrgIssuersRouteRouteImport.update({
  id: '/issuers',
  path: '/issuers',
  getParentRoute: () => AppOOrgRouteRoute,
} as any)
const AppOOrgOverviewRoute = AppOOrgOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppOOrgRouteRoute,
} as any)
const AppOOrgCertificatesIndexRoute =
  AppOOrgCertificatesIndexRouteImport.update({
    id: '/certificates/',
    path: '/certificates/',
    getParentRoute: () => AppOOrgRouteRoute,
  } as any)
const AppOOrgCertificatesNewRoute = AppOOrgCertificatesNewRouteImport.update({
  id: '/certificates/new',
  path: '/certificates/new',
  getParentRoute: () => AppOOrgRouteRoute,
} as any)
const AppOOrgClientsIndexRoute = AppOOrgClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppOOrgRouteRoute,
} as any)
const AppOOrgClientsNewRoute = AppOOrgClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AppOOrgRouteRoute,
} as any)
const AppOOrgIssuersIndexRoute = AppOOrgIssuersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOOrgIssuersRouteRoute,
} as any)
const AppOOrgIssuersAccountsRoute = AppOOrgIssuersAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppOOrgIssuersRouteRoute,
} as any)
const AppOOrgIssuersCasRoute = AppOOrgIssuersCasRouteImport.update({
  id: '/cas',
  path: '/cas',
  getParentRoute: () => AppOOrgIssuersRouteRoute,
} as any)
const AppOOrgIssuersDnsRoute = AppOOrgIssuersDnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => AppOOrgIssuersRouteRoute,
} as any)
const AppOOrgCertificatesIdIndexRoute =
  AppOOrgCertificatesIdIndexRouteImport.update({
    id: '/certificates/$id/',
    path: '/certificates/$id/',
    getParentRoute: () => AppOOrgRouteRoute,
  } as any)
const AppOOrgCertificatesIdTabRoute =
  AppOOrgCertificatesIdTabRouteImport.update({
    id: '/certificates/$id/$tab',
    path: '/certificates/$id/$tab',
    getParentRoute: () => AppOOrgRouteRoute,
  } as any)
const AppOOrgCertificatesIdEditRoute =
  AppOOrgCertificatesIdEditRouteImport.update({
    id: '/certificates/$id/edit',
    path: '/certificates/$id/edit',
    getParentRoute: () => AppOOrgRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/no-organization': typeof AppNoOrganizationRoute
  '/o/$org': typeof AppOOrgRouteRouteWithChildren
  '/settings/$section': typeof AppSettingsSectionRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/o/$org/issuers': typeof AppOOrgIssuersRouteRouteWithChildren
  '/o/$org/audit': typeof AppOOrgAuditRoute
  '/o/$org/overview': typeof AppOOrgOverviewRoute
  '/o/$org/': typeof AppOOrgIndexRoute
  '/o/$org/certificates/new': typeof AppOOrgCertificatesNewRoute
  '/o/$org/clients/new': typeof AppOOrgClientsNewRoute
  '/o/$org/issuers/accounts': typeof AppOOrgIssuersAccountsRoute
  '/o/$org/issuers/cas': typeof AppOOrgIssuersCasRoute
  '/o/$org/issuers/dns': typeof AppOOrgIssuersDnsRoute
  '/o/$org/certificates/': typeof AppOOrgCertificatesIndexRoute
  '/o/$org/clients/': typeof AppOOrgClientsIndexRoute
  '/o/$org/issuers/': typeof AppOOrgIssuersIndexRoute
  '/o/$org/certificates/$id/$tab': typeof AppOOrgCertificatesIdTabRoute
  '/o/$org/certificates/$id/edit': typeof AppOOrgCertificatesIdEditRoute
  '/o/$org/certificates/$id/': typeof AppOOrgCertificatesIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/no-organization': typeof AppNoOrganizationRoute
  '/': typeof AppIndexRoute
  '/settings/$section': typeof AppSettingsSectionRoute
  '/settings': typeof AppSettingsIndexRoute
  '/o/$org/audit': typeof AppOOrgAuditRoute
  '/o/$org/overview': typeof AppOOrgOverviewRoute
  '/o/$org': typeof AppOOrgIndexRoute
  '/o/$org/certificates/new': typeof AppOOrgCertificatesNewRoute
  '/o/$org/clients/new': typeof AppOOrgClientsNewRoute
  '/o/$org/issuers/accounts': typeof AppOOrgIssuersAccountsRoute
  '/o/$org/issuers/cas': typeof AppOOrgIssuersCasRoute
  '/o/$org/issuers/dns': typeof AppOOrgIssuersDnsRoute
  '/o/$org/certificates': typeof AppOOrgCertificatesIndexRoute
  '/o/$org/clients': typeof AppOOrgClientsIndexRoute
  '/o/$org/issuers': typeof AppOOrgIssuersIndexRoute
  '/o/$org/certificates/$id/$tab': typeof AppOOrgCertificatesIdTabRoute
  '/o/$org/certificates/$id/edit': typeof AppOOrgCertificatesIdEditRoute
  '/o/$org/certificates/$id': typeof AppOOrgCertificatesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/no-organization': typeof AppNoOrganizationRoute
  '/_app/': typeof AppIndexRoute
  '/_app/o/$org': typeof AppOOrgRouteRouteWithChildren
  '/_app/settings/$section': typeof AppSettingsSectionRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/o/$org/issuers': typeof AppOOrgIssuersRouteRouteWithChildren
  '/_app/o/$org/audit': typeof AppOOrgAuditRoute
  '/_app/o/$org/overview': typeof AppOOrgOverviewRoute
  '/_app/o/$org/': typeof AppOOrgIndexRoute
  '/_app/o/$org/certificates/new': typeof AppOOrgCertificatesNewRoute
  '/_app/o/$org/clients/new': typeof AppOOrgClientsNewRoute
  '/_app/o/$org/issuers/accounts': typeof AppOOrgIssuersAccountsRoute
  '/_app/o/$org/issuers/cas': typeof AppOOrgIssuersCasRoute
  '/_app/o/$org/issuers/dns': typeof AppOOrgIssuersDnsRoute
  '/_app/o/$org/certificates/': typeof AppOOrgCertificatesIndexRoute
  '/_app/o/$org/clients/': typeof AppOOrgClientsIndexRoute
  '/_app/o/$org/issuers/': typeof AppOOrgIssuersIndexRoute
  '/_app/o/$org/certificates/$id/$tab': typeof AppOOrgCertificatesIdTabRoute
  '/_app/o/$org/certificates/$id/edit': typeof AppOOrgCertificatesIdEditRoute
  '/_app/o/$org/certificates/$id/': typeof AppOOrgCertificatesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/no-organization'
    | '/o/$org'
    | '/settings/$section'
    | '/settings/'
    | '/o/$org/issuers'
    | '/o/$org/audit'
    | '/o/$org/overview'
    | '/o/$org/'
    | '/o/$org/certificates/new'
    | '/o/$org/clients/new'
    | '/o/$org/issuers/accounts'
    | '/o/$org/issuers/cas'
    | '/o/$org/issuers/dns'
    | '/o/$org/certificates/'
    | '/o/$org/clients/'
    | '/o/$org/issuers/'
    | '/o/$org/certificates/$id/$tab'
    | '/o/$org/certificates/$id/edit'
    | '/o/$org/certificates/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/no-organization'
    | '/'
    | '/settings/$section'
    | '/settings'
    | '/o/$org/audit'
    | '/o/$org/overview'
    | '/o/$org'
    | '/o/$org/certificates/new'
    | '/o/$org/clients/new'
    | '/o/$org/issuers/accounts'
    | '/o/$org/issuers/cas'
    | '/o/$org/issuers/dns'
    | '/o/$org/certificates'
    | '/o/$org/clients'
    | '/o/$org/issuers'
    | '/o/$org/certificates/$id/$tab'
    | '/o/$org/certificates/$id/edit'
    | '/o/$org/certificates/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/no-organization'
    | '/_app/'
    | '/_app/o/$org'
    | '/_app/settings/$section'
    | '/_app/settings/'
    | '/_app/o/$org/issuers'
    | '/_app/o/$org/audit'
    | '/_app/o/$org/overview'
    | '/_app/o/$org/'
    | '/_app/o/$org/certificates/new'
    | '/_app/o/$org/clients/new'
    | '/_app/o/$org/issuers/accounts'
    | '/_app/o/$org/issuers/cas'
    | '/_app/o/$org/issuers/dns'
    | '/_app/o/$org/certificates/'
    | '/_app/o/$org/clients/'
    | '/_app/o/$org/issuers/'
    | '/_app/o/$org/certificates/$id/$tab'
    | '/_app/o/$org/certificates/$id/edit'
    | '/_app/o/$org/certificates/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/no-organization': {
      id: '/_app/no-organization'
      path: '/no-organization'
      fullPath: '/no-organization'
      preLoaderRoute: typeof AppNoOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/o/$org': {
      id: '/_app/o/$org'
      path: '/o/$org'
      fullPath: '/o/$org'
      preLoaderRoute: typeof AppOOrgRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/$section': {
      id: '/_app/settings/$section'
      path: '/settings/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof AppSettingsSectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/o/$org/': {
      id: '/_app/o/$org/'
      path: '/'
      fullPath: '/o/$org/'
      preLoaderRoute: typeof AppOOrgIndexRouteImport
      parentRoute: typeof AppOOrgRouteRoute
    }
    '/_app/o/$org/audit': {
      id: '/_app/o/$org/audit'
      path: '/audit'
      fullPath: '/o/$org/audit'
      preLoaderRoute: typeof AppOOrgAuditRouteImport
      parentRoute: typeof AppOOrgRouteRoute
    }
    '/_app/o/$org/issuers': {
      id: '/_app/o/$org/issuers'
      path: '/issuers'
      fullPath: '/o/$org/issuers'
      preLoaderRoute: typeof AppOOrgIssuersRouteRouteImport
      parentRoute: typeof AppOOrgRouteRoute
    }
    '/_app/o/$org/overview': {
      id: '/_app/o/$org/overview'
      path: '/overview'
      fullPath: '/o/$org/overview'
      preLoaderRoute: typeof AppOOrgOverviewRouteImport
      parentRoute: typeof AppOOrgRouteRoute
    }
    '/_app/o/$org/certificates/': {
      id: '/_app/o/$org/certificates/'
      path: '/certificates'
      fullPath: '/o/$org/certificates/'
      preLoaderRoute: typeof AppOOrgCertificatesIndexRouteImport
      parentRoute: typeof AppOOrgRouteRoute
    }
    '/_app/o/$org/certificates/new': {
      id: '/_app/o/$org/certificates/new'
      path: '/certificates/new'
      fullPath: '/o/$org/certificates/new'
      preLoaderRoute: typeof AppOOrgCertificatesNewRouteImport
      parentRoute: typeof AppOOrgRouteRoute
    }
    '/_app/o/$org/clients/': {
      id: '/_app/o/$org/clients/'
      path: '/clients'
      fullPath: '/o/$org/clients/'
      preLoaderRoute: typeof AppOOrgClientsIndexRouteImport
      parentRoute: typeof AppOOrgRouteRoute
    }
    '/_app/o/$org/clients/new': {
      id: '/_app/o/$org/clients/new'
      path: '/clients/new'
      fullPath: '/o/$org/clients/new'
      preLoaderRoute: typeof AppOOrgClientsNewRouteImport
      parentRoute: typeof AppOOrgRouteRoute
    }
    '/_app/o/$org/issuers/': {
      id: '/_app/o/$org/issuers/'
      path: '/'
      fullPath: '/o/$org/issuers/'
      preLoaderRoute: typeof AppOOrgIssuersIndexRouteImport
      parentRoute: typeof AppOOrgIssuersRouteRoute
    }
    '/_app/o/$org/issuers/accounts': {
      id: '/_app/o/$org/issuers/accounts'
      path: '/accounts'
      fullPath: '/o/$org/issuers/accounts'
      preLoaderRoute: typeof AppOOrgIssuersAccountsRouteImport
      parentRoute: typeof AppOOrgIssuersRouteRoute
    }
    '/_app/o/$org/issuers/cas': {
      id: '/_app/o/$org/issuers/cas'
      path: '/cas'
      fullPath: '/o/$org/issuers/cas'
      preLoaderRoute: typeof AppOOrgIssuersCasRouteImport
      parentRoute: typeof AppOOrgIssuersRouteRoute
    }
    '/_app/o/$org/issuers/dns': {
      id: '/_app/o/$org/issuers/dns'
      path: '/dns'
      fullPath: '/o/$org/issuers/dns'
      preLoaderRoute: typeof AppOOrgIssuersDnsRouteImport
      parentRoute: typeof AppOOrgIssuersRouteRoute
    }
    '/_app/o/$org/certificates/$id/': {
      id: '/_app/o/$org/certificates/$id/'
      path: '/certificates/$id'
      fullPath: '/o/$org/certificates/$id/'
      preLoaderRoute: typeof AppOOrgCertificatesIdIndexRouteImport
      parentRoute: typeof AppOOrgRouteRoute
    }
    '/_app/o/$org/certificates/$id/$tab': {
      id: '/_app/o/$org/certificates/$id/$tab'
      path: '/certificates/$id/$tab'
      fullPath: '/o/$org/certificates/$id/$tab'
      preLoaderRoute: typeof AppOOrgCertificatesIdTabRouteImport
      parentRoute: typeof AppOOrgRouteRoute
    }
    '/_app/o/$org/certificates/$id/edit': {
      id: '/_app/o/$org/certificates/$id/edit'
      path: '/certificates/$id/edit'
      fullPath: '/o/$org/certificates/$id/edit'
      preLoaderRoute: typeof AppOOrgCertificatesIdEditRouteImport
      parentRoute: typeof AppOOrgRouteRoute
    }
  }
}

interface AppOOrgIssuersRouteRouteChildren {
  AppOOrgIssuersAccountsRoute: typeof AppOOrgIssuersAccountsRoute
  AppOOrgIssuersCasRoute: typeof AppOOrgIssuersCasRoute
  AppOOrgIssuersDnsRoute: typeof AppOOrgIssuersDnsRoute
  AppOOrgIssuersIndexRoute: typeof AppOOrgIssuersIndexRoute
}

const AppOOrgIssuersRouteRouteChildren: AppOOrgIssuersRouteRouteChildren = {
  AppOOrgIssuersAccountsRoute: AppOOrgIssuersAccountsRoute,
  AppOOrgIssuersCasRoute: AppOOrgIssuersCasRoute,
  AppOOrgIssuersDnsRoute: AppOOrgIssuersDnsRoute,
  AppOOrgIssuersIndexRoute: AppOOrgIssuersIndexRoute,
}

const AppOOrgIssuersRouteRouteWithChildren =
  AppOOrgIssuersRouteRoute._addFileChildren(AppOOrgIssuersRouteRouteChildren)

interface AppOOrgRouteRouteChildren {
  AppOOrgIssuersRouteRoute: typeof AppOOrgIssuersRouteRouteWithChildren
  AppOOrgAuditRoute: typeof AppOOrgAuditRoute
  AppOOrgOverviewRoute: typeof AppOOrgOverviewRoute
  AppOOrgIndexRoute: typeof AppOOrgIndexRoute
  AppOOrgCertificatesNewRoute: typeof AppOOrgCertificatesNewRoute
  AppOOrgClientsNewRoute: typeof AppOOrgClientsNewRoute
  AppOOrgCertificatesIndexRoute: typeof AppOOrgCertificatesIndexRoute
  AppOOrgClientsIndexRoute: typeof AppOOrgClientsIndexRoute
  AppOOrgCertificatesIdTabRoute: typeof AppOOrgCertificatesIdTabRoute
  AppOOrgCertificatesIdEditRoute: typeof AppOOrgCertificatesIdEditRoute
  AppOOrgCertificatesIdIndexRoute: typeof AppOOrgCertificatesIdIndexRoute
}

const AppOOrgRouteRouteChildren: AppOOrgRouteRouteChildren = {
  AppOOrgIssuersRouteRoute: AppOOrgIssuersRouteRouteWithChildren,
  AppOOrgAuditRoute: AppOOrgAuditRoute,
  AppOOrgOverviewRoute: AppOOrgOverviewRoute,
  AppOOrgIndexRoute: AppOOrgIndexRoute,
  AppOOrgCertificatesNewRoute: AppOOrgCertificatesNewRoute,
  AppOOrgClientsNewRoute: AppOOrgClientsNewRoute,
  AppOOrgCertificatesIndexRoute: AppOOrgCertificatesIndexRoute,
  AppOOrgClientsIndexRoute: AppOOrgClientsIndexRoute,
  AppOOrgCertificatesIdTabRoute: AppOOrgCertificatesIdTabRoute,
  AppOOrgCertificatesIdEditRoute: AppOOrgCertificatesIdEditRoute,
  AppOOrgCertificatesIdIndexRoute: AppOOrgCertificatesIdIndexRoute,
}

const AppOOrgRouteRouteWithChildren = AppOOrgRouteRoute._addFileChildren(
  AppOOrgRouteRouteChildren,
)

interface AppRouteChildren {
  AppNoOrganizationRoute: typeof AppNoOrganizationRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOOrgRouteRoute: typeof AppOOrgRouteRouteWithChildren
  AppSettingsSectionRoute: typeof AppSettingsSectionRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNoOrganizationRoute: AppNoOrganizationRoute,
  AppIndexRoute: AppIndexRoute,
  AppOOrgRouteRoute: AppOOrgRouteRouteWithChildren,
  AppSettingsSectionRoute: AppSettingsSectionRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
